---
title: "粒子フィルターの連続極限"
subtitle: "どんな過程が現れるか？"
author: "司馬 博文"
date: 1/23/2024
date-modified: 2/12/2024
categories: [Particles, Process]
toc: true
number-sections: true
code-block-bg: true
code-block-border-left: "#5AB5BA"
code-overflow: wrap
code-fold: true
bibliography: 
    - ../../../assets/2023.bib
    - ../../../assets/2024.bib
csl: ../../../assets/apalike.csl
crossref:
    sec-prefix: 節
    eq-prefix: 式
    def-prefix: 定義
    def-title: 定義
    thm-prefix: 定理
    thm-title: 定理
    fig-prefix: 図
    fig-title: 図
abstract-title: 概要
abstract: 粒子フィルターを拡散過程に対して適用することを考える．拡散過程の Euler-Maruyama 離散化に対して構成された粒子フィルターの，タイムステップを $0$ にする極限 $\Delta\searrow0$ での振る舞いを議論する．
---

{{< include ../../../assets/_preamble.qmd >}}

リサンプリングと粒子フィルターは $(\Om,\F,\P)$ 上に定義されているとし，この確率測度 $\P$ に関する期待値を $\E$ で表す．

一方で，観測対象は $(\Om',\F',\P')$ 上の過程 $z:\R_+\times\Om'\to\R^d$ とする．

２つの分布の間の関係を導く．

## リサンプリング

### 形式化

積空間 $[N]^{[N]}$ を **附番の空間** といい，元を $a\in[N]^{[N]}$ で表す．

積空間 $\R_+^N\setminus\{0\}^N$ を **荷重の空間** といい，元を $w\in\R_+^N\setminus\{0\}^N$ で表す．簡単のため，以降は $\R_+^N$ とも表してしまう．ノルム
$$
\norm{w}_1:=\sum_{i=1}^Nw_i
$$
を考える．

::: {.callout-tip icon="false" title="定義（リサンプリング）"}

1. 粒子数 $N$ に関する **リサンプリング法** $r$ とは，**荷重の空間 $\R_+^N$ から附番の空間 $[N]^{[N]}$ への確率核** をいう．すなわち，荷重に応じて，附番の空間上の確率分布を対応させる関数
$$
r:\R_+^N\to\cP([N]^{[N]})
$$
をいう．

2. リサンプリング法 $r$ が **不偏** であるとは，任意の番号 $j\in[N]$ に対して，その番号を得る粒子数の期待値が，荷重の通りになることをいう：$A\sim r(w)$ ならば，
$$
\begin{align*}
    \E[\#A^{-1}(j)]&=\E\Square{\sum_{i=1}^N1_{\Brace{A(i)=j}}}\\
    &=N\frac{w_j}{\norm{w}_1}\quad(j\in[N]).
\end{align*}
$$

:::

::: {.callout-caution icon="false" collapse="true" title="定義に関する議論"}
定義は [@Chopin+2022 p.3199] を参考にした．リサンプリング法の定義は，確率核 $r$ の終域をどうするかで議論があると思う．初めは $r:\R_+^N\to\cP([N])$ と定めたくなる．しかしこれでは **$N$ 回の非独立的なサンプリング** を表現できない．$r(w^{1:N})^{\otimes N}$ とするわけには行かないし，ベクトル $N\cdot r(w^{1:N})^\top$ が個数の分布になるようにサンプリングせよ，ということだったら確率核になっていない．結局確率核は $r:\R_+^N\to\cP([N]^{[N]})$ と取るしかない．すると，不偏性の表現が難しくなる．
:::

::: {.callout-caution icon="false" collapse="true" title="PAC-Bayes × リサンプリング？"}
問題構成がすごく PAC-Bayes っぽい．というより，Gibbs classifier っぽい．
:::

::: {.callout-caution icon="false" collapse="true" title="空間 $\mathcal{P}([N]^{[N]})$ と $\mathcal{M}^1([N]^{[N]})$"}

離散空間上の測度 $\mu\in\cM^1([N]^{[N]})$ は，その一点集合上での値
$$
f_\mu(a):=\mu(\{a\})
$$
で一意に定まるため，$\cM^1([N]^{[N]})$ は $\Map([N]^{[N]},\R_+)$ と，$\cP([N]^{[N]})$ は $[N]^{[N]}$ 上の確率質量関数全体の集合と同一視できる．

さらに，**関数空間 $\Map([N]^{[N]},\R_+)$ に各点収束の位相を入れたものと，弱位相を備えた $\cM^1([N]^{[N]})$ とは同相である**．

これを，$[N]^{[N]}$ に限らず，任意の可算な離散空間 $S$ において示す．すると $S$ 上では，弱収束は全変動収束に等しい．^[[@Dudley2002 p.389] 演習11.1.2．]

一般に [@Scheffe1947] の定理より，密度が各点収束するならば，分布は全変動収束，特に弱収束する．逆に，$S$ 上の分布が収束するとき，任意の一点集合 $\{x\}\subset S$ は開かつ閉であるから境界は空集合であり，[@Alexandroff1940] の特徴付けから，密度（というより確率質量関数）も収束する．

よって，$\cM^1([N]^{[N]})$ 上の弱収束と，$\Map([N]^{[N]},\R_+)$ 上の各点収束とは同値．いずれも第２可算だから，点列の収束が等しいことは位相も等しいことを含意する．
:::

以降，$\cM^1([N]^{[N]})$ は全変動ノルムが備わったノルム空間と見る．これは，写像の空間 $\Map([N]^{[N]},\R_+)$ に各点収束の位相が備わった空間と同一視できる．

### 荷重が一様になる極限でも安定なリサンプリング法

#### モチベーション

リサンプリング法 $r:\R_+^N\to\cP([N]^{[N]})$ に対して，荷重が一様に近づく（＝殆どリサンプリングをしなくなっていく）極限における性質を，連続関数
$$
\begin{align*}
    e:\R_+^N\times(0,1)&\to \R_+^N\\
(v,\Delta)\quad&\mapsto e^{-\Delta v}:=(e^{-\Delta v^1},\cdots,e^{-\Delta v^N})
\end{align*}
$$
を通じて調べる：
$$
\wt{r}(v,\Delta):=r\circ e(v,\Delta)=r(e^{-\Delta v}).
$$

$v\in\R_+^N$ が大雑把に方向を意味し，$\Delta>0$ が $0$ に近づくほど荷重が一様に近づくようなつまみの役割を果たす．

$\Delta$ をタイムステップとも考えると，粒子フィルターに $\Delta\searrow0$ の極限が存在するためには，リサンプリング回数が爆発しないために，
$$
\wt{r}(v,\Delta)(a)=O(\Delta)\quad(v\in\R_+^N,a\ne\id_{[N]})
$$ {#eq-1}
が成り立つ必要がある．

#### リサンプリング安定性の定式化

条件 ([-@eq-1]) が成り立つことは，
$$
\iota(v,\Delta):=\frac{r(e^{-\Delta v})}{\Delta}\quad\in\cM^1([N]^{[N]}).
$$
により定まる関数
$$
\iota:\R_+^N\times(0,1)\to\cM^1([N]^{[N]})
$$
が，任意の $a\in[N]^{[N]}\setminus\{\id_{[N]}\}$ に関して $\Delta\searrow0$ に関する極限 $\lim_{\Delta\searrow0}\iota(v,\Delta)$ を持つことに同値．

ここで，このリサンプリング強度関数
$$
\iota:\R^N_+\times(0,1)\to\cM^1([N]^{[N]})
$$
は連続になるとする．これはリサンプリング法 $r:\R_+^N\to\cP([N]^{[N]})$ が連続ならば成り立つ．
^[$\cP([N]^{[N]})$ 上の弱位相は，質量関数の各点収束に同値．よって，任意の附番 $a\in[N]^{[N]}$ に対して，$r(e^{-\Delta w})(a)\in[0,1]$ が連続であることに同値．つまり，$a\in[N]^{[N]}$ の通りにリサンプリングされる確率が，荷重 $w\in\R_+^N$ の変化に対して連続的に変化することを要請している．]

すると結局，条件 ([-@eq-1]) は，$\iota$ が連続な延長
$$
\ov{\iota}:\R_+^N\times[0,1)\to\cM^1([N]^{[N]}\setminus\{\id_{[N]}\})
$$
を持てば十分．^[ただしもちろん，$r$ が連続，または $\iota$ が連続であるという仮定の下で．]

これは $r$ が連続であることに加えて，上の収束が $v\in\R_+^N$ 上一様に成り立つならば，成り立つ．

$\ov{\iota}(v):=\ov{\iota}(v,0)$ は **極限リサンプリング強度** であり，総和を取ったもの
$$
\begin{align*}
    \ov{\iota}^*(w)&:=(\ov{\iota}(w,0)|1)\\
    &=\sum_{a\in[N]^{[N]}\setminus\{\id_{[N]}\}}\ov{\iota}(w,0)(a)\quad\in\R_+
\end{align*}
$$
は **全リサンプリング率** と呼べる．^[ただし，$(\ov{\iota}(w,0)|1)$ の $1$ は $[N]^{[N]}\setminus\{\id_{[N]}\}$ 上の定値関数とした．]

::: {.callout-tip icon="false"}
## 補題（ここまでの議論のまとめ）

1. リサンプリング法 $r:\R_+^N\to\cP([N]^{[N]})$ が連続で，
2. $[N]^{[N]}\setminus\{\id_{[N]}\}$ 上の関数の空間 $\cM^1([N]^{[N]}\setminus\{\id_{[N]}\})$ での収束
$$
\ov{\iota}(v)=\lim_{\Delta\searrow0}\frac{r(e^{-\Delta v})}{\Delta}
$$
は $v\in\R^N_+$ 上一様に成り立つ

とする．このとき，極限リサンプリング強度
$$
\ov{\iota}:\R_+^N\to\cM^1([N]^{[N]}\setminus\{\id_{[N]}\})
$$
は $\cM^1([N]^{[N]}\setminus\{\id_{[N]}\})$ の弱位相について連続である．
:::

::: {.callout-caution collapse="true" title="積空間上の連続関数の連続延長" icon="false"}

$$
f(x,y):=x^{\frac{1}{y}}
$$
によって $f:(0,1]\times(0,1)\to[0,1]$ を定める．任意の $x\in(0,1]$ について，極限
$$
\lim_{y\searrow0}x^{\frac{1}{y}}=\begin{cases}
0&x<1,\\
1&x=1.
\end{cases}
$$
は存在するが，延長
$$
\ov{f}:(0,1]\times[0,1]\to[0,1]
$$
は連続ではない．$\ov{f}(x,0)=\delta_1(x)$ である．

しかし，距離空間 $X,Y$ に対して，$f:X\times Y\to\R$ が，境界点 $\ov{y}\in\partial Y$ に対して，$f(x,y)\to f(x,\ov{y})$ が $x\in X$ に関して一様に成り立つならば，$f:X\times\ov{Y}\to\R$ は連続になる．

一様収束するとは，任意の $\ep>0$ に対して，ある $\delta>0$ が存在して，
$$
\abs{y-\ov{y}}<\delta\Rightarrow\norm{f(-,y)-f(-,\ov{y})}_\infty<\ep
$$
が成り立つことをいう．このとき，$f(-,\ov{y}):X\to\R$ は連続になる．^[[@杉浦光夫1980 p.305] 定理13.3 など．]

すると，$f:X\times\ov{Y}\to\R$ も連続であることが示せる．任意の収束点列 $\{(x_n,y_n)\}\subset X\times Y$ を取る．収束先が $(x,\ov{y})\in X\times\partial Y$ の形である場合について，$f(x_n,y_n)\to f(x,\ov{y})$ が成り立つことを示せばよい．

実際このとき，ある $N\in\N$ が存在して，任意の $n\ge N$ について
$$
\norm{f(-,y_n)-f(-,\ov{y})}_\infty<\frac{\ep}{2}
$$
かつ
$$
\abs{f(x_n,\ov{y})-f(x,\ov{y})}<\frac{\ep}{2}
$$
であるから，
$$
\begin{align*}
    &\abs{f(x_n,y_n)-f(x,\ov{y})}\\
    \le&\abs{f(x_n,y_n)-f(x_n,\ov{y})}+\abs{f(x_n,\ov{y})-f(x,\ov{y})}\\
    <&\frac{\ep}{2}+\frac{\ep}{2}=\ep.
\end{align*}
$$

:::

## 粒子フィルターの構成

::: {.callout-tip icon="false"}
## 目標となる Feynman-Kac 測度

$\R^d$ 上の伊藤拡散 $\{z_t\}\subset\L(\Om';\R^d)$ は，
$$
b_i,\sigma_{ij}\in\Lip_b(\R^d)\quad(i,j\in[d])
$$
が定める確率微分方程式
$$
z_t=b(z_t)dt+\sigma(z_t)dB_t
$$
で定まるものとする．

これを参照過程とし，ポテンシャル $V\in C_b(\R^d)_+$ が定める Feynman-Kac 測度を $\Pi\in C_c(D_{\R^d}(\R_+))^*$ と表す：
$$
\Pi(f):=\frac{1}{\cZ}\E\Square{f(z_{[0,\tau]})\exp\paren{-\int^\tau_0V(z_u)\,du}}
$$
$$
\cZ:=\E\Square{\exp\paren{-\int^\tau_0V(z_u)\,du}},\qquad f\in C_c(D_{\R^d}(\R_+);\R^d).
$$
:::

この $D_{\R^d}(\R_+)$ 上の Feynman-Kac 測度を，離散時間粒子フィルターがどこまで近似できるかを考える．

::: {.callout-tip icon="false"}
## 粒子フィルターの構成

粒子フィルター $\{X^\Delta_k\}\subset\L(\Om;M_{Nd}(\R))$ は最も自然に構成する．

粒子数 $N$ のリサンプリング法 $r$ に関して，サンプリング間隔を $\Delta>0$ として，
$$
\begin{align*}
    (X^\Delta_k)^i&:=(X_{k-1}^\Delta)^{A_k(i)}+\Delta\cdot b\paren{(X_{k-1}^\Delta)^{A_k(i)}}\\
    &\qquad+\sigma\paren{(X_{k-1}^\Delta)^{A_k(i)}}(B_{k\Delta}^i-B_{(k-1)\Delta}^i)\\
    &\qquad\qquad(i\in[N],k\in\N)\\
    A_k&\iidsim r(e^{-\Delta V(X^\Delta_k)})
\end{align*}
$$
と再帰的に定める．

これを $D_{\R^d}(\R_+)$-過程と見たものを
$$
Z_t^\Delta:=X_{\Floor{\frac{t}{\Delta}}}^\Delta
$$
と表す．フィルトレーション $\F_t$ は $(B_s)_{s\in[0,t]}$ と $\paren{A_{\Floor{\frac{s}{\Delta}}}}_{s\in[0,t]}$ とが生成するものの，完備右連続化とする．

:::

1. 任意の単調減少列 $\{\Delta_n\}\subset\R^+$ に対して，粒子フィルターの列
$$
\{X^{\Delta_n}\}\subset\L(\Om;D_{M_{Nd}(\R)}(\R_+))
$$
は一様に緊密である．

::: {.callout-tip icon="false"}
## 定理

Feynman-Kac 測度を定める参照過程 $\{z_t\}$ とポテンシャル $V:\R^d\to\R_+$ について，次を仮定する：

1. 
$$
b_i,\sigma_{ij}\in\Lip_b(\R^d)\quad(i,j\in[d])
$$
2. 
$$
\inf_{x\in\R^d}\inf_{\substack{\theta\in\R^d\\\norm{\theta}_2=1}}\norm{\sigma(x)\theta}_2>0
$$
3. $$V\in C_b(\R^d)_+$$

リサンプリング法 $r$ について，極限リサンプリング測度
$$
\ov{\iota}:\R_+^{N}\to\cM^1([N]^{[N]}\setminus\{\id_{[N]}\})
$$
が存在し，連続であるとする．^[その結果，任意の $a\in[N]^{[N]}\setminus\{\id_{[N]}\}$ に関して，$\R^{dN}\ni x\mapsto\ov{\iota}(V(x^1,\cdots,x^N))(a)$ が有界連続になる．]

このとき，これが定める粒子フィルター $\{X_k^\Delta\}_{k=0}^\infty$ の càdlàg 延長 $\{Z_t^\Delta\}_{t\in\R_+}$ は，任意の単調減少列 $\{\Delta_n\}\subset\R^+$ に対して，次を満たす：

1. ある Lévy 過程 $\{Z_t\}$ に分布収束する：
$$
(Z_t^{\Delta_n})\dto(Z_t).
$$
2. 分布収束極限の生成作用素 $\L$ は，伊藤拡散 $\{z_t\}$ の生成作用素
$$
\begin{align*}
    Lf(x)&=\frac{1}{2}\sum_{i,j=1}^d(\sigma\sigma^\top)_{ij}(x)\pp{^2f}{x_i\partial x_j}(x)\\
    &\qquad+\sum_{i=1}^db_i(x)\pp{f}{x_i}(x)\\
    &\qquad\qquad(f\in C_c^2(\R^d),x\in\R^d)
\end{align*}
$$
を用いて，
$$
\begin{align*}
    \L f(x)&:=\sum_{n=1}^N\sum_{i=1}^db_i(x^n)\pp{f}{x^n_i}(x)\\
    &\qquad+\sum_{n=1}^N\frac{1}{2}\sum_{i,j=1}^d(\sigma\sigma^\top)_{ij}(x^n)\pp{^2f}{x^n_i\partial x^n_j}(x)\\
    &\qquad+\sum_{a\ne1:N}\ov{\iota}(V(x),a)\Paren{f(x^{a(1:N)})-f(x^{1:N})}\\
    &\qquad\qquad(f\in C_c^2(\R^{dN}),x\in\R^{dN},x^n\in\R^d)
\end{align*}
$$
と表せる．
3. $\cV\in C_b(\R_+\times\R^{dN})_+$ を有界連続なポテンシャルとすると，任意の $f\in C_b(\R^{dN})$ について，
$$
\begin{align*}
    \lim_{n\to\infty}&\E\Square{f(X^{\Delta_n}_{\floor{\tau/\Delta_n}})\exp\paren{-\sum_{k=0}^{\floor{\tau/\Delta_n}-1}\Delta_n\cV(k\Delta_n,X^{\Delta_n}_k)}}\\
    =&\E\Square{f(Z_\tau)\exp\paren{-\int^\tau_0\cV(u,Z_u)\,du}}.
\end{align*}
$$

:::