---
title: "粒子法の概観"
subtitle: "分子動力学法から SMC サンプラーまで"
author: "司馬 博文"
date: 4/7/2024
categories: [Particles, Survey]
bibliography: 
    - ../../../assets/mathematics.bib
    - ../../../assets/bib.bib
    - ../../../assets/bib1.bib
csl: ../../../assets/apalike.csl
abstract-title: 概要
abstract: |
    粒子法とは空間や分布を多数の粒子の集合として離散化して表現・計算する技術の総称である．シミュレーションからデータ同化まで幅広い応用を持つ．この記事ではこれらの技術を「粒子」という軸でひとつの記事にまとめることを試みる．
listing: 
    -   id: lst-listing
        type: grid
        sort: false
        contents:
            - "../../2023/Surveys/ParticleFilter.qmd"
            - "../../Surveys/SMCSamplers.qmd"
            - "../../2023/Particles/ParticleFilter.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
---

## シミュレーションのための粒子法

### はじめに

多くの物質は元々離散的であり，その最小単位は原子や分子である．

これをコンピュータ内に粒子として表現し，その現実世界での動きを模倣することを目指すシミュレーション法は [分子動力学法](https://ja.wikipedia.org/wiki/分子動力学法) (MD: molecular dynamics) と呼ばれる．

アイデアは大変シンプルである．

::: {.callout-caution title="原子論についての Feynman の名言" collapse="true" icon="false"}

Feynman の講義録（のちに教科書になる）では，最も重要な科学知識の一つとして原子論を挙げている：

> If, in some cataclysm, all of scientific knowledge were to be destroyed, and only one sentence passed on to the next generations of creatures, what statement would contain the most information in the fewest words? I believe it is the _atomic hypothesis_ (or the atomic fact, or whatever you wish to call it) that _all things are made of atoms—little particles that move around in perpetual motion, attracting each other when they are a little distance apart, but repelling upon being squeezed into one another_. In that one sentence, you will see, there is an enormous amount of information about the world, if just a little imagination and thinking are applied. [@Fenyman+1963]

:::

### 分子動力学法

[分子動力学法](https://ja.wikipedia.org/wiki/分子動力学法) の文脈で **粒子法** (particle methods) と言ったとき，

* 古典的な質点には Newton 力学
* 剛体で体積を持つ場合は Euler 方程式
* 内部構造を持つ場合は Langrange 方程式
* さらに一般の場合は Hamilton 方程式

に基づいて粒子の動きをシミュレーションすることを指す．

### モンテカルロ法

分子動力学法は Monte Carlo 法と組み合わせて使われることが多い．

粒子の動きを上述の方程式に基づいて提案し，離散化誤差を Metropolis 法によって補正することで，系の物理量の分布を求めたり，平均値を求めたりする [@Rapaport2004 p.4], [@Griebel+2007 p.17]．

そもそも MCMC の手法 [@Metropolis+1953] 自体も，Schrödinger 方程式に基づいた基底状態のシミュレーションを実行するために生まれたものである．

これが強力なのである．極めて強力であるが故に，計算科学の分野ではすでに，そして将来的には確実に，シミュレーションと数値実験が，実際の実験と似たような重要な役割を科学において担うことになると見られている．

### 推論のための粒子法との関係

この意味での粒子法と，統計学において粒子法と言った場合に想像されるであろう SMC や IPM (interacting particle methods) とは **実は数理的には同一物である** ことを見たい．

一言で言えば，一般に粒子法はポテンシャル（ハミルトニアン）に従って粒子を伝播する方法であり，粒子フィルターは特にこれが Feynman-Kac 測度で与えられる場合に用いられる粒子法である．

## 推論のための粒子法

### ベイズ逆問題

シミュレーションができるようになったならば，これを実際の実験データや観測データと付き合わせて比較したいということになる．

このようにデータに基づいてシミュレーションを校正する作業は **逆問題** (inverse problem) と呼ばれ，旧来は統計的推論との関係は希薄であった．

::: {.callout-tip appearance="simple" icon="false" title="逆問題の例"}

* [逆散乱問題](https://ja.wikipedia.org/wiki/逆散乱)：[反響定位](https://ja.wikipedia.org/wiki/反響定位) (echolocation) やソナー，[地震探索](https://en.wikipedia.org/wiki/Reflection_seismology) (seismic exploration)
* [断層映像法](https://ja.wikipedia.org/wiki/トモグラフィー) (tomography)：[海洋音響トモグラフィー](https://ja.wikipedia.org/wiki/海洋音響トモグラフィー) や [地震波トモグラフィー](https://ja.wikipedia.org/wiki/%E5%9C%B0%E9%9C%87%E6%B3%A2%E3%83%88%E3%83%A2%E3%82%B0%E3%83%A9%E3%83%95%E3%82%A3%E3%83%BC) など．
* [医用画像](https://ja.wikipedia.org/wiki/医用画像) (medical imaging)：X線撮影，CT, MRI など．
* [非破壊検査](https://ja.wikipedia.org/wiki/非破壊検査) (NDT: Non-Destructive Testing)：[超音波探傷試験](https://ja.wikipedia.org/wiki/超音波探傷試験) (UT: Ultrasonic Testing / SAT: Scanning Acoustic Tomography)
* 認知科学：脳波 (EEG: Electroencephalogram)，脳磁図 (MEG: Magnetoencephalography) など．^[「MRI や PET では脳内における血流量や糖代謝等の空間分布が mm オーダーの分解能で直接に計測できるのに対し、EEG や MEG では頭表面上で計測される電位分布や磁場分布から脳内の起電力分布を推定するという問題、いわゆる脳電位逆問題や脳磁場逆問題を解決しなければならない。」[@岡本-本間2002]．fMRI や陽電子断層撮像法 (PET: Positron Emission Tomography) [@Ter-Pogossian1975] は深いところまで見れるが時間分解能が低いという欠点もある．]

:::

::: {.callout-important title="逆問題の形式的な定義" collapse="true" icon="false"}

逆問題は広く Banach 関数上の作用素 $F:X\osup U\to Y$ の零点を求める問題として定式化される [定義1.2.1 @Nakamura-Potthast2015 p.1-15]．

大きく分類すると，源泉問題 (source problem) と散乱問題 (scattering problem)，力学系逆問題 (dynamical systems inversion)，スペクトル逆問題 (spectral inverse problem) との４つに分けられる．

場の復元と形状の復元は散乱問題の特別な場合とみれる．スペクトル逆問題は [@Kac1966] で有名である．

データ同化問題は力学系逆問題を逐次的に解く方法と位置付けられる [@Nakamura-Potthast2015 p.1-20]．

:::

しかし「系に対する，方程式などの形で与えられる事前知識をもとに，データから実際の構造に対する知識をアップデートしていく」という営みはまさにベイズ推論の一種である．

特にベイズによる取り扱いが統一的な数学的基礎を与えることに加え，従来からの無定義用語であった well-posedness に数学的に厳密な定義を与えることができることから，近年 **ベイズ逆問題** (Bayesian inverse problem) と呼ばれる分野が進展を見せている [@Stuart2010]．

さらに従来の逆問題のためのアルゴリズムは統計学における対応物を持つことが多い．例えば Tikhonov 正則化と呼ばれる手続きは Ridge 回帰 [@Hoerl-Kennard1970] に他ならない．データ同化においては変分推論が先駆けて古くから使われている [@佐々木1958]．

ベイズの取り扱いはこのようなアルゴリズムの開発に対しても統一的な基盤を与える上に，アルゴリズムの最適性の議論も可能になる [@Nickl2017]．

### データ同化

極めて現代的な逆問題の発展形が **データ同化** (data assimilation) または **動的逆問題** (dynamic inverse problem) である．^[データ同化に対するレトロニムとして，逆問題を **古典的逆問題** (classical inverse problem) と呼ぶこともある [@Nakamura-Potthast2015 p.1-5]．]

データ同化は地球科学，特に気象予測の分野で芽生えた考え方である．気象予測では大規模なシミュレーションが欠かせないが，同時に正確な予測のためには初期値の正確さが重要である．

しかし系が巨大すぎるあまり，観測データから得られる情報は極めて限定的であり，むしろ初期値を正確に知るためにもシミュレーションや構造的な知識が必要である．

このように順問題と逆問題とを逐次的に考えることがデータ同化の特徴である．もしかしたら data-simulation assimilation と呼ぶべきかもしれない．

現在データ同化は測定値とシミュレーションを同化させて精度の良い予測を行う営為全般に応用が進んでいる [@Nakamura-Potthast2015]．

### 粒子フィルターの位置付け

従来から粒子法が用いられていたが，粒子フィルターは今後の大規模データ世界におけるデータ同化の主力技術と目されている [@vanLeeuwen+2019]．

## 関連記事 {.unlisted .unnumbered}

::: {#lst-listing}
:::