---
title: "A Recent Development of Particle Methods"
subtitle: "Inquiry towards a Continuous Time Limit and Scalability"
author: "Hirofumi Shiba"
date: 2/25/2024
date-modified: 2/26/2024
categories: [Particles, Computation]
toc: true
number-sections: true
code-block-bg: true
code-block-border-left: "#5AB5BA"
code-overflow: wrap
code-fold: true
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
crossref:
    sec-prefix: 節
    eq-prefix: 式
    def-prefix: 定義
    def-title: 定義
    thm-prefix: 定理
    thm-title: 定理
    fig-prefix: 図
    fig-title: 図
abstract-title: Abstract
abstract: aa
---

{{< include ../../../_preamble.qmd >}}

This is a detailed version of the poster presented at [MLSS2024](../../../static/Sessions.qmd#sec-MLSS2024), S3-41, March 8 (Fri) 18:00-19:30.

Japanese version is available [here](PFja.qmd).

## What Is a Particle Filter?

_Particle filters_, also known as _Sequential Monte Carlo_ methods (SMCs), were invented in [@Kitagawa1993] and [@Gordon+1993] independently as an simulation-based algorithm which performs filtering in non-Gaussian and non-linear state space models, overcoming the weeknesses of then-standard Kalman-based filtering methods.

In particle-based approaches, a filtering distribution is approximated by a cloud of weighted samples, hence giving rise to the term 'particle methods'. The samples are propagated to approximate the next distribution, leading to efficient sequential estimation in dynamic settings.

## Resampling: The Key to Effective Particle Filtering

The _resampling step_ is the key difference from sequential importance sampling methods. Particle filters incorporate a resampling step to occasionally reset the weights of the samples, while maintaining the overall distribution they represent, in order to prevent the effective number of particles participating in the estimation from becoming too small--a situation also called _weight degeneracy_.

## Expanding Applications of Particle Filters

Recent developments have highlithgted the capability of particle filters as general-purpose samplers, extending their applicability beyond the traditional realm of temporal graphical models to a broader range of statistical inference problems. This versatility has earned them the alternative name 'SMC', a term reminiscent of 'MCMC'. This poster trys to be another contribution in this direction.

## A Generi Particle Filter: An Algorithmic Description

