---
title: "粒子フィルターの連続モデルへの適用"
author: "司馬 博文"
date: 1/24/2024
categories: [Particles, Computation]
toc: true
number-sections: true
code-block-bg: true
code-block-border-left: "#5AB5BA"
code-overflow: wrap
code-fold: true
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
crossref:
    sec-prefix: 節
    eq-prefix: 式
    def-prefix: 定義
    def-title: 定義
    thm-prefix: 定理
    thm-title: 定理
    fig-prefix: 図
    fig-title: 図
abstract-title: 概要
abstract: 粒子フィルターを，拡散過程に対して適用することを考える．
---

{{< include ../../../_preamble.qmd >}}

## 導入：粒子フィルターとは何か？

粒子フィルターとは，逐次モンテカルロ法とも呼ばれ，あらゆる状態空間モデル（非線型・非Gaussでも！）に適用可能なサンプリングベースの非線型フィルタリングアルゴリズムとして提案された [@Gordon+1993], [@Kitagawa1993]．Kalman フィルターベースの手法の難点を克服したのである．

フィルタリング分布を，粒子と呼ばれる有限個の重み付けられたサンプルで近似し，そのサンプルを更新していくことで，逐次的にフィルタリング分布を近似する手法であるため，粒子フィルターと呼ばれる．

## リサンプリング：粒子フィルターの最重要メカニズム

逐次重点サンプリングとの違いは，表現する分布は変えずに，定期的に荷重を一様に均す **リサンプリング** という機構を導入しているために，荷重の縮退と呼ばれる，時間経過と共に有効サンプル数が極めて小さくなってしまう問題を回避している点にある．

粒子フィルターの妙は，そのサンプリング段階にあると言える．

## 粒子フィルターの適用範囲の拡大

しかし，粒子フィルターは時系列構造を持ったグラフィカルモデルに限った推論アルゴリズムではなく，**極めて汎用的な手法** であることがわかってきた．だから「逐次モンテカルロ法」という，「マルコフ連鎖モンテカルロ法」を連想させる名前も付いているのである．

複雑な目標分布 $\pi$ からサンプリングすることは，機械学習において重要な問題の一つであるが，テンパリングの発想で，これを近似する列
$$
\pi_1,\pi_2,\cdots,\pi_n=\pi
$$
を構成し，これを逐次的に近似する粒子フィルターを構成することで，多峰性にも強いサンプリング手法として使うこともでき，これを SMC Sampler と呼ぶ [@DelMoral+2006]．

この粒子フィルターの逐次的な構造と，テンパリングを組み合わせる手法は，多くの設定で MCMC よりも安定性のある推論手法を提供する．

本稿も粒子フィルターの適用先を拡張する試みの一つであり，粒子フィルターを拡散過程に対して適用した場合の，リサンプリング効率と収束性について考察したものである．

## 粒子フィルターの数理的描写

## 粒子フィルターのアルゴリズム的描写

## 粒子フィルターの拡散過程への適用

