---
title: "条件付き正規分布からのシミュレーション法"
author: "Hirofumi Shiba"
date: "11/17/2023"
categories: [Math Notes]
toc: true
number-sections: false
website:
    twitter-card: true
bibliography: bib.bib
csl: apa.csl
---

文献 [@Doucet2010-ConditionalGaussianSimulation] の主張に証明を与える．

{{< include preamble.qmd >}}

```{=html}
<a class="embedly-card" href="https://www.cs.ubc.ca/~arnaud/doucet_simulationconditionalgaussian.pdf">Card</a><script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
```

::: {.callout-tip title="命題：正規確率変数同士の条件付き分布"}
$$Z=(X,Y)\sim\rN_n(m,\Sigma)\qquad m=\vctr{m_x}{m_y},\qquad\Sigma=\mtrx{\Sigma_{xx}}{\Sigma_{xy}}{\Sigma_{xy}^\top}{\Sigma_{yy}}$$
で，共分散行列は正則 $\Sigma\in\GL_n(\R)$ とする．このとき，
$$X|Y=y\sim\rN_{n_x}(m_{x|y},\Sigma_{x|y}),\qquad m_{x|y}=m_x+\Sigma_{xy}\Sigma_{yy}^{-1}(y-m_y),\qquad\Sigma_{x|y}=\Sigma_{xx}-\Sigma_{xy}\Sigma_{yy}^{-1}\Sigma_{xy}^\top.$$
:::

::: {.callout-note icon=false}

## 証明
$Z$の密度
$$\frac{1}{(2\pi)^{n/2}(\det\Sigma)^{1/2}}\exp\paren{-\frac{1}{2}(z-m)^\top\Sigma^{-1}(z-m)}$$
を，$Y$ の密度との積で表した際，残った因子が $X|Y$ の密度となる． $\exp$ の中身に注目する．Schur補行列を $S:=\Sigma_{xx}-\Sigma_{xy}\Sigma_{yy}^{-1}\Sigma_{xy}^\top$ とすると，
$$\Sigma^{-1}=\mtrx{S^{-1}}{-S^{-1}T}{-T^\top S^{-1}}{\Sigma_{yy}^{-1}+T^\top S^{-1}T},\qquad T:=\Sigma_{xy}\Sigma_{yy}^{-1}$$
であるから， $\eta:=T(y-m_y)=\Sigma_{xx}\Sigma_{yy}^{-1}(y-m_y)$ とおくと，
\begin{align*}
    (z-m)^\top\Sigma^{-1}(z-m)&=(x-m_x)^\top S^{-1}(x-m_x)-(y-m_y)^\top T^\top S^{-1}(x-m_x)-(x-m_x)^\top S^{-1}T(y-m_y)\\
    &\qquad\qquad+(y-m_y)^\top T^\top S^{-1}T(y-m_y) +(y-m_y)^\top\Sigma_{yy}^{-1}(y-m_y)\\
    &=\Paren{(x-m_x)^\top-\eta^\top}S^{-1}(x-m_x)-\Paren{(x-m_x)^\top+\eta^\top}S^{-1}\eta+(y-m_y)^\top\Sigma_{yy}^{-1}(y-m_y)\\
    &=\Paren{(x-m_x)^\top-\eta^\top}S^{-1}\Paren{(x-m_x)-\eta}+(y-m_y)^\top\Sigma_{yy}^{-1}(y-m_y).
\end{align*}
以上より，平均は $m_{x|y}=m_x+\eta$ で，共分散行列は $\Sigma_{x|y}=S$ ．
:::

::: {.callout-tip title="条件付き分布からのシミュレーション"}
条件付き確率変数 $X|Y$ のシミュレーションは，条件付き共分散行列 $\Sigma_{x|y}$ のCholesky分解 $\Sigma_{x|y}=\sqrt{\Sigma_{x|y}}\paren{\sqrt{\Sigma_{x|y}}}^\top$ を用いて，
$$\ov{X}=m_{x|y}+\sqrt{\Sigma_{x|y}}U,\qquad U\sim\rN_{n_x}(0,I_{n_x})$$
によって行うのも直接的だが， $n_x$ の次元が大きすぎる場合，Cholesky分解の計算がネックとなる．そのような場合は，
$$\ov{X}=X+\Sigma_{xy}\Sigma_{yy}^{-1}(y-Y),\qquad Z=\vctr{X}{Y}\sim\rN_n(m,\Sigma),$$
というアルゴリズムを用いることが出来る [@Hoffman-Ribak1991]．
:::

::: {.callout-note icon=false}

## 証明

$\ov{X}$ はGauss確率変数の線型変換だからやはりGaussである．よって，平均と分散が $X|Y$ に一致することを示せば良い．
次のように $\ov{X}$ を書き換えることが出来る：
\begin{align*}
    \ov{X}&=X+\Sigma_{xy}\Sigma_{yy}^{-1}(y-Y)=X+\Paren{m_x+\Sigma_{xy}\Sigma_{yy}^{-1}(y-m_y)}+\Paren{m_x+\Sigma_{xy}\Sigma_{yy}^{-1}(Y-m_y)}\\
    &=X+m_{x|y}-\E[X|Y]
\end{align*}
これより，$\E[\ov{X}|Y]=m_{x|y}$．よって，
$$\E[\ov{X}]=\E[\E[\ov{X}|Y]]=m_{x|y}.$$
続いて，
$$\Var[\ov{X}|Y]=\Var[X-\E[X|Y]|Y]=\E[(X-\E[X|Y])^2|Y]=\Var[X|Y]=\Sigma_{x|y}$$
より，全分散の公式から
$$\Var[\ov{X}]=\E[\Var[\ov{X}|Y]]+\underbrace{\Var[\E[\ov{X}|Y]]}_{=0}=\Sigma_{x|y}.$$

:::