---
title: "数学者のための統計力学１"
subtitle: Ising 模型
author: "司馬 博文"
date: 4/7/2024
categories: [Nature]
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
abstract-title: 概要
abstract: 数学者のために，統計力学の場面設定を数学的に理解することを試みる．統計力学の最も代表的なモデルである Ising 模型の数理も概観する．
---
---

{{< include ../../../_preamble.qmd >}}

普通数学者がやらないことであるが，古典粒子系を例にとって，統計力学における基本的な用語を確認する．

統計力学といえども場面設定は力学であり，その形式はハミルトン形式が利用される．

しかし，その運動方程式を解析的に分析するのではなく，相空間 $\Om$ 上の（有界）測度に注目して，確率統計学，果てには計算統計学を利用して展開していく．

ちょうど，統計学ではここのサンプル $\om\in\Om$ よりも全体的な振る舞い $P\in\cP(\Om)$ や統計量 $\Om\to\R$ の平均値や分散などの統計的な振る舞いに興味があるのと同じことである．

## 古典粒子系

### 多様体 $\Om_{\Lambda,N}$

有界集合 $\Lambda\subset\R^3$ に囚われた古典的な $N$ 粒子系を考えると，位置と速度によって各粒子は記述できるから，
$$
\Om_{\Lambda,N}:=(\Lambda\times\R^3)^N
$$
内の点によって系が記述できる．これを **相空間** (phase space) という．^[すなわち，$\Lambda$ 上の線型束である．]

### 関数 $H_{\Lambda,N}$

この上に **エネルギー** が定まるが，これは **ハミルトニアン** ともいう：^[$V$ は境界ポテンシャルといい，外場との相互作用がある場合に現れる．]
$$
H_{\Lambda,N}(Q,V)=\sum_{i=1}^N\frac{mv_i^2}{2}+\sum_{i<j\in[N]}U(q_i-q_j)+\sum_{i=1}^NV_b(q_i)
$$
$$
Q=(q_1,\cdots,q_N)\in\Lambda^{3N}
$$

多くの場合，ポテンシャル関数 $U$ はコンパクト台を持つ，すなわち，**相互作用半径** (radius of interaction) $R$ をもつとする：$\supp U\subset U_R(0)$．^[これは粒子間相互作用が short-range であると仮定しているためである．重力やクーロン力を考えている訳ではない．]

経験則的に，まずは Lennard-Jones ポテンシャル
$$
U(r)=\frac{A}{r^{12}}-\frac{B}{r^6}\quad A,B>0
$$
を用いてモデリングする場合が多い．

系の時間発展は変換の族 $\{S_t\}\subset\Aut(\Om_{\Lambda,N})$ （**動力学** dynamics という）によって記述され，
動力学は運動方程式から導出される．
$$
\dd{q_i}{t}=v_i
$$
$$
m\dd{v_i}{t}=-\sum_{i\ne j}\nabla U(q_j-q_i)-\nabla V_b(q_i)
$$

### 部分多様体 $\Om_{\Lambda,N,E}$ と小正準分布 {#sec-microcanonical}

この動力学 $\{S_t\}$ は体積とエネルギーを保存量にもつ．すなわち，各 $S_t$ は保測的で，等エネルギー集合
$$
\Om_{\Lambda,N,E}:=\Brace{(Q,\Lambda)\in\Om_{\Lambda,N}\mid H_{\Lambda,N}(Q,\Lambda)=E}
$$
を不変部分集合にもつ．

$\Om_{\Lambda,N,E}$ 上の測度
$$
\nu_{\Lambda,N,E}(B):=\lim_{\Delta E\to0}\frac{\ell(\Delta B)}{\Delta E}
$$
は $S_t$ によって保存される．これを **小正準分布** (microcanonical measures) または Gelfand-Leray measures という．

ただし，$\Delta B$ は $x\in B$ から始まった $\Om_{\Lambda,N,E}$ の法線（面）で，$\Om_{\Lambda,N,E+\Delta E}$ との交点で終わる線分の $x\in B$ に関する合併である．

他にも，等位集合が $S_t$ によって保存される関数 $I_i:\Om_{\Lambda,N}\to\R$ は存在し得て，その場合は全ての合併 $\Om_{\Lambda,N,E,I_1,\cdots,I_k}$ 上に小正準分布が遺伝する．

### エルゴード仮説

Boltzman のエルゴード仮説は，他の積分 $I_i$ が存在しない場合，$\Om_{\Lambda,N,E}$ 上の $S_t$-不変で $\nu_{\Lambda,N,E}$-絶対連続な測度は，$\nu_{\Lambda,N,E}$ の定数倍に限る，というものである．

これにより，特定の系が運動 $S_t$ によって平衡状態に至った際，相空間上を旅する際に特定の状態が現れる頻度分布は，必ず小正準分布に一致することが帰結される．

### configuration gas

もし粒子が全て動いていないならば，相空間は $\R^{3N}=:\Om_{\Lambda,N}^{\text{conf}}$ で良い．

これを **configuration gas** といい，古典粒子系の更なる理想化に当たる．

## 格子模型

一部は実際の物理系の良いモデルとなっているが，より複雑なモデルの統計物理学的性質の良い第一近似としても用いられる．

### 格子気体

configuration gas から更なるモデルの簡略化を考える．

粒子の位置は必ず格子点上にあるとすれば，配置空間はさらに $\Lambda\subset\bZ^3$ に対して
$$
\Om_{\Lambda,N}=\Brace{Q=(q_1,\cdots,q_N)\in\Lambda^N\mid q_i\ne q_j\;(i\ne j)}
$$
と簡略化される．

仮に外場もないとすると，ハミルトニアンは単にポテンシャルの和
$$
H(Q)=\sum_{i<j}U(q_i-q_j)
$$
となる．

### スピン系

有限集合 $\Lambda\subset\bZ^3$ が粒子で満ちているとすると，配置空間は縮退する．

その際のスピン系の相空間は，関数の集合
$$
\Om_\Lambda:=S^\Lambda
$$
になる．

$S=\partial U_1(0)\subset\R^3$ の場合を **平面回転子** (planar rotator) モデルという．$S=\{\pm1\}$ としても（Ising spin），^[[@西森秀稔2003 p.4]．情報統計力学では，スピンをビットやニューロンの状態に見立てる．] 物理系のモデルとして磁性体の第一近似として使える模型になる．

ハミルトニアンは，相互作用と外場の和として
$$
H_\Lambda(\sigma)=\sum_{x\ne y\in\Lambda}U(x-y)\sigma(x)\sigma(y)+h\sum_{x\in\Lambda}\sigma(x)
$$
と与えられる．

コンパクト台を持つ関数 $U$ が $U_1(0)\cap\bZ^3$ で消える場合を **Ising 模型** という．

## 参考文献 {.appendix}

[@Minlos2000], [@西森秀稔2003]