---
title: "数学者のための統計力学２"
subtitle: 小正準集団・正準集団・大正準集団
author: "司馬 博文"
date: 4/7/2024
categories: [Nature]
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
abstract-title: 概要
abstract: 数学者のために，統計力学の最も代表的なモデルである Ising 模型の数理を概観する．
---

{{< include ../../../_preamble.qmd >}}

系 $\Om_{\Lambda,N}$ の統計的な振る舞いを最もよく記述する確率分布 $P\in\cP(\Om_{\Lambda,N})$ を推定することを考える．

系が平衡状態にない場合は極めて困難な問題となるが，平衡状態の場合はいくつか候補が存在する．

仮に初期分布 $P_0\in\cP(\Om_{\Lambda,N})$ を持っていた場合，分布は $(S_t)_*P_0$ というように $\cP(\Om_{\Lambda,N})$ 上の力学系として発展していく．

従って，平衡分布は必ず $S_t$ の不動点，不変確率分布である必要があるが，これを満たす分布は複数存在し，これが小正準集団，正準集団，大正準集団である．

**確率的な系も $\cP(\Om_{\Lambda,N})$ 上で見れば決定論的な発展をするのが数理の妙である**．

これら３つの分布はどれもそれだけで完全なものではなく，熱力学極限において真に物理的に意味のある量になると理解する．

## 小正準分布

[小正準分布](StatisticalMechanics1.qmd#sec-microcanonical) を正規化したものも $S_t$ の不変確率分布である：
$$
P^{\text{microcanon}}_{\Lambda,N,E}(A):=\frac{\nu_{\Lambda,N,E}(A)}{\nu_{\Lambda,N,E}(\Om_{\Lambda,N,E})}
$$

改めて，$P^{\text{microcanon}}_{\Lambda,N,E}$ は $\Om_{\Lambda,N,E}$ 上にしか台を持たないことに注意．

加えて実は，**$P^{\text{microcanon}}_{\Lambda,N,E}$ は $\R^{6N}$ 上の Lebesgue 測度 $\ell_{6N}$ に関して絶対連続ではない**．

## Gibbs の正準分布

系のエネルギーを指定するのではなく，逆温度を指定することで，密度
$$
p^{\text{canon}}_{\Lambda,N,\beta}(Q,V)=\frac{1}{Z_{\Lambda,N,\beta}}e^{-\beta H_{\Lambda,N}(Q,V)}
$$
を持つ不変確率分布を得る．^[$S_t$ は体積を保存し Hamiltonian も保存するため，これは明らかに $S_t$ の不変確率分布である．] これを **正準分布** (canonical distribution) という．

$\beta>0$ を **逆温度**，$Z_{\Lambda,N,\beta}$ を **分配関数** (partition function / statistical sum) という．

古典気体の $H$ において位置に依存する項と速度に依存する項とが分かれているため，$P^{\text{canon}}_{\Lambda,N,\beta}$ において位置と速度は独立であり，速度 $v_1,\cdots,v_N$ も互いに独立でそれぞれは Gauss 分布に従う．これを [**Maxwell の法則**](https://ja.wikipedia.org/wiki/%E3%83%9E%E3%82%AF%E3%82%B9%E3%82%A6%E3%82%A7%E3%83%AB%E5%88%86%E5%B8%83) という．

また特に，Gibbs 測度の配置空間上での周辺分布は，configuration gas の Gibbs 測度に一致する．この意味で，古典気体の統計力学的性質は，configuration gas に帰着すると言える．

## ２つの関係と熱力学極限

$\Lambda_0\subset\Lambda$ を部分領域として，この領域に $s$ 個の粒子が存在する状態
$$
\Om_{\Lambda,N}^{\Lambda_0,s}:=\Brace{(Q,V)\in\Om_{V,N}\mid\abs{Q\cap\Lambda_0}=s}
$$
を考え，この部分領域への小正準分布 $P^{\text{microcanon}}_{\Lambda,N,E}$ の制限を考えると，ある極限に関して正準分布になる [@Minlos2000]．

すなわち，ある領域 $\Lambda_0$ に $s$ 個の粒子が存在する限り値が変わらないような量 $F:\Om_{\Lambda,N}\to\R$ は，小正準平均も正準平均も「ほとんど」変わらないことになる．この極限の正確な意味は
$$
\Lambda\nearrow\R^v,N\to\infty,\frac{N}{\abs{\Lambda}}\to\rho\in\R,\frac{E_i}{\abs{\Lambda_i}}\to e\in\R,
$$
というものであり，これを **熱力学極限** という（第 [-@sec-thermodynamic-limit] 節）．

## 大正準集団

大正準集団は，領域 $\Lambda\subset\R^3$ に粒子数 $N\in\N$ を定めずに存在する互いに区別できない粒子の系を考えることになる：
$$
\Om_\Lambda=C_\Lambda^{(0)}\cup C_\Lambda^{(1)}\cup\cdots\cup C_\lambda^{(N)}\cup\cdots
$$

この $\Om_\Lambda$ 上に，各 $C_\Lambda^{(N)}$ 上での Lebesgue 測度が誘導する測度 (Lebesgue-Poisson measure)
$$
\mu_\Lambda^{(N)}(A):=\frac{\ell_{3N}(A)}{N!}
$$
の貼り合わせとして定義される測度を正規化したものを $\mu$ とし，これを体積の代わりとする．

これを基底測度として密度
$$
p^{\text{grandcanon}}_{\Lambda,\beta,\mu}(c):=\frac{1}{\Xi(\Lambda,\beta,\mu)}e^{-\beta(H_\Lambda(c)+\mu N(c))}
$$
が定める分布を **大正準分布** という．

$\beta>0$ は逆温度であるが，$\mu\in\R$ は化学ポテンシャルである．

小正準集団が正準集団になる際に，エネルギー一定の制約は解放されて，代わりに新たなパラメータ $\beta>0$ を得た．ここからさらに粒子数一定の制約を解放し，代わりに新たなパラメータ $\mu\in\R$ を得たものが大正準集団である．この順に解析が容易になる．

大正準分布を粒子数一定の条件で条件付けて得る $C_\Lambda^{(N)}$ 上の分布は正準分布に一致する．

## 熱力学極限 {#sec-thermodynamic-limit}

$F_B:\Om_\Lambda\to\R$ が **局所変数** であるとは，
$$
F_B(c)=F_B(c\cap B)\quad(c\in\Om_\Lambda)
$$
を満たすことをいう．

熱力学極限
$$
\lim_{\Lambda\nearrow\R^3}\brac{F_B}_{\Lambda,\beta,\mu}=\brac{F_B}_{\infty,\beta,\mu}
$$
は，ある空間上のある積分と捉えられる．これを **極限 Gibbs 測度** (limit Gibbs distribution) という．

この極限 Gibbs 測度が複数存在したり，良い性質が失われたりする現象を **相転移** といい，その際の $(\beta,\mu)$ を特異点という．

熱力学では，系の変化が極めて緩慢であるために，一瞬一瞬において平衡状態が保たれているとみなせる物理的過程が扱われるため，大正準集団では $T=\beta^{-1},\mu$，正準集団では $T,\rho$，小正準集団では $\rho,e$ などのマクロ変量によって記述できる理論になっている．

そして熱力学極限において，これら３集団は等価であるから，これらはパラメータ変換の問題でしかなく，さらにこのパラメータ空間上に別の関数も導入される．特にエントロピー $s(e,\rho)$，Helmgolz の自由エネルギー $f(\beta,\rho)$，圧力 $p(\beta,\mu)$ などであり，これらは互いに Legendre 変換により関係し合っている．

これらの熱力学的関数も，特定の統計力学的な量の熱力学極限として理解できる．

$$
s(\rho,e)=\lim_{\substack{\Lambda\nearrow\bZ^v\\\frac{N}{\abs{\Lambda}}\to\rho\\\frac{E}{\Lambda}\to e}}\frac{\log Q^{\text{indistin}}(\Lambda,E,N)}{\abs{\Lambda}}
$$
$$
f(\beta,\rho)=-\frac{1}{\beta}\lim_{\substack{\Lambda\nearrow\bZ^3\\\frac{N}{\abs{\Lambda}}\to\rho}}\frac{\log Z^{\text{indistin}}(\Lambda,N,\beta)}{\abs{\Lambda}}
$$
$$
p(\beta,\mu)=\frac{1}{\beta}\lim_{N\nearrow\bZ^3}\frac{\log\Xi(\Lambda,\mu,\beta)}{\abs{\Lambda}}
$$

ただし，$Q^{\text{indistin}},Z^{\text{indistin}},\Xi$ はそれぞれ，（粒子が互いに区別がつかない場合の）小正準集団，正準集団，大正準集団の正規化定数とした．

## 参考文献 {.appendix}

[@Minlos2000], [@西森秀稔2003]