project:
  type: website
  output-dir: docs

website:
  title: "Ano2math5"
  image: anomaths.png
  favicon: profile.jpg
  site-url: https://github.com/162348
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/162348
format:
  html:
    theme: minty
    css: styles.css