project:
  type: website
  output-dir: docs

website:
  title: "Hirofumi Shiba"
  image: anomaths.png
  favicon: profile.jpg
  site-url: https://162348.github.io/docs/
  description: "A website by a Bayesian Computation Researcher"
  navbar:
    right:
      - text: "Blog"
        file: recent.qmd
      - text: "Sessions"
        file: ./static/Sessions.qmd
      - text: "日本語"
        file: ./static/Japanese.qmd
  open-graph: 
    description: A Blog by a Bayesian Computation Researcher
  twitter-card: true
  google-analytics: "G-36GX2G6GLL"
  comments:
    utterances:
      repo: quarto-dev/quarto-web

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    highlight-style: ayu
    code-block-bg: true
    code-block-border-left: "#7CC4AC"

execute:
  freeze: auto