project:
  type: website
  output-dir: docs

website:
  title: "Anomaths"
  image: anomaths.png
  site-url: https://github.com/162348
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/162348
  sidebar:
    search: true
  open-graph: true
  twitter-card:
    site: "@ano2math5"
format:
  html:
    theme: darkly
    css: styles.css