project:
  type: website
  output-dir: docs
  render: # https://quarto.org/docs/projects/quarto-projects.html#render-targets
    - "/posts/*"
    - "/static/*"
    - "*.qmd"
  preview: 
    port: 1623
brand: assets/_brand.yml

website:
  title: "Hirofumi Shiba"
  image: assets/Shiba2.png
  favicon: assets/Shiba2.png
  site-url: https://162348.github.io/
  description: "A website by a Bayesian Computation Researcher"
  back-to-top-navigation: false
  navbar:
    right:
      - text: "Notes"
        menu:
          - text: "English Notes"
            file: ./static/English.qmd
          - text: "ノート (Japanese)"
            file: blog.qmd
      - text: "Materials"
        file: ./static/Materials.qmd
      - text: "Slides"
        file: ./static/Slides.qmd
      - text: "Software"
        file: ./static/Software.qmd
      - text: "About"
        file: ./static/about.qmd
    tools:
      - icon: github
        href: https://github.com/162348/162348.github.io/
      # - icon: envelope
      #   href: mailto:shiba.hirofumi@ism.ac.jp
      # - icon: twitter
      #   href: https://twitter.com/ano2math5
  page-navigation: true
  page-footer: 
    # border: true
    left: 
      - text: "Hirofumi Shiba"
        href: https://162348.github.io/
    right:
      - icon: github
        href: https://github.com/162348/162348.github.io/
      - icon: twitter
        href: https://twitter.com/ano2math5
      - icon: envelope
        href: mailto:shiba.hirofumi@ism.ac.jp
      - icon: rss
        href: blog.xml
    background: "#80c4ac"
  # repo-url: https://github.com/162348/162348.github.io/
  # repo-actions: [edit, issue]
  search:
    keyboard-shortcut: ["?", "H"]
  open-graph: true
  twitter-card:
    creator: "@ano2math5"
  google-analytics: "G-36GX2G6GLL"
  comments:
    giscus:
      repo: 162348/162348.github.io
      repo-id: R_kgDOKlfKYQ
      category: Announcements
      category-id: DIC_kwDOKlfKYc4CgDmb
      mapping: pathname
      reactions-enabled: true
      loading: lazy
      input-position: top

format:
  html:
    mainfont: "BIZ UDPGothic"
    theme: minty
    # theme: 
    # light: minty
    # dark: cyborg
    css: assets/styles.css
    toc: true
    number-sections: true
    highlight-style: ayu
    code-block-bg: true
    code-block-border-left: "#7CC4AC"
    code-overflow: scroll
    code-fold: true
    code-annotations: select
    # license: "CC BY-NC-ND"
    # fig-width: 6
    # fig-height: 4
    toc-title: "目次"
    abstract-title: "概要"
    include-in-header: assets/include-in-header.html
  # revealjs:
  #   slide-number: true
  #   chalkboard: 
  #     buttons: false
  #   preview-links: auto
  #   logo: assets/profile.jpg
  #   css: assets/slides.css
  #   scrollable: true
  #   smaller: true
  #   controls: true
  #   controls-layout: bottom-right
  #   self-contained-math: true
  #   shift-heading-level-by: -1
  #   toc: true
  #   toc-depth: 2
  #   toc-title: 目次
  #   number-sections: true
  #   theme: serif
  #   show-slide-number: all
  #   include-in-header: assets/forSlides.html
  #   tbl-cap-location: bottom
  #   margin: 0.05
  #   comments: false
  # beamer:
  #   include-in-header: assets/forBeamer.tex
  #   classoption: twocolumn
  #   shift-heading-level-by: -2
  #   pdf-engine: lualatex
  #   linkcolor: ParisGreen
  #   filecolor: ParisGreen
  #   urlcolor: ParisGreen
  #   citecolor: ParisGreen
  #   linestretch: 0.2
  #   link-citations: true
  #   keep-tex: true
  # pdf: 
  #   linkcolor: ParisGreen
  #   filecolor: ParisGreen
  #   urlcolor: ParisGreen
  #   citecolor: ParisGreen
  #   link-citations: true
  #   pdf-engine: lualatex
  #   fontenc: T1
  #   fontfamily: kpfonts  # https://tug.org/FontCatalogue/kpsansserif/
  #   fontfamilyoptions: sfmath

crossref:
    def-prefix: 定義
    def-title: 定義
    thm-prefix: 定理
    thm-title: 定理
    fig-prefix: 図
    fig-title: 図
date-format: "M/DD/YYYY"
csl: assets/apalike.csl
bibliography:
  - assets/2023.bib
  - assets/2024.bib
  - assets/2025.bib

execute:
  freeze: true
  cache: true