project:
  type: website
  output-dir: docs

website:
  title: "Ano2math5"
  image: anomaths.png
  favicon: profile.jpg
  site-url: https://github.com/162348
  description: "A website by a Bayesian Computation Researcher"
  navbar:
    right:
      - text: "Home"
        file: about.qmd
      - text: "Blog"
        file: index.qmd
      - text: "Sessions"
        file: ./static/Lectures.qmd
  open-graph: 
    description: A Blog by a Bayesian Computation Researcher
  twitter-card: 
    creator: "@ano2math5"
    description: A Blog by a Bayesian Computation Researcher
  google-analytics: "G-36GX2G6GLL"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

execute:
  freeze: auto