project:
  type: website
  output-dir: docs

website:
  title: "Hirofumi Shiba"
  image: anomaths.png
  favicon: profile.jpg
  site-url: https://github.com/162348
  description: "A website by a Bayesian Computation Researcher"
  navbar:
    right:
      - text: "Blog"
        file: recent.qmd
      - text: "Sessions"
        file: ./static/Sessions.qmd
      - text: "日本語"
        file: ./static/Japanese.qmd
  open-graph: 
    description: A Blog by a Bayesian Computation Researcher
  twitter-card: 
    creator: "@ano2math5"
    description: A Blog by a Bayesian Computation Researcher
  google-analytics: "G-36GX2G6GLL"
  comments:
    utterances:
      repo: quarto-dev/quarto-web

format:
  html:
    theme: minty
    css: styles.css
    toc: true

execute:
  freeze: auto