project:
  type: website
  output-dir: docs

website:
  title: "Ano2math5"
  image: anomaths.png
  favicon: profile.jpg
  site-url: https://github.com/162348
  navbar:
    right:
      - text: "Home"
        file: about.qmd
      - text: "Blog"
        file: index.qmd
    open-graph: true
    twitter-card: true
  google-analytics: "G-36GX2G6GLL"
format:
  html:
    theme: minty
    css: styles.css
    toc: true