---
title: "シンガポール研究滞在記"
author: "司馬 博文"
date: 6/25/2025
date-modified: 7/11/2025
categories: [Life]
bibliography: 
    - ../../../assets/2023.bib
    - ../../../assets/2024.bib
    - ../../../assets/2025.bib
csl: ../../../assets/apalike.csl
---

## シンガポール生活のはじまり

６月の１日から 30 日までの１ヶ月間，総研大の[研究派遣プログラム](https://www.soken.ac.jp/education/dispatch/sokendai_studentdispatchprogram/)の援助を受けて，シンガポール国立大学の Alexandre Thiéry 准教授を訪問した．

[昨年度のロンドン UCL の訪問](../../2024/Life/UCL.qmd) に続き，人生２度目の研究滞在である．その際は Alexandros Beskos 教授を訪問し，２度目の Alex 訪問でもある．

いずれの Alex も逐次モンテカルロ法 (SMC)，マルコフ連鎖モンテカルロ法 (MCMC) 双方で顕著な業績をあげている，代表的なベイズ計算の研究者である．２人の間には共著も多く，いずれもすでに大変な大物であるが，年齢的にはまだまだ中堅というべきである．

シンガポールの気候はロンドンの対極にある．まず熱くて日差しが強い．緯度１度であることを思えば不思議ではない．

さらに蒸し暑さで悪名高い東京の夏よりも湿度が高い．だが不思議と不快感は少ない．駅に着くまでに汗ダラダラになった，という経験は１度もしていない．おそらく，町中に日陰が多いことと，アスファルトが少なく，代わりに土と街路樹（日本のような人工的な街路樹ではなくて本当に生えている）が多いからだろう．

天気予報を見ると１週間まるまる 100% 雨の予報である週もあったが，かといってほとんど雨は降らない．どういうことかというと，当日中に雨が **１度でも** 降る確率は 100% であるが，それはバケツをひっくり返したような雨で 10 分も続かないのが常である．シンガポールは屋根が多いから，近場で雨宿りしてやり過ごせば，傘を持たずとも１週間過ごせる．

<!-- そして人々の気質も違う．困っている人が居たら率先して助けてくれるのはどちらも同じであるが， -->

しかしロンドンと共通するのは，人々の多様性である．ロンドンとは違いアジア人が多数を占めるとはいえ，マレー系，インド系，中華系に３分され，言語もこの３つを結構似た頻度で聞く．

この多様性が，僕がシンガポールを，そしてロンドンを好きな理由である．

## 共同研究

シンガポールでは週１で滞在先の Thiéry とのミーティングを行った．初回から PDMP の離散化と既存の MCMC との比較という PDMP 研究の一大課題が共有されたため，その後のミーティングも活発にディスカッションが進んだ．

だかそれだけということもなく，多様体上の MCMC 手法 [@Au+2023] や，高次元における粒子フィルター [@Finke-Thiery2023] にも詳しいため，多くのことを学ぶことができた．

自分が追っている研究の最新論文 [@Crucinio-Pathiraja2025] がたまたま出たので，これについて Slack 上で紹介したところ，Thiéry も読んでくれてディスカッションまでしてくれた．

最終日には Hamiltonian Monte Carlo の高次元漸近解析の方向性をまとめ，ドラフトにまとめることまで出来た．帰国後に継続的に取り組む予定をしている．

さらに高次元における PDMP とそのベイズ逆問題への応用についても，その研究の後にやる見通しがついている．

## 研究環境

シンガポールでは初日から Thiéry 氏がポスドクの林氏と，David Nott のポスドクである Lucas を紹介してくれた．

私には机も用意されており，同室にはイタリアから滞在中の Piergiacomo がいた．

出張前には想像もしなかったことだが，私は彼らと，Linda Tan のポスドクである Abhinek も入れて，その後は毎日お昼と４時のティータイムを共にすることになる．

大学に行く機会はあまりないかもしれないと思い，東部のエリアにホテルをとってしまったのだが，彼らとの時間が好きすぎて平日は結局毎日片道１時間かけて通ってしまった．

こんなことならば大学の近くにホテルを借りればよかったと後悔したものであった．

林は訪問時時系列の予測を研究しており，これに SSM-GP と呼ばれる状態空間モデルと Gauss 過程の考え方を両方取り入れた手法を用いていた．

その新規性としては，さらに拡散モデルによる非線型な遷移を可能にしていることにある．

月末にあった BayesComp2025 というベイズ計算最大の国際学会でポスター発表をすることに向けて，最後のシミュレーション欄を詰めていたのだがなぜかうまくいかない点があった．

その点について Thiéry とミーティングをしていたところに，私も同居させてもらい，その日のうちに解決した．

特に粒子フィルターのシミュレーションにおいては，これまた隣に世界的な粒子フィルターの研究者である Hai-Dang も居たにも拘らず，自分が観測ノイズが小さすぎることに問題があることを見抜けた．

結局 [@DelMoral-Murray] に関連する現象であったが，自分の友人を助けたいという気持ちが実ったようで嬉しかった．

## [BayesComp2025](https://bayescomp2025.sg/)

BayesComp は２年に１度開催される，計算に特化した BayesComp-ISBA 主催のベイズ特化の国際学会である．

この分野では最大規模であり，今回もサテライト２日と本会議３日を併せて５日間開催された．

この会議に出席する前に，自分は出席予定のセッションで触れられる論文のほとんど全てに目を通してから出席した．

お陰で聞きたいことをはっきり質問できた機会も多い．さらに何より，インターバル時間に研究者の本音が聞くことによって，自分の知識が有機的に繋がり，２倍にも３倍にもなるのを感じた．

この会議では，自分は残念ながら研究の進捗が間に合わず，ポスター発表はできなかったが，多くの友人に「見たかった」と言ってもらった．次こそはポスターでも口頭でもぜひ発表したいものである．

最も印象に残ったのは Emti による Bayesian Learning Rule に関する講演であった．ベイズ推論の情報理論的な特徴付け [@Zellner1988] は自分にとって大変興味深いものであり，"Bring the science back to ML" の標語は discussion section に参加したみんなの脳裏に残ったであろう．

## 俺の見てきたシンガポール {.appendix}

さらに個人的な経験を書いてしまおうと思う．

基本的に東アジア人の顔をして中華系の料理店に入ると，最初から中国語（標準語）で接客される．コスト的には納得である．牛肉麺とかを beef noodle とか言って注文する気も起きないから，まあ理にかなっているかと思っていた．

しかしある日タクシーに乗って中国語を話したところ，「君ら中国人はマナーが悪い」と説教を受けた．シンガポールは配車アプリが発達しており，運転手と全く会話せずに目的地に到着することも可能であるが，本人確認の都合もあり，確認したいことも多い．それにも拘らず何をいっても一言も喋ろうとしないおそろしい乗客はたいてい中華系なのだという．

あまりにお門違いだと思ったので事情を説明したところ，すぐに通じた．あろうことか，運転手さんは東京に 30 年以上も住んでいたことがあり，自分が日本語を喋ったらすぐにわかってくれた．^[ここで気づくだろうが，僕の中国語は，聞き手がネイティブじゃない限り，僕がネイティブじゃないことは見抜けない完成度がある．] なお，この運転手さんは，マレー系のシンガポール人で，生粋のシンガポール生まれシンガポール育ちであると言っていた．

シンガポールは極めて犯罪率が低く，麻薬使用率も極めて低い．日本で生きていると正直それがデフォルトだと感じてしまうところがあるが，ここまで多様な社会で軋轢がないはずがない．

私は，これは資本主義のマジックだと見る．少なくとも今のシンガポールは，近隣国に比べて圧倒的な富がある．その大きな要因として，英語を公用語に残してあることがある．