---
title: "Séminaire de Statistique"
title-block-banner: true
page-layout: full
toc: false
number-sections: false
comments: false
include-in-header: 
            - text: |
                <style>
                h1, .title, .description {
                  font-family: "Zen Kurenaido", sans-serif !important;
                }
                </style>
bibliography: 
    - ../../assets/2023.bib
    - ../../assets/2024.bib
    - ../../assets/2025.bib
csl: ../../assets/apalike.csl
---

## テーマ

1. 確率過程

    キーワード：semimartingale [@Metivier1982], Malliavin calculus [@Nualart2018], convergence of processes [@Jacod-Shiryaev2003]

    * [@Roberts+1997], [@Christensen+2005] の証明の semi-martingale の視点からの再定式化

    * [@Chevallier+2023], [@Winkler+2024] などの状態空間が変化する過程の列の収束の証明は完成されていない．semi-martingale の視点からの厳密な定式化を目指す．

2. $\mathcal{P}(\mathbb{R}^d)$ の幾何学

    キーワード：JKO scheme [@Figalli-Glaudo2023], Fisher-Rao geometry [@Ay+2017], Wasserstein geometry [@Villani2003]

    * tempering path の Fisher-Rao 幾何に関する解析 [@Aubin-Frankowski+2022], [@Chopin+2023] の証明を，Wasserstein 幾何に関する勾配流の枠組みと同様に，勾配流の数学 [@Ambrosio+2008] を通じて定式化できないか？

    * 平均場 Langevin 拡散の $\mathcal{P}(\mathbb{R}^d)$ 勾配流としての解釈．

    * [@Hoffman-Ma2020] の過程を $d\to\infty$ の極限をとったら，変化点を持つ過程に収束する？最適化とサンプリングの中間を取れば，特定の分布族の中で KL の意味で真の分布との距離を最小にする点に収束する？

    <!-- 応用先：SVGD [@Nusken2024], tempering path [@Chopin+2023] -->

3. 統計的学習理論

    キーワード：empirical process [@Gine-Nickl2021], learning theory [@Bach2024], PAC-Bayes [@Alquier2024]

    * 早期停止に関する研究（離散拡散モデル [@Zhang+2024], ロジスティック回帰 [@Wu+2025] ）はリスク評価を各時点（早期停止点や収束点など）に対して静的に行っているのみである．理論の確率過程化ができないか？

    * SGD path を追う研究 [@Glasgow2024], [@Berthier+2024] もまだ静的な・停止時を用いた解析にとどまっている．

    <!-- 応用先：汎化誤差解析 -->

## 2025 夏

| Location | Time |
|:-----:|:----:|
| ISM 3F | - |

: {.hover .striped .bordered .responsive-sm tbl-colwidths="[20,20]"}