---
title: "粒子フィルターとは何か | About Particle Filter（執筆中）"
author: "Hirofumi Shiba"
date: "11/25/2023"
date-modified: "12/13/2023"
categories: [Particles, Survey]
toc: true
number-sections: true
twitter-card: true
bibliography: bib.bib
csl: ../../../apa.csl
abstract-title: 概要
abstract: 粒子フィルターは今年で30周年を迎える「万能」非線型フィルタリング手法である．相関を持つ粒子系によって分布を逐次的に近似する遺伝的アルゴリズムであり，多くの科学分野にまたがる応用を持つと同時に，数理的対象としても豊かな構造を持つ．その概要と今後の研究方向を紹介する．
crossref:
    sec-prefix: 節
    eq-prefix: 式
---

{{< include ../../../_preamble.qmd >}}

## フィルタリング問題の歴史

### フィルタリング（濾波）問題とは何か？

フィルタ（濾波器）の第一義は，液体から不純物を取り除くための装置である．そのアナロジーで「フィルタリング問題」と言った場合は，信号処理の意味で電圧や電波の信号を「濾過」してノイズを除去し本当に注目したい部分を純粋化する営みのことを指す．凡ゆる通信機器において装置の熱運動によるノイズが入ることは避けられぬ自然の摂理であり，フィルタリング問題は普遍的な課題である．^[[@Anderson-Moore1979-OptimalFiltering] 第1.1節．]

Gaussは天体観測の経験から「誤差論」と最小二乗法を発明し，これが現代の統計的推定理論の先駆けとなった．これと同じように，通信と制御の分野では「時々刻々と受信するデータから時々刻々と変化する信号をどのようにうまく濾波するか」という独自の課題から，独自の理論が発展していった．^[[@有本卓1970]．]

特に，デジタル回路がない時代では，「どのような電気回路のシステムとして濾波機をデザインすれば良いか？」という電気工学的な回路設計の問題としての側面も大きかった．

このアナログフィルタの時代で，フィルタリングの問題を統計的技術で解くための理論^[このフィルタリング問題の統計的な側面を，前述の電気工学的な側面から区別して，stochastic filteringと呼んだりもする．] が，まず離散時間の場合が [@Kolmogorov1941]，続いて連続時間の場合が [@Wiener1949] によって模索された．^[[@Bain-Crisan2009-StochasticFiltering] 1.3節．]

しかし，この Kolmogorov と Wiener 理論では「信号とノイズの過程が定常である」という仮定の下で展開されており，この**定常性の制約が Kolmogorov-Wiener 理論の広い応用を阻んでいた**．

だがこれは，「当時の技術（抵抗器やコンデンサーなど）で実装出来る範囲」という制約がある上で考えられた理論としては，仕方ないことでもあった．更なる理論的発展も，デジタル技術の登場を待つ必要があった．

### デジタルフィルタリングの登場

トランジスタというデジタル技術が使われるようになり，集積回路の製造技術が発達すると，「フィルタ（濾波器）」はアナログデジタル変換器，レジスタ，メモリ，マイクロプロセッサから構成された**デジタルフィルタが主に使われるようになった**．アナログフィルタから物理的な姿は全く変わり，もはや肉眼では見えない装置になってしまったのである．^[[@青山友紀1986] 「当初は大型コンピュータを用いたシミュレーションの技法であったディジタルフィルタが，今では超LSI 1チップで実現されるまでになった．」他にも，発表時1986年では，音声信号を中心とする低周波帯域ではデジタルフィルタがアナログフィルタを駆逐しつつあること，通信システムのデジタル化に伴ってこの勢いは完全に代替するまで進むだろうとの筆者の考えが述べられている．]

その中で [@Kalman1960] が，定常性の仮定が満たされない場合でも使えるアルゴリズムである [**カルマンフィルター**](https://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%AB%E3%83%9E%E3%83%B3%E3%83%95%E3%82%A3%E3%83%AB%E3%82%BF%E3%83%BC) を提案すると，すぐにApollo計画に導入されてスペースシャトルの制御へ実用化され，更には海軍の潜水艦などにも応用されていった．^[[@NASA1985] がNASAからの資料．また，[@DelMoral-Penev2014] も参照．加えて，[@Kalman1960] からちょうど10周年の文献 [@有本卓1970] に当時の雰囲気も感じさせる良いサーベイがある．]

あらゆるシステムがデジタル化されていく中で，アナログフィルタは徹底的にデジタルフィルタに代替されるようになり，最終的に「フィルタ（濾波器）」の語は，「水を濾過する如く電圧情報のノイズを除去する機器」という類比から，デジタル技術の出現により更なる一段階の抽象化を受けて物理的実体も失い，「ノイズを除去してメッセージ部分をなるべく正確に推定するアルゴリズム」という完全に数学的で抽象的な存在として研究が進められていくことになる．

### カルマンフィルターの限界

この Kalman filter は素晴らしかった．特に，Kalman は [**状態空間モデル**](../2023-11-6/SSM.qmd#sec-SSM) という枠組みを導入し，どのようなシステムに適用可能かに関する共通言語を提供したことが，即時的な応用に寄与した面もあるだろう．^[[@Ristic+2004 p.3] "The state-space approach is convenient for handling multivariate data and nonlinear/non-Gaussian processes and it provides a significant advantage over traditional time-series techniques for these problems."] 例えばこの語彙に従えば，「Kalman filter は状態空間モデルが線型正規であれば最適なフィルタリング手法」ということになる．

しかし Kalman filter にも大きな制約があった．それは **モデルが線型かつ正規である場合にしか使えない** ということである．一方で現実のシステムは殆どが非線型性を持つ．

そこで NASA の [Ames 研究センター](https://ja.wikipedia.org/wiki/%E3%82%A8%E3%82%A4%E3%83%A0%E3%82%BA%E7%A0%94%E7%A9%B6%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BC) ではすぐに [**拡張 Kalman フィルタ**](https://en.wikipedia.org/wiki/Extended_Kalman_filter) と共分散行列の二乗根を保持する実装が考案され，これが本当の意味で Kalman フィルターを実用に耐えるものにした [@NASA1985]．^[また，同様にアポロ計画の中で，飛行体に載積出来るような小規模な計算資源と短い単語長でも安定してKalman filterが動くように，共分散行列の二乗根を保持するという "square-root" formulation of the filter が 1972年に考案されたことが，summary でも触れられている [@NASA1985]．]

だが，「拡張」の名前の通り本質的な解決とは言えず，システムの非線型性が強い場合は性能が伸びない．^[[@Julier-Uhlmann2004 p.402] など．拡張 Kalman filter は遷移関数を線型近似することに基づく．よって Jacobi 行列の計算が必要であり，このため **解析的方法** とも呼ばれる [@Ristic+2004 p.21]．よって遷移関数が可微分でない場合も実行不可能である．とはいっても，拡張 Kalman filter はナビゲーションシステムや GPS のデファクトスタンダードである [Wikipedia](https://en.wikipedia.org/wiki/Extended_Kalman_filter#Disadvantages_and_alternatives)．] こうして，計算機や情報通信技術の発展と共に複雑化していくシステムに併せて，様々なフィルターが考案されていく必要があるのである．統計計算の時代の黎明である．

### 非線型性・非正規性という強敵

実は，1960年に開発された Kalman filter を真に超克する手法は，1990年代に入るのを待つ必要がある．他のシミュレーションに基づく [ベイズ計算手法](../2023-12-6/BayesianComp.qmd#sec-MCMC-SMC) と同じく，計算機の十分な発達を待つ必要があったのである．

というのも，Kalman filter は，線型正規状態空間モデルの下でフィルタリング分布 $\L[X_t|Y_1,\cdots,Y_t]$ は再び正規分布であり，平均と共分散という２つの量のみで完全に特徴付けられるため，これらのみを考慮し，微分方程式を解いて更新規則を事前に得ておくことで，計算量を大幅に削減することが出来る，というトリックに基づく．

このように線型性と正規性が同在する状況，または状態空間が有限であるなどの状況でない限り，フィルタリング分布 $\L[X_t|Y_1,\cdots,Y_t]$ は有限次元の十分統計量を持たない．^[[@Ristic+2004 p.16]．]

従って，計算量削減のトリックは絶対に存在せず，正面から分布 $\L[X_t|Y_1,\cdots,Y_t]$ を近似する方法を考える必要がある．これには新しいアイデアが必要であると同時に，一定の性能を持つ計算機の出現を待つ必要もあったのである．

### 種々の近似戦略

フィルタリング分布
$$\bP_t(X_t\in dx_t):=\L[X_t|Y_{0:t}]$$
は Bayes の定理を通じて再帰的な関係
$$
\begin{align*}
    &\bP_{t-1}(X_t\in dx_t|Y_{0:t-1})\\
    &=\int_{x_{t-1}\in E}\bP_{t-1}(X_{t-1}\in dx_{t-1}|\\
    &\qquad Y_{0:t-1}=y_{0:t-1})P_t(x_{t-1},dx_t),\\
    &\bP_t(X_t\in dx_t|Y_{0:t}=y_{0:t})\\
    &=\frac{1}{p_t(y_t|y_{0:t-1})}f_t(x_t|y_t)\\
    &\qquad\bP_{t-1}(X_t\in dx_t|Y_{0:t-1}=y_{0:t-1}).
\end{align*}
$$
を満たすが，この積分を計算する必要がある．^[この結果は [@Choping-Papaspiliopoulos20-SMC] 第5章 など．記法 $Y_{0:t}$ は [本サイトの数学記法一覧](../2023-12-12/Notations.qmd#sec-tuples) を参照]

#### 数値積分による方法

状態空間 $E$ の次元が大きくない場合，積分は数値積分によって近似できる．

状態空間が有限である場合は積分は加法に退化するため，正確に実行することができる．^[[@Choping-Papaspiliopoulos20-SMC] 第6章，[@Ristic+2004] 2.2節．]

さらにMAP推定量を計算する Viterbi 算譜 [@Forney1973] と Baum-Welch 算譜 [@Rabiner1989] とは音声認識の分野で広く使われており，また状態空間が近似的に離散である場合に，近似手法としても用いられる．^[[@Ristic+2004 p.24]．]

#### Gauss混合で近似する方法

フィルタリング分布 $\L[X_t|Y_{0:t}]$ を正規分布の有限混合で近似する方法は **Gaussian sum filter** と呼ばれる [@Sorenson-Alspach1971]．これは多峰性を帯びる事後分布のモデリングに強く，物体追跡の分野で広く使われることとなったが，一般の設定に使える普遍的な手法ではなかった．^[[@Ristic+2004 p.25]．]

#### サンプルによる近似

フィルタリング分布 $\L[X_t|Y_{0:t}]$ を正規分布を表現する決定論的に設計された粒子系によって近似し，これをシステムモデルに従って伝播させる．これにより，フィルタリング分布の2次以下の積率までは性格に近似できていることになる．この手法を **無香 Kalman filter** (Unscenteed Kalman filter) という [@Julier+2000], [@Julier-Uhlmann2004]．

この手法は，宇宙から大気圏に再突入する弾道物体の追跡などの場面で，粒子フィルターよりやや正確性が劣るが計算が速く，実用的であることも知られている [@Ristic+2004 p.101]．

## 粒子フィルターの発明

線型性や正規性の仮定を **一才** 必要としない，全く新しい Monte Carlo 法を用いたフィルタリングアルゴリズムを，[@Gordon+1993] がbootstrap filterという名前で発表し，角度観測のみを用いた物体追跡の問題への応用を付した．

実は，この角度情報のみから物体を追跡するという問題は極めて非線型性が強い問題として古典的なものであり，従来の拡張Kalman filterの方法では精度が全く伸びなかった．これに比べて **bootstrap filter では圧倒的な性能改善が見られたのであった**．

### 逐次重点サンプリングの修正としての粒子フィルター

この技術は基本的には [重点サンプリング](../2023-12-6/BayesianComp.qmd#sec-importance-sampling) を繰り返すという仕組みである．このアイデアは古くからあったが，計算機の性能と，後述（ @sec-degeneracy ）の退化の問題から，実用的だとは見做されていなかった．逐次重点サンプリングは，次元が上がっていくにつれて分散が指数増大するという致命的欠点がある．^[[@Chopin-Papaspiliopoulos20-SMC] 第8.7節 p.95，[@Creal2011] p.253．]

そこで，「リサンプリング」（「選択（セレクション）」ともいう）という新たな機構を各段階に取り入れることを考える．この機構により，次元の呪いを克服し，推定精度が保たれるのであるが，一方で粒子の間に相関が導入されるために，理論的解析を困難にする．この点から粒子フィルターは「（平均場）相関粒子法」「遺伝型粒子フィルター」^[[@DelMoral-Horton2023-EnKF] など] ともいう．^[呼び方については[@DelMoral13-MeanFieldSimulation]と[紹介記事](../2023-11-9/index.qmd#sec-names) も参照．]

たしかに計算負荷はその分上がるが，1990年代では計算機の性能の方がすでにこれを凌駕していたのである．なお，[@Gordon+1993] はリサンプリング手法としては多項リサンプリングを採用しており，極めて実装が簡単という点も多くの応用を生んだ理由である．^[[@Creal2011] p.256．]

北川源四郎も同年（1993年）のカンファレンスにて，Monte Carlo filter の名前で同様のアルゴリズムを発表している．そのジャーナル版は [@北川1996]．^[[Del MoralのWebサイト](https://people.bordeaux.inria.fr/pierre.delmoral/simulinks.html)も歴史的背景に詳しい．] 日本語文献 [@北川源四郎1996-統計数理] は[ウェブ上からも読める](https://www.ism.ac.jp/editsec/toukei/pdf/44-1-031.pdf)．

### 粒子フィルターの応用

[@Gordon+1993] による粒子フィルターの考案は，物体追跡（と防衛目的）への応用が念頭にあり，この分野では粒子フィルターが極めて有効である [@Ristic+2004]．^[[@Yang+2023] は水中での物体追跡が縮退により従来は粒子フィルタが使えなかった問題の解決を試みている．[@Kummert+2021] はロボット支援を用いた手術中に物体追跡を利用する際に，尤度が低すぎるなどの要素から追跡対象を失った状態を検出してアラートを出す機構を開発している．]

ロボティクス，HCI (Human-Computer Interaction) 分野への応用もなされている[@岡2005], [@Wills-Schon2023]．

ファイナンスで扱う時系列は非線型性・非正規性を示すと同時にデータ数も多い．逐次推定のステップ数が増えようとも誤差が蓄積しない粒子フィルターが見事に推定を実行する．^[ファイナンスにおける確率ボラティリティモデルなどの例が挙げられている [@Creal2011] p.256．]

加えて，マクロ経済学の分野で [動学的確率的一般均衡モデル](https://en.wikipedia.org/wiki/Dynamic_stochastic_general_equilibrium) の推定にも応用されている．このモデルは，非線型なミクロ経済学的モデルの上に構築された大規模なモデルで，非線型な1次条件を持つ．^[粒子フィルターの経済学での応用が増えたきっかけが Fernández-Villaverde and Rubio-Ramírez (2005, 2007) による（小規模な）DSGEモデルの推定への応用だった [@Creal2011 p.246]．[@矢野2014] は実物景気循環モデル (Real Business Cycles
Model) への応用を解説している．] このような複雑なモデルでは一般にMCMC法では収束が遅いが，粒子フィルターに焼戻し法や並列計算を組み合わせることでこの問題を回避でき，さらに事後分布が多峰性を持つ場合でさえ有用である [@Herbst-Schorfheide2013]．

近年では[エージェント・ベースド・モデル](https://ja.wikipedia.org/wiki/%E3%82%A8%E3%83%BC%E3%82%B8%E3%82%A7%E3%83%B3%E3%83%88%E3%83%BB%E3%83%99%E3%83%BC%E3%82%B9%E3%83%BB%E3%83%A2%E3%83%87%E3%83%AB)への応用もある [@Lux2018]．

### 粒子フィルターの一般の推定問題への応用

こうして，粒子フィルターは濾波問題の文脈で発明されたMonte Carlo法であるが，状態空間モデルに対する濾波に限らず，種々の設定での逐次的問題，更には逐次的構造を持たない一般の推定問題にも応用できる．この発展により，粒子フィルターはMCMCと合流して，[ベイズ計算](../2023-12-6/BayesianComp.qmd) の主要トピックの１つに躍り出た [@Martin+2023-history p.11]．この意味で，粒子フィルターは広く**逐次Monte Carlo法**（Sequential Monte Carlo methods 略して **SMC** ）とも呼ばれる．^[[@Chopin-Papaspiliopoulos20-SMC] 第3章にSMCのフィルタリング以外の多くの応用が紹介されている．] 

逐次的ではない通常の設定，いわば「静的」な設定の下でのBayes推論にSMCを用いる方法は [@Chopin2002] が草分け的な仕事をした．この枠組みでは，Bayes事後分布 $\pi(\theta|y_1,\cdots,y_N)$ の近似において，途中の $\pi(\theta|y_1,\cdots,y_n)$ を経由して逐次的に近似することが，自然な計算コスト削減法として理解できる．

### 粒子フィルターの欠点 {#sec-degeneracy}

粒子フィルターは高い汎用性の代償として，多数の粒子を用意したいなら計算量が多くなることを欠点に持つ．従って，粒子フィルターは，他の手法が実行不可能なほどの非線型性・非正規性を示す問題に（のみ）用いるべきというものである．が，CPUや並列計算の発展により十分な量の粒子を用意できる場面も増えたため，その問題点も形骸化してきてると言える．^[[@矢野2014] p.190，[@Ristic+2004] 前文 p.xi．]

また，粒子フィルターは，観測 $Y_t$ の次元が大きいなど，観測から得られる情報量が多く，尤度（ポテンシャル）の尖度が高いとき，多くの粒子が小さな荷重を持ってしまう．この状態は近似精度悪化の原因となり**縮退**と呼ばれる．^[[@Chopin-Papaspiliopoulos20-SMC 19.1節 p.371], [@Creal2011 2.5.1節 p.258]．] そのような場合は，観測の情報を柔軟に取り入れた提案核を構築し，誘導粒子フィルターをうまく設計する必要がある．

地球科学や天気予報の分野では $Y_t$ は大きく（$10^7$を超えることもある），このような場合は粒子フィルターは実行可能でなくなる．加えてKalmanフィルターも行列計算の部分が実行不可能になり，アンサンブルKalmanフィルタという粒子法が用いられる．

## 今後の研究

粒子フィルターの応用には次の点の研究が肝要である．^[[@Ristic+2004] Epilogueに次の言葉がある
> "The key factors for a successful application of particle filters in practice are therefore a good choice of the importance density and Rao-Blackwellization if possible.""
]

### 提案分布の取り方

@sec-degeneracy で触れた通り，特に観測の情報量が大きい場合，提案分布の選び方が粒子フィルターの精度を大きく左右するが，この取り方について普遍的な指針というものが得られていない．

[@Guarniero+2017] と [@Heng+2020] は提案分布にパラメトリックモデルを用意し，粒子推定量の分散を最小化するようにそのモデル内で逐次的に最適化していく機構を提案している．

[@Naesseth2015] が提唱するnested SMCは，は各時刻での提案分布を近似するために，もう一つのSMCを内部に走らせる．当然計算量は二倍になるが，それでも単純なbootstrap filterから大きく性能が改善する場合が多い．

> 粒子フィルタを適用する際の課題の一つは，各粒子に割り当てられる重みが1粒子に集中する，いわゆる退化の問題を限られた数の粒子でいかに克服するかである．[@上野玄太2019]

### 部分的な線型構造の利用

周辺化粒子フィルター，またはRao-Blackwellized particle filterとも呼ばれる方法である．これは多くの場面で，仮定されている状態空間モデルが部分的に線型である場合に，線型の部分をKalmanフィルターによって正確に解き，残った部分のみを粒子フィルターで解くことで，精度の向上とアルゴリズムの効率化を図る方法である．

[@Ristic+2004 p.287] では，探知前追跡 (track-before-detect) の問題^[探知前追跡とは，信号が弱い，またはノイズが強い環境下において，信頼のおける初期信号を頼りにせずとも，物体追跡を実行するための手法．]において，周辺化粒子フィルタが，必要な粒子数を大きく削減してくれることを紹介している．

その他にも，問題毎の特有の構造を利用して計算量を削減・パフォーマンスを最適化することは重要な営みである．

### 粒子数に関する漸近論

目前の問題を，所与の精度で解くために必要な粒子数は幾ばくか？という問題は実用上も有益だと思われる．^[[@Ristic+2004 p.288] に示唆されている．]

### 属人化医療への応用

筆者は属人化医療への応用が大きなモチベーションになっている．^[[過去の記事](../2023-11-6/SSM.qmd)でも触れた．]

病気の進行（あるいは健康）のモニタリングのために，健康診断やウェアラブルデバイス，フォローアップから得られるデータは，治療の見直しや異常の早期発見のために即時処理されることが望ましい．これに逐次モンテカルロ法でBayes的に迫る研究がある [@Alvares+2021] ！

さらに，個々人の日常生活のレベルではSMCを用いているものはどうやらまだなく，運動と睡眠時間の間の関係と処置効果をMonte Carlo法を用いて推定している研究はある [@Daza-Schneider2022]．これを逐次化することで，よりリアルタイムで自分に合った生活習慣への示唆が得られるアプリを開発できるかもしれない．

また，属人化医療においてはシステム生物学的なモデルに基づいた薬効推定が欠かせない．小規模な患者群と測定時間（服薬時間）に関する不確定性を考慮した手法が [@Krengel+2013] で考察されている．

次世代DNAシークエンサーでは，DNAの各塩基ごとに異なる蛍光物質を結合させ，蛍光の波長と強度により塩基を読み取る仕組みであり，蛍光強度の生データからDNA配列データへ変換するベースコールと呼ばれる段階で粒子フィルターを使うことも提案されている [@Shen-Vikalo2012]．

また，腫瘍サンプルに含まれる体細胞の突然変異に関するデータから，SMCを用いて腫瘍の発達と進行の状態を理解する手法も提案されている [@Ogundijo+2019]．

Covid-19のようなパンデミックにおいて，疫学モデルを通じて時間変動する再生産数をリアルタイムでモニタリングをして意思決定に繋げるためのSMC手法も考えられており，実際にノルウェーで使用され有効性が実証された [@Strovik+2023]．

状態空間が高次元になることと，既存のモデルを状態空間モデルに定式化することに困難が伴うことが，朧げながら共通課題のように思われるが，その現れ方と解決法は個々の事例で異なる．