---
title: "Butkovsky and Veretennikov (2013) On Asymptotics for Vaserstein Coupling of Markov Chains"
author: "司馬博文"
date: 4/4/2024
image: Butkovsky-Veretennikov2013.svg
categories: [Review, Kernel]
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
abstract-title: 概要
abstract: |
    Butkovsky and Veretennikov [Stochastic Processes and Their Applications 123(2013) 3518-3541] は対称とは限らないエルゴード的な Markov 連鎖の収束レートを，カップリングの方法を用いて導出した仕事．
---

{{< include ../../../_preamble.qmd >}}

## 概要

* マルチンゲールによる導出
* Lyapunov 型の条件が簡単に十分条件を与えるような，再帰時刻による取り扱い

[@Kulik2018 p.45-] では，安定性の定理の証明に，マルチンゲールを用いた議論を用いている．エルゴード性を持つ Markov 連鎖は必ず

1. 局所的な集合上で良い攪拌性を持ち，
2. その他の点に行ってしまった場合でも，「十分早く」その局所的な集合に戻ってくる

という２つのモードを持つ．これを別々に解析する見通しの良い議論を与えてくれるのがマルチンゲールによる議論であるとしている [@Kulik2018 p.71] が，似たような議論をしているのが本論文 [@Butkovsky-Veretennikov2013] である．^[それと [@Durmus+2016] を挙げている．]

## 背景

* 一様エルゴード性を **strongly ergodic** とも呼んでいる：
$$
\sup_{x\in E}\norm{P^n(x,-)-\pi}_\TV\le Ce^{-\lambda n}.
$$

* 一方で，各点 $x\in E$ で
$$
\norm{P^n(x,-)-\pi}_\TV\to0
$$
が成り立つことを **weakly ergodic** と呼んでいる．

本論文では，$\lambda$ を推定する [@Diaconis-Stroock1991] 理論を，weakly ergodic の場合と非対称な場合に拡張する．

すると，[@Diaconis-Stroock1991] 理論では遷移確率核 $P$ のスペクトルギャップであった $\lambda$ は，一般の設定の下でもある一般化した半群生成作用素のスペクトル半径に関係することがわかった．

### [@Diaconis-Stroock1991] 理論

一様エルゴード性の収束速度 $\lambda$ を定量化するアプローチの１つ．

::: {.callout-tip title="定理"}
有限状態空間 $E$ 上の $P$-一様 Markov 連鎖は，既約かつ対称ならば，
$$
\lambda<\log\operatorname{Gap}(P)
$$
$$
\operatorname{Gap}(P):=\max\Brace{\abs{\lambda}\in\R_+\mid1>\lambda\in\Sp(P)}
$$
:::

* 対称ならば $P=P^*$．
* スペクトルギャップは一般の正作用素に定義できる．

### [@Vaserstein1969] による最適カップリングの構成

これを一般化したという．

最適な Markov カップリングよりも，カップリング確率が高いカップリングがあるらしい（しかし Markov にならない）．[この稿](../Process/Coupling.qmd) に書いた．

### Lyapunov 型の条件

[@Douc+2004], [@Kalashinikov1973], [@Lamperti1960], [@Rosenthal2002], [@Tweedie1981] による．

## 本論

### カップリング補題

本論に入る前に，次の結果を準備している：

::: {.callout-tip title="補題（カップリング不等式の評価）^[[@Butkovsky-Veretennikov2013 pp.3521-22] 補題2.2]"}

$X_1,X_2$ を確率核 $P$ を持つ Markov 連鎖，$Z=(X_1,X_2)$ をその最適 Markov カップリングを
$$
X_n^1=:\xi_n1_{\Brace{\zeta_n=0}}+\eta_n^11_{\Brace{\zeta_n=1}}
$$
$$
X_n^2=:\xi_n1_{\Brace{\zeta_n=0}}+\eta_n^21_{\Brace{\zeta_n=1}}
$$
とする．このとき，
$$
\P[X_n^1\ne X_n^2]\le\Paren{1-p_0}\E\Square{\prod_{k=0}^{n-1}\Paren{1-p(\eta_k^1,\eta_k^2)}}
$$
$$
p(x_1,x_2):=1-\frac{1}{2}\norm{P(x_1,-)-P(x_2,-)}_\TV
$$
$$
p_0:=1-\frac{1}{2}\norm{\P^{X_0^1}-\P^{X_0^2}}_\TV=\P[X_0^1=X_0^2]
$$
が成り立つ．

:::

::: {.callout-note title="証明" collapse="true"}

基本的な考え方は
$$
\begin{align*}
    \P[X^1_n\ne X_n^2]&\le\P[\zeta_0=1,\zeta_1=1,\cdots,\zeta_{n}=1]\\
    &=\E[1_{\Brace{\zeta_0=1}}1_{\Brace{\zeta_1=1}}\cdots1_{\Brace{\zeta_{n}=1}}]
\end{align*}
$$
である．これは，$X_n^1\ne X_n^2$ ならば $\zeta_n=1$ が必要であるため，
$$
\begin{align*}
    \Brace{X_n^1\ne X_n^2}&\subset\Brace{\zeta_n=1}\\
    &=\Brace{\zeta_0=1,\zeta_1=1,\cdots,\zeta_{n}=1}
\end{align*}
$$
であるが，逆は必ずしも成り立たないためである．

これに，$\F_n:=\sigma[X_n^1,X_n^2]$ について，
$$
\begin{align*}
    &\E\Square{\prod_{i=k}^n1_{\Brace{\zeta_i=1}}\,\middle|\,\F_{k-1}}\\
    &=\E\Square{\prod_{i=k-1}^{n-1}\Paren{1-p(\eta^1_i,\eta_i^2)}\,\middle|\,\F_{k-1}}1_{\Brace{\zeta_{k-1}=1}}
\end{align*}
$$
の $k=1$ の場合を併せて結論を得る．この等式自体は降下法により示す．

$k=n$ の場合の式
$$
\E[1_{\Brace{\zeta_n=1}}\mi\F_{n-1}]=\Paren{1-p(\eta_{n-1}^1,\eta_{n-1}^2)}1_{\Brace{\zeta_{n-1}=1}}
$$
は明らかである．$k<n$ の場合，帰納法の仮定と，$\F_{k-1}$ の下で $\zeta_k$ と $(\eta_k^1,\eta_k^2)$ は条件付き独立であるから，次のように式変形できる：
$$
\begin{align*}
    &\quad\E\Square{\prod_{i=k}^n1_{\Brace{\zeta_i=1}}\,\middle|\,\F_{k-1}}\\
    &=\E\Square{1_{\Brace{\zeta_k=1}}\E\Square{\prod_{i=k+1}^n1_{\Brace{\zeta_i=1}}\,\middle|\,\F_k}\,\middle|\,\F_{k-1}}\\
    &=\E\Square{1_{\Brace{\zeta_k=1}}\E\Square{\prod_{i=k}^{n-1}\Paren{1-p(\eta^1_i,\eta^2_i)}\,\middle|\,\F_k}\,\middle|\,\F_{k-1}}\\
    &=\E[1_{\Brace{\zeta_k=1}}\mi\F_{k-1}]\E\Square{\prod_{i=k}^{n-1}\Paren{1-p(\eta^1_i,\eta^2_i)}\,\middle|\,\F_{k-1}}\\
    &=1_{\Brace{\zeta_{k-1}=1}}\Paren{1-p(\eta^1_{k-1},\eta^2_{k-1})}\E\Square{\prod_{i=k}^{n-1}\Paren{1-p(\eta^1_i,\eta^2_i)}\,\middle|\,\F_{k-1}}\\
    &=1_{\Brace{\zeta_{k-1}=1}}\E\Square{\prod_{i=k-1}^{n-1}\Paren{1-p(\eta^1_i,\eta^2_i)}\,\middle|\,\F_{k-1}}\\
\end{align*}
$$

:::

この補題により，確率核 $P$ を共有する２つの Markov 過程 $(X_n^1),(X_n^2)$ が与えられたとき，これらのカップリング $(\wt{X}^1_n),(\wt{X}^2_n)$ を同一の確率空間 $(\Om,\F,\P)$ 上に構成し，$(\wt{X}_n^1)\deq(X_n^1),(\wt{X}_n^2)\deq(X_n^2)$ であるが，全変動距離を $\P$ によって評価できるようになる．

### スペクトルギャップによる一様エルゴード速度

次の積分作用素 $A:\L_b(E^2)\to\L_b(E^2)$ を考える：
$$
Af(x):=\Paren{1-p(x)}\E[f(\eta_1)\mi\eta_0=x]
$$
$$
\eta_i=\vctr{\eta_i^1}{\eta_i^2},\quad x=\vctr{x^1}{x^2}.
$$
このスペクトル半径
$$
r(A):=\limsup_{n\to\infty}\sqrt[n]{\norm{A^n}}
$$
が一様エルゴード性を引き起こすのである．

::: {.callout-caution title="証明の概略" collapse="true"}
なお，この定義式は，後述の $r(A)\le1$ と併せると，任意の $\ep>0$ に対して，ある $C>0$ が存在して，$r(A)\le r(A)^{1-\ep}$ であるから，
$$
\begin{align*}
    \norm{A^n}&\le C\paren{r(A)^{1-\ep}}^n\\
    &=Ce^{n(1-\ep)\log r(A)}\\
    &=Ce^{-n(1-\ep)\log\abs{r(A)}}
\end{align*}
$$
を含意することに注意．

実は次の定理の証明は，次の不等式を導いているのみである：
$$
\frac{1}{2}\norm{P^n(x,-)-P^n(y,-)}_\TV\le\norm{A^{n}}.
$$

この２式より，直ちに証明が完成する．
:::

ただし，作用素ノルム $\norm{A^n}$ は任意の $\norm{1}=1$ を満たす関数ノルムに関して構成して良い．$C_b(E^2)$ を考えることも有用である．

いずれにしろ，
$$
\norm{A}_\infty=1-\inf_{x\in E^2}p(x)\le1
$$
という条件式は変わらない．作用素ノルムの劣乗法性から
$$
r(A)=\limsup_{n\to\infty}\sqrt[n]{\norm{A^n}_\infty}\le\norm{A}_\infty\le1
$$
であることに注意．

::: {.callout-tip title="定理^[[@Butkovsky-Veretennikov2013] 定理2.1．]"}

1. $A:\L_b(E^2)\to\L_b(E^2)$ は有界作用素であり，$r(A)\le1$ を満たす．
2. $r(A)<1$ ならば，$X$ はただ一つの不変確率測度を持ち，任意の $\ep>0$ に対して，初期分布 $X_0^1,X_0^2$ に依らないある $C>0$ が存在して，
$$
\norm{\P^{X_n^1}-\P^{X_n^2}}_\TV\le C(1-p_0)e^{-n\abs{\log r(A)}(1-\ep)}.
$$
:::

::: {.callout-note title="証明" collapse="true"}
一般に，任意の $f\in\L_b(E^2)$ に対して，$(\eta_k)$ のMarkov性より，
$$
\begin{align*}
    \E\Square{f(\eta_n)\prod_{i=0}^{n-1}\Paren{1-p(\eta_i)}}&=\E\Square{\E\Square{f(\eta_n)\prod_{i=0}^{n-1}\Paren{1-p(\eta_i)}\,\middle|\,\eta_0,\cdots,\eta_{n-1}}}\\
    &=\E\Square{\prod_{i=0}^{n-2}\Paren{1-p(\eta_i)}\cdot\Paren{1-p(\eta_{n-1})}\E[f(\eta_n)\mi\eta_{n-1}]}\\
    &=\E\Square{\prod_{i=0}^{n-2}\Paren{1-p(\eta_i)}\cdot Af(\eta_{n-1})}=\E[A^nf(\eta_0)].
\end{align*}
$$
これより，$\Brace{\eta_n=0}\supset\Brace{\prod_{k=0}^{n-1}\Paren{1-p(Z_k)}=0}$ に注意すれば，次の評価を得る：
$$
\begin{align*}
    \norm{P^n(x,-)-P^n(y,-)}_\TV&\le2\P_{(x,y)}^Q[X_n\ne Y_n]\le2\E_{(x,y)}^{Q_\perp}\Square{\prod_{k=0}^{n-1}\Paren{1-p(Z_k)}}\\
    &=2\E_{(x,y)}^{Q_\perp}\Square{\delta_1(\eta_n)\prod_{k=0}^{n-1}\Paren{1-p(Z_k)}}=2\E_{(x,y)}^{Q_\perp}[A^{n-1}\delta_1(\eta_1)](1-p(\eta_0))\\
    &\le2\delta_{x,y}\norm{A^{n-1}}_\infty
\end{align*}
$$
よって，$\frac{1}{2}\norm{P^n(x,-)-P^n(y,-)}$ はちょうど作用素ノルム $\norm{A^{n-1}}$ を評価する問題に帰着する．
:::

### 再帰性と非一様エルゴード速度

$$
\norm{A}_\infty=1-\inf_{x\in E^2}p(x)=1
$$
の場合に当たるものであるが，
$$
K(\ep):=\Brace{x\in E^2\mid p(x)\ge\ep}
$$
に無限回再帰するとき，その頻度に依存して，指数的か多項式的か決まる．^[前節から判る通り，局所Dobrushin条件を満たす集合（small set ともいう）上では常に指数収束である．] この頻度は，次の帰着時間 $\tau^B,T^B$ の積率条件で記述される：
$$
\tau^B:=\inf\Brace{n\ge1\mid\eta_n\in B}
$$
$$
T^B:=\inf\Brace{n\ge1\mid(X_n^1,X_n^2)\in B}
$$
ただし，$B\in\cE^{\otimes2}$．

::: {.callout-tip title="命題2.1"}
ある $\ep,\lambda,M>0$ と $\cE^{\otimes2}\ni B\subset K(\ep)$ について，次が成り立つとする：

1. $Q:=\E[e^{\lambda\tau^B}]<\infty$．
2. 任意の $x\in B$ について，$\E_x[e^{\lambda\tau^B}]\le M$．

このとき，$X$ はただ一つの不変確率測度 $\pi$ をもち，またある初期分布 $(X_0^1,X_0^2)$ に依らない $C>0$ が存在して，
$$
\norm{\P^{X_n^1}-\P^{X_n^2}}_\TV\le CQe^{-n\theta}
$$
$$
\theta:=\frac{\abs{\log(1-\ep)}\lambda}{\log M+\abs{\log(1-\ep)}}
$$

:::

::: {.callout-tip title="定理2.2"}

ある $\ep>0,\lambda>0,M>0,\cE^{\otimes2}\ni B\subset K(\ep)$ について，次が成り立つとする：

1. $Q_2:=\E[e^{\lambda T^B}]<\infty$．
2. 任意の $x\in B\setminus K(1)$ について，$\E_x[e^{\lambda T^B}]<M$．

このとき，過程 $X$ はただ一つの不変確率分布 $\pi$ をもち，ある初期分布 $(X_0^1,X_0^2)$ に依存しない定数 $C>0$ が存在して，
$$
\norm{\P^{X_n^1}-\P^{X_n^2}}_\TV\le CQ_2e^{-n\theta_1}
$$
$$
\theta_1:=\frac{\abs{\log(1-\ep)}\lambda}{\log M+3\abs{\log(1-\ep)}}.
$$

:::

::: {.callout-tip title="定理2.3"}
ある $\ep>0,\lambda\ge1,M>0,\cE^{\otimes2}\ni B\subset K(\ep)$ について，次が成り立つとする：

1. $Q_3:=\E[(T^B)^\lambda]<\infty$．
2. 任意の $x\in B\setminus K(1)$ に対して，$\E_x[(T^B)^\lambda]<M$．

このとき，過程 $X$ はただ一つの不変確率分布 $\pi$ をもち，任意の $\lambda_1\in(0,\lambda)$ に対して，ある初期分布 $(X_0^1,X_0^2)$ に依存しない定数 $C>0$ が存在して，
$$
\norm{\P^{X_n^1}-\P^{X_n^2}}_\TV\le CQ_3n^{-\lambda_1}
$$

:::

## 例

あ