---
title: "Peters and de With (2012) Rejection-Free Monte Carlo Sampling for General Potentials"
author: "司馬 博文"
date: 4/6/2024
date-modified: 4/27/2024
categories: [Review]
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
abstract-title: 概要
abstract: |
    [@Peters-deWith2012] は Metropolis 法による棄却-採択の代わりに，衝突により方向を変える粒子を想定することで，効率的な Monte Carlo 法を実行することを目指した．ただの event-driven な molecular dynamics と違い，一般の滑らかなポテンシャルに適用可能である点が革新的である．しかし，粒子系のポテンシャルは常に和の形で表されるように，一般の PDMP に基づいた連続時間 MCMC 手法も，適用可能なモデルの範囲が限定されている点が難点である [@Nemeth-Fearnhead2021]．
---

{{< include ../../../_preamble.qmd >}}

## 概要

統計用語でいう Bouncy Particle Sampler を，Metropolis-Hastings 法の連続時間極限として初めて提案した論文であるが，これが [@Bouchard-Cote+2018-BPS] に発見されるには６年の時間を要した．

これを正準分布からのサンプリング法として導入した [@Peters-deWith2012] ではこの手法を event-driven rejection-free Monte Carlo 法と呼ぶ．連続なポテンシャル $E$ を用いることが可能なことが特徴．event-driven アプローチだけでなく，event-chain アプローチでの実装も扱った．Lennard-Jones ポテンシャルを持った流体のシミュレーションで検証した．

### 備考

* ここでは本質的には連続時間極限をとっているが，直接議論されているのはポテンシャルの細分化の連続極限である．
  * $U(x(t))$ があったとき，$\Delta U\to0$ の極限を考えているために，実質的に $\Delta t\to0$ を議論している．
* 多粒子系のなすカノニカル分布からのサンプリングを考えているため，分布が積の形に分解できることを前提としている．

## 背景

### time-driven から event-driven へ

（古典）統計力学に従って粒子系をシミュレーションする際には，MD (molecular dynamics) と MC (Monte Carlo methods) の組み合わせ [@Duane+1987] を用いることになるが，現状いずれも Metropolis [@Metropolis+1953] の採択-棄却の枠組みで実行されるのが最も一般的である．

Metropolis の方法だと，

* 凝縮系では MD 法としてのタイムステップは小さく取る必要があると同時に，他の粒子と重なってしまいやすく，棄却率が高くなる．
* 希薄系ではタイムスケールは分子の衝突過程に依存するので，シミュレーション時間のほとんどは無駄に使う必要が出る．

という難点がある．

同様にして，time-driven MD も剛体球などの撃力相互作用を及ぼしあう系ではうまく働かないため，明らかに event-driven な方がいい．これは最初の MD 法 [@Alder-Wainwright1959] で取られた通りの作戦である．

いずれの場合も event-driven な手法を用いることで効率化される可能性がある．

### ED-MD の改良

かといって event-driven MD にも難点がある．

ED-MD はポテンシャルが単関数である場合にまでしか一般化できない．単関数でないと，いつイベントが起こるかが予測できないのである．

しかし本手法は，イベントを Poisson 過程でシミュレーションすることにしたので，一般のポテンシャルに適用できる（ @sec-effectiveness-of-potentials も参照）．

また，衝突のモデリングも event-chain 手法 [@Bernard+2009], [@Bernard-Krauth2011] 同様，選択の余地があり，SEC のように衝突時の動きを被衝突粒子が模倣するでも良いし，普通にビリヤードのように Newton 力学的衝突をモデリングするのでも良い．

### 他の手法との比較

アルゴリズム的には kinetic / dynamic MC  [@Fichthorn-Weinberg1991] $n$-fold way MC simulation [@Bortz+1975] に似て Poisson 過程のシミュレーションに帰着する．

だが本手法は，イベントをシミュレーションしたのちに，そのイベントの間の粒子系の動きは線形に補間される．

### 分子動力学

分子動力学法 (MD: Molecular Dynamics simulation) は，系のミクロなダイナミクスを実験的に調べる代わりに，シミュレーションによって必要条件を絞り込んでいく構成的な・計算機集約的なアプローチである．

特に，多体系の運動方程式を計算機を用いて数値的に解くことを指す [@Alder-Wainwright1959]．それ故，物理や化学はもちろん，生化学，物質科学，さらには工学分野にまで幅広く用いられるシミュレーション法になる．

> the inescapable conclusion is that MD will — if it hasn’t already — become an indispensable part of the theorist’s toolbox. [@Rapaport2004 p.ix]

従来は実験と理論が相補的な関係にあったが，まるで基盤モデルが強化学習のための効率的な世界モデルになるように，計算機シミュレーションと Monte Carlo 法が新時代の科学の第三の要素になるのかも知れない．^["What distinguishes computer simulation in general from other forms of computation, if such a distinction can be made, is the manner in which the computer is used: instead of merely performing a calculation, the computer becomes the virtual laboratory in which a system is studied - a numerical experiment." [@Rapaport2004 p.3]．]

アイデア自体は当然極めてナイーブであり，Laplace の悪魔や気体分子運動論の時代から大変に意識されたが，その最初の非自明な適用はデジタルコンピュータ完成のあとであった [@Alder-Wainwright1958], [@Alder-Wainwright1959]．

彼らの関心は，ポロニウムなどの剛体球 (hard-sphere) の系とみれる物質の温度に依存した相転移現象にあった [@Alder-Wainwright1957]．[@Alder-Wainwright1959] では撃力相互作用 (impulsive interaction) が問題であったので，event-driven なシミュレーション (ED-MD scheme) が取られていたことは [@Peters-deWith2012] でも言及されている．当時の計算機では，500個の粒子を扱うことが限界であったことが興味深い．

その他に，粒子に内部構造がない場合は time-driven な Newton 力学のシミュレーションで良いかもしれないが，剛体で体積を持つ場合は Euler 方程式，内部構造を持つ場合は Langrange 方程式のシミュレーションも伴うかもしれない [@Rapaport2004 p.4]．

通常の平衡状態の（エネルギー・体積・粒子数一定の）分子系は小正準集団に対応するが，特定の温度条件下での物性を考えたい場合は，運動方程式を修正してシミュレーションする方法もある．この方法の欠点は，物性を再現できても，個々の分子の軌道を正しく模倣しているわけではないという点であるが，そもそもそのカオス的な振る舞いから，正しい軌道を得ることは諦めることが多い．このこともあり，MD 法で用いられる数値積分法は比較的低次元で軽量なものでも十分なのである [@Rapaport2004 p.4]．^[内部構造がある分子をシミュレーションする場合はよりやわらかい相互作用を考える必要があり，その際は積分は高次元になる上に，内部の運動が高速であるためにタイムステップも細かくする必要が出てくる．さらに拘束条件が存在する場合は，積分法よりも高い精度で取り扱う必要があり，特別な注意を要する．]

#### 他手法の可能性

セルオートマトンや格子ボルツマン法などの格子ベースの手法の方が計算量は安価であるが，表現力に劣ることになる．

Lanvegin 方程式に基づいた Brownian dynamics などのさらに連続時間ベースの手法もある．

### 統計力学で用いる分子動力学法

統計力学で用いられる Monte Carlo 法と molecular dynamics には極めて深い繋がりがある．

#### 布置平均を取る方法

一度 MD の文脈を取り去り，純粋に統計力学的な量を Monte Carlo 法によって計算したいとする．

やりたいことは抽象的には，その統計的集団の Boltzmann 分布から系をサンプリングできれば良い [@Liu2004 p.184]．

典型的には MCMC によって行うこととなるが，結局その提案は MD によって示唆されたものの方が効率が良くなる．

> The advantage of the MD proposal is that the resulting MCMC moves follow the dynamics of the target distribution more closely. [@Liu2004 p.184]

これは結局，背後の物理学的な本質を捉えているためとも言える

> A major advantage of molecular dynamics simulation in physical systems is its reliance on basic physics principles (e.g. Newton's equation), which has been shown by nature to work well. [@Liu2004 p.189]

#### 時間平均を取る方法

統計力学において，マクロ物理量はアンサンブル平均として計算され，エルゴード仮説の下では１つの系の時間発展を追うことで計算できることになる．

これに MD を用いるとすると，自然と Monte Carlo シミュレーションのサブルーチンとして MD を用いることになるが，タイムステップが系の特徴的な事象をよく捉えるように注意して取る必要がある．特に，系のハミルトニアンが変化しすぎないように離散化誤差を抑える必要がある [@Liu2004 p.184]．

特に MD シミュレーション自体が（温度と粒子数が一定な）小正準集団に対応することになる [@Rapaport2004 p.6]．

> **混合モンテカルロ／分子動力学法**：モンテカルロ法を用いた構造分布の生成において，試行に用いる構造をニュートンの運動方程式など決定論的手法に従って用意する手法．分子凝集系などの複雑な系に対して，効率的に構造空間探索を行えると期待される．[@用語解説2022]

#### Optimal scaling の問題

ここで，optimal scaling と並行な，**タイムステップ選択の問題** がやはり中核となることが確認された．

> how to choose a good step size has always been an art in the field. [@Liu2004 p.183]

特に，凝縮系において系を放置し過ぎると，すぐにハミルトニアンが保存されなくなってしまうため，MD を用いた Monte Carlo 法では極めてタイムステップを細かくすることが必須であることが一番の問題である．

> a main problem with MD simulation is the stringent requirement of a small time-step size. [@Liu2004 p.189]^["For example, the protein folding process takes about $10^{-3}$ seconds in nature. A proper MD simulation of such a process needs a step size of order $10^{-12}$ and will take about $10^6$ days using a current computer."]

かといって，MD から遊離した MCMC を実行して性能を上げるためには，何かしらの形で遷移核に分布の形状を通知したいところであるが，これは MD 法なしには難しいということになる．^[For example, if the system of interest consists of closely packed particles, a random proposal for moving a particle is most likely rejected because the proposed new position has been partially occupied by others. [@Liu2004 p.189]]

明らかに分布が特殊な形状をしているのに，ランダムウォークがその方向を見つけるまで待つのでは効率が悪い．

#### Hamiltonian Monte Carlo 法

そこで，完全な MD シミュレーションは行わず，Hamiltonian からの知識を部分的に提案核に取り入れるというアイデアが HMC (hybrid Monte Carlo) [@Duane+1987] として示された．^[特に格子場の理論において，Fermion 自由度が存在する場合のシミュレーションを問題として扱っていた．]

後に，統計力学的な背景を持たないサンプリング問題についても，Hamilton 系から示唆された提案分布を用いる方が MCMC として性能が良いことが発見された．これが HMC (Hamiltonian Monte Carlo) 法 [@Neal1996] である．

### ポテンシャルの役割 {#sec-effectiveness-of-potentials}

例え量子系のシミュレーションであろうとも，Born-Oppenheimer などの近似を重ねて，原子に働く有効ポテンシャルにのみ注目することにより，古典系のシミュレーションと同様の方法で実行することができ，多くのマクロ的な性質を再現することが出来ることが，[@Griebel+2007 pp.17-] に詳細に説明されている．

実際の系での粒子間相互作用を決定する際，純粋に Schrödinger 方程式などから理論的に導出するだけでなく，解析的に記述されたポテンシャルをフィッティングしてみてそれが理論や実験に合致するかどうかを見る統計的な方法もとられる [@Griebel+2007 p.27]．このようなモデル選択の立場に立つのが良い [@戸田+2011 p.34]．

多くの場合ポテンシャルは，粒子間距離や角度，座標などの変数が入っており，これらのパラメータを推定することで探されるが，当然このステップは難しいものである：

> The construction of good potentials is still a form of art and requires much skill, work, and intuition. [@Griebel+2007 p.28]

Morse ポテンシャルや Lennard-Jones ポテンシャルがその代表例である．いわば，これらのポテンシャルも模型なのである．半導体のモデリングなどでは，さらに複雑なポテンシャルが必要になる [@Griebel+2007 p.30]．

このように，多体問題をポテンシャル関数によって解く手法は 1980 年代からである [@Griebel+2007 p.30]．ポテンシャル関数の形によって、適した数値計算アルゴリズムが異なる。特に、長距離力の高速計算のためには、ポテンシャルの性質を巧みに利用したアルゴリズムが必要である。

#### システム同定としての物理学

> What do we mean by “understanding” something? We can imagine that this complicated array of moving things which constitutes “the world” is something like a great chess game being played by the gods, and we are observers of the game. [@Fenyman+1963]

> 今まで見てきたように，状態空間モデルは運動学習過程を統一的に説明するモデルであり，最適推定や最適制御の定式化に欠かせない．一方，状態空間モデルに含まれる行列の値は，運動方程式などといった物理的要請から決定できることもあるが，運動適応の学習係数などは未知のパラメータであることが多い．従って，与えられた実験データから状態空間モデルのパラメタを決定する必要がある．このパラメタ推定は制御理論において **システム同定** と呼ばれる．冒頭の引用のように，ファインマンは数学や物理を自然界のシステム同定とみなした．[@田中宏和2019 p.173]

## 本論

Metropolis scheme のように提案と棄却によって詳細釣り合い条件を満たすのではなく，棄却するところを衝突にすることによって詳細釣り合い条件を達成することを考える．

この状態から連続極限を考えていく．

まず，$U$ が階段関数であるとし，$q(x,y)$ が提案されたとすると，登った段数の分だけ独立な採択-棄却を実行することで，1回の採択-棄却の手続きを代用できる（ @Tartero-Krauth2023 の consensus 方式）．すなわち，最終的な採択確率は
$$
\begin{align*}
    P_{\text{no-coll}}(x,y)&=\prod_i1\land e^{-\beta\Delta U_i}\\
    &=\exp\paren{-\beta\sum_{i}(\Delta U_i)_+}
\end{align*}
$$

こうして，連続なポテンシャルを単関数近似して，同様の手続きを実行するアイデアが考えられるが，ここではより洗練された手法を考える．

ポテンシャルのステップ $\Delta U$ が $0$ に近づくという連続極限を取ることで，「どの時点まで衝突せずに直進できるか」を計算することに帰着する．例えば時刻 $[s,s_0]$ の間に衝突しない確率は
$$
P_{\text{no-coll}}(s)=\exp\paren{-\beta\int_s^{s_0}(D_t U(x(t)))_+dt}
$$
となる．

実際に，衝突する時刻を求めるには，採択-棄却手続きのための一様変数 $u\sim\rU([0,1])$ を取り，これに対して $u=P_{\text{no-coll}}(s)$ を満たす時刻 $s$ を計算すれば良いのである：
$$
-k_BT\log u=\int^s_{s_0}(D_tU(x(t)))_+dt.
$$

衝突のモデルが，例えば新しい速度 $v$ を「対称」に決めるようなものであったならば，この手法は対称な手法で詳細釣り合い条件を満たす．ここら辺も evnet-chain Monte Carlo [@Bernard+2009] に似ている．

## 多粒子系での実装

ポテンシャル $U=\sum_{\al\in\Lambda}U_\al$ を持つ多粒子系を考え，衝突規則とその実装の例を提示している．

このとき，粒子の速度 $v$ を何かしらの分布に従って refresh するとしているが，これは ECMC [@Bernard+2009] の名残だろう．

実際，Appendix にて，動力学の不変分布自体が Boltzmann-Gibbs 分布になっていることが示されており，refresh は必要ないことが注記されている．

また，ここで例示されているアルゴリズムは対称な MCMC を定めるとしているのも懸念点の１つである．

## 議論

３粒子以上が関与するポテンシャルに関しても自然に拡張でき，これが SEC [@Bernard+2009] にはない美点である．

MD よりも効率的であることは理論的には示していないが，実験的にはそう予想される．

> It remains to be seen if the application of the method is suited for niche applications only or if it can rival with MD and Metropolis-MC for general purpose molecular simulations.

