---
title: "総合研究大学院大学５年一貫博士課程のすすめ"
subtitle: "統計科学コース（統計数理研究所）"
author: "司馬博文"
date: 5/25/2024
date-modified: 6/13/2024
categories: [Opinion, Life]
image: Images/博士（統計科学）.svg
bibliography: 
    - ../../../assets/2023.bib
    - ../../../assets/2024.bib
csl: ../../../assets/apalike.csl
abstract-title: 概要
abstract: 統数研での五年一貫制博士課程（正確には，総合研究大学院大学統計科学コース）を紹介します．同期が居ないこと（がありえること）が最も人を選ぶ点でしょう．しかし，そのことが気にならない場合は，まさに理想郷のような研究環境が整っていると言えるでしょう．
---

<!--
{{< tweet sokenojou 1798237358514643257 >}}
-->

```{=html}
<div class="article-card-container">
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">総研大と鎌谷研の学生募集ですわ〜！ <a href="https://t.co/kv27wI4wtV">https://t.co/kv27wI4wtV</a></p>&mdash; 総合研究大学院大学お嬢様部 (@sokenojou) <a href="https://twitter.com/sokenojou/status/1798237358514643257?ref_src=twsrc%5Etfw">June 5, 2024</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
</div>
```

{{< include ../../../assets/_preamble.qmd >}}

::: {.callout-caution appearance="simple"}
筆者は **2023 年度入学** であり，その場合についてのみ述べます．

特に，本稿で紹介している 2023 年度の制度から変更がある可能性がありますから，本格的に進学を検討する場合は，記事中に適宜付しました「チェックすべきリンク集」のリンク先もご確認ください．
:::

::: {.callout-tip appearance="simple" title="チェックすべきリンク集"}
* [総研大の HP](https://www.soken.ac.jp/)
* [統計科学コースの HP](https://www.ism.ac.jp/senkou/)
* [総研大の学生便覧](https://www.soken.ac.jp/campuslife/handbook/)
:::

## 統数研での５年一貫博士課程

### 総合研究大学院大学について

統計数理研究所において研究教育を受けたい場合，大学院生としては 

::: {.callout-caution appearance="minimal"}

* 総合研究大学院大学
  * 先端学術院先端学術専攻
    * [統計科学コース](https://www.ism.ac.jp/senkou/)

:::

に所属することになります．

上位概念から解説して参ります．

1. [総合研究大学院大学（略して **総研大**）]{.underline}

    学部を持たない国立（大学院）大学です．^[なお，博士課程のみの国立大学院大学としては，日本初であるという（[Wikipedia](https://ja.wikipedia.org/wiki/%E7%B7%8F%E5%90%88%E7%A0%94%E7%A9%B6%E5%A4%A7%E5%AD%A6%E9%99%A2%E5%A4%A7%E5%AD%A6)）．] 1988 年の開学以来 35 年の歴史を持ちます．
2. [先端学術院先端学術専攻]{.underline}

    総合研究大学院大学はもともと複数の専攻に分かれてしましたが，１つの「先端学術院先端学術専攻」に統合され，20 個のコースに分かれている，という扱いになりました．受験者にとって大事なことには，このことにより定員に関する融通がより効くようになりました．このこともあり，統計科学コースは定員２名となっていますが，2024 年度のように**受験者数２名でも合格者が０名などの展開が十分に起こり得ます**．
3. [統計科学コース]{.underline}

    全 20 コースの一覧は [こちら](https://www.soken.ac.jp/prog/) からご覧になれます．それぞれのコースが **基盤機関** と呼ばれる研究所と対応しており，実際の教育研究はその研究所で行われます．^[総研大本部は葉山にキャンパスありますが，そこに通うことは，統合進化科学研究センターに対応する統合進化科学コースを除いてありません．] 統数研の他には，国立天文台，宇宙科学研究所（JAXA の一部），国立民俗学博物館，国立情報学研究所などが基盤機関としてあります．

### 学生数について

::: {.callout-caution collapse="true" title="定員について"}

５年一貫博士課程の定員は２名ですが，2021 年度から2023 年度は１名，2024 年度は０名でした．

一方で，３年次編入（通常の博士課程に相当）の定員が６名で，毎年ほとんど６名の方が入学されます．例年，そのうちの $2/3$ が社会人学生です．

:::

2024 年４月１日の学生総数は $34$ 名で，うち社会人が $24$ 名になります．大多数が社会人であることの影響で，社会人学生以外の学生を **フルタイム学生** と呼ぶ伝統があります．

社会人学生の方は基本的にリモートでの研究指導を受けることになりますから，研究所には半年に一回来れれば良い方だという方も多いです．

そのためフルタイム学生は同期の存在が期待できないだけでなく，そもそも研究所に来てもほとんど他の学生に会えないことも多いです．

### 教員陣について {#sec-teachers}

::: {.callout-tip appearance="simple" title="チェックすべきリンク集"}
* [統数研の教員と専門一覧](https://www.ism.ac.jp/ism_info_j/theme_j.html)
* [統数研の教員の主な教育内容](https://www.ism.ac.jp/senkou/subject/teacher.html)
* [総研大のシラバス](https://cplan-public.soken.ac.jp/public/web/Syllabus/WebSyllabusKensaku/UI/WSL_SyllabusKensaku.aspx)
:::

統数研には授業を開講している専任教員だけで 81 人います．

また上掲の [統数研の教員と専門一覧](https://www.ism.ac.jp/ism_info_j/theme_j.html) から分かる通り，凡そ統計に関連のある分野が理論・応用を分けずに網羅されており，それもスター研究者が揃っています．

統計は，応用をすれば大変多くの分野に応用されますし，理論的なアプローチも数学・物理・最適化など多様ですから，**普通の大学院ならば複数の研究科・専攻に散らばっているはずの教員陣が１つの研究所に揃っている** ことは，統計を学生として学ぶにあたって大変な恩恵になります．

例えば [統計数理セミナー](https://www.ism.ac.jp/meetings/seminar.html) はこのことを端的に感得する良い機会です．筆者も，統数研の教員陣の真の裾の広さを，ここで初めて実感することができました．

::: {.callout-caution collapse="true" title="統計数理セミナーについて"}

統数研では [統計数理セミナー](https://www.ism.ac.jp/meetings/seminar.html) と呼ばれる研究発表が毎週水曜日 16:00~17:20 （40 分のセッションが２回）に開催されており，全ての教員は毎年１回は発表することになっています．

統計数理セミナーは，学生が出席報告とレポート提出をすることで単位を取得することも出来る授業としても開講されています．そこで多くの分野の最新の研究に触れることになり，必ずや新たな発見があることでしょう．

特に，数学と数理統計の一部しか知らずに入学した筆者にとっては，実際の統計モデリングの研究（地震データ，天文データ，統数研が実施している [国民性調査](https://www.ism.ac.jp/kokuminsei/) のサーベイデータ），機械学習の理論研究，マテリアルズインフォマティクスへの応用などが，そこで出会った新しいトピックでした．

以上のトピックは思いつく順番に挙げたまでですが，多岐に渡る研究分野の存在と，その分野でのスターが揃っていることを，入学してしばらくしてようやく理解されてきました．

:::

### 授業について

統数研では教員が学生数の３倍近くいるため，授業は大変充実しています．しかしその分，多くの授業では教員と１対１になることが想定されます．

ですが，先生がメーリングリストで追加の参加者を呼びかけたり，学生側が他の学生を誘い合わせたりして，参加人数を増やして授業を盛り上げることもできます．

開講が珍しい授業ですと，教員陣も学生として参加していることも珍しくありません．

実際筆者も今まで７つの講義を取りましたが，まだ１対１の授業は経験していません．一方，受講者が２人だけということは３回ほど経験しています．

また，社会人学生が $2/3$ を占めている以上，リモートやハイブリッドでの開講や日程調整については極めて柔軟に対応されます．

筆者は統数研から遠い片道２時間弱の場所に住んでいるため，なるべく対面授業の日は１日にまとめたく，よく日程を調整していただいています．

### 金銭支援について {#sec-support}

::: {.callout-tip appearance="simple" title="チェックすべきリンク集"}
* [統数研のページ「奨学金等」](https://www.ism.ac.jp/senkou/life/scholarship.html)
* [総研大のページ「学費・各種経済支援」](https://www.soken.ac.jp/campuslife/tuition/)
:::

1. リサーチ・アシスタント

    ５年の間いつでも，申請をすることで RA としての雇用を希望することができます．月額約 10 万円の給与が７月から３月まで支給されます．１年ごとの更新です．^[収入の要件があります．例えば学振特別研究員はここに書いた意味での RA を利用できません．また，指導教員が別の予算を持っている場合は，その予算から追加で（二重に）雇用される場合もあります．]
2. [総研大特別研究員](https://www.soken.ac.jp/campuslife/tuition/sp_researcher_ch/)

    博士後期課程（５年一貫課程の３年次以降）では，特別研究員制度へ応募することができます．これは学振の特別研究員（DC1, DC2）に似た制度です．総研大の学生は学振のものと併せて２つの特別研究員制度が利用可能ということになります．

[授業料免除](https://www.soken.ac.jp/campuslife/tuition/exemption/) や [奨学金](https://www.soken.ac.jp/campuslife/tuition/jasso/) を除いて，統計科学コース独自のものは基本この２つです．

他にも，次の研究支援があります：

* 研究環境整備費

    初年度に 20 万円を上限に，PC やモニターなどの研究環境を整えるために，学生に予算が配分されます．

* [SOKENDAI 研究派遣プログラム](https://www.soken.ac.jp/education/dispatch/sokendai_studentdispatchprogram/)

    数日〜１年前後の多岐に渡る期間について，学生の海外での研究滞在にかかる費用を 100 万円を上限として援助してもらえるというプログラムです．^[国内での研究滞在にも同様の援助プログラムがあります．]

### 修士号について

五年一貫博士課程では，基本的には **博士（統計科学）** の学位のみが授与されます．^[場合によっては博士（学術）も授与されます．]

しかし特例として，２年以上在籍し，特定の要件を満たした場合は，中途退学と同時に修士の学位を得ることもできます．

詳しくは [@総合研究大学院大学学生便覧2023 p.5] をご参照ください．

### 図書室について {#sec-library}

統数研での研究環境について，筆者が最後に触れたいのは [図書室](https://www.ism.ac.jp/library/index_j.html) の存在です．

統数研の歴史は極めて長く，戦前の 1944 年に設立され，2004 年度までは文部省直轄の研究機関でした．

そのこともあってか，殊に統計と数学に関しては膨大な文献が揃っています．特に古典的な文献については，筆者は今のところ参照したい書籍が統数研図書室で見当たらなかったことはほとんどありません．

歴史的に貴重な文献が「文部省統計数理研究所」の印と共に２冊ほど所蔵されている，という経験が何度もあります．最新の書籍も和書ならば寄贈や，同研究所の先生方がすでに買っているかなどのことも多く，よく揃っています．

なお，電子リソース（論文や e-book）も，統計・数学関連のものは統数研内のネットワークからアクセスすることで殆どが閲覧できます．自宅にいても，`ssh` を通じた所内ネットワークへのリモートアクセスで随時論文などの電子リソースにアクセスすることができます．

## 学生生活について（私の場合）

以上が統数研で学生生活をするにあたっての基本的な情報です．

具体的なイメージが湧きましたでしょうか？

以降，統数研への進学を検討している方に向けて，わたしの主観的な見解も交えて，統数研での学生生活の美点と欠点について詳しい紹介をします．

### 結論

結論として，統数研での学生生活は [**学生が少ないという欠点を除けばこの上なく理想的な環境だ**]{.underline} と考えます．

その理由は次の通りです：

::: {.callout-important appearance="minimal"}

1. 図書室が充実していて，殆どの文献をすぐに参照することができる（第 [-@sec-library] 節）．
2. 計算機準備予算も付くので，大きなモニターと高性能な計算機で研究・勉強ができる（第 [-@sec-support] 節）．
3. 先生方との距離が近く，研究に関する相談もしやすい（第 [-@sec-teachers] 節）．
4. 事務の方との距離が近く，込み入った相談や提出物の忘れなども，時には先回りをして親切に対応していただける（第 [-@sec-life-support] 節）．
5. およそ統計に関連する分野のエキスパートが，単一の機関に揃っている（第 [-@sec-lectures] 節）．

:::

### 【注意喚起】同期が居ないことについて {#sec-warning}

まず最初に，最も重要な点を述べます．

**統数研での博士課程は，通常の大学院生活とは全く違うものになることは確かです**．

最大の違いは，[**研究室の同期・先輩が居ない代わりに，教員・事務の先生方との距離が近い**]{.underline}，ということです．^[現在，統数研では，複数名の学生がいる教員も５名ほど居ます．ですが，それでも同期は基本的におらず，先輩もすぐに卒業してしまったり，社会人であり殆ど連絡を取る機会がない，という場合が多いです．同期・先輩の存在を期待して進学するのは危険でしょう．]

最初から「大人」としての振る舞いが求められる，とでも言うべきでしょうか．

換言すれば，学生は研究所内では極めて少数派ですので，先生方も事務の方々も，学生が何で困っているのか，本当に想像がつかない場合が多いのです．さらに言えば，あなたが学生であることも言わなきゃわからないことが多いです．

ですから，少しでもわからないことや不安なことがあれば，先生方も事務の方にはっきりと「自分は学生である」ということと「こういうことで困っている」と言語化してコミュニケーションを自分から取りにいかないと，困った状況に陥りやすいです．このことが，最大の注意点でしょう．

例えば研究や資料準備などがうまく行っていなくて後ろめたい気持ちがあり，大人とのコミュニケーションを避けがちな精神状態であるときは尚更ですから，普通の大学院生活よりも「時すでに遅し」という状況に陥りやすいと言えるかも知れません．

この点から，「基本的には，特別な理由がない限り，５年一貫博士課程は勧めない」という立場の先生方も多いです．

「研究室内に溜まった暗黙のノウハウ」のようなものもありませんから，学振特別研究員の申請，奨学金・授業料免除などの諸々の申請，図書館カードを作ってもらう，研究費の使い方，発表用ポスターの作り方，スパコンの使い方，eduroam を使えるようにしてもらう（以降略）など，積極的に先生方と事務の方々に，時には，「すみません，一から何をすべきか分からないかもしれません」と「迷惑」をかけていく姿勢が必要になることもあるかもしれません．

その点，研究所外でのつながりも重要です．

::: {.callout-caution title="さらに踏み込んだアドバイス" collapse="true"}

「迷惑」と書きましたのは，実際は迷惑ではないからです．自分で調べて解決しようとしても，すでに共有された慣習やルールがあるかもしれませんから，自己流にやってミスる／手遅れになるよりかは，わからないことはわからないと聞くのが「正解」であり，想定されています．

自分からアクションを起こさなきゃいけないのは，５年一貫制博士課程の入学者が毎年０か１かですので，先生方も事務の方も本当に忘れている場合の方が多いです．

その意味で，学生はマイノリティですから，「自分は学生としてここにいる」という気持ちを強く持って，研究生活を歩むのが大事だと思います．

さらに言えば，マイノリティである学生の中でも社会人学生が大半を占めます．社会人学生の方の多くは大変にコミュニケーションがうまく，先生や事務の方と本音で話をしたり，うまく協力関係を構築したりすることが大変上手な方も多いです．

それゆえ，学部からストレートで統数研に来た場合，右往左往してしまうことが多くなるかもしれません．

しかし統数研は学生数が少ないため一人当たりのリソースが多く，社会人の方が共同研究を遂行するには最高の環境でしょう．学生のみなさんも，以上の理由からみすみすこの環境を逃すにはもったいないと考えます．

そこで，本記事を用意したのでした．

:::

### 学生生活の支援 {#sec-life-support}

先生方も事務の方も，困っている学生を助けたいと常に配慮してくださいますし，上述の通り，支援制度と研究環境は大変充実しています．

またとりわけ，大学院担当の事務の方々は，学生の背景もよく覚えていてくださり，申請書を書く際にいくつかわからない項目や揃わない書類があった際は親身になって相談に乗ってくださいます．

例えば，筆者のミスで出席連絡メールが数回不着であったときは「司馬くんのことだし出席してるよね？もしかして送信先ミスってない？」と気づいてくださったりもしました．

ですから，良い環境で研究したいと主体的に思える方は，ぜひ統数研の５年一貫博士課程を検討してみて欲しい，その気持ちで筆を取っております．

健康診断も職員と同一扱いであるため，めっちゃすごいところでの検診になります．学部の頃は移動式のバスとかだったのに（もちろんそれが劣るわけではないですが），健康診断専用の宿泊も可能な施設での検診です．すごい安心感．

### 研究室の様子

先ほど第 [-@sec-warning] 節で「同期がいない」と強調しました．５年一貫博士課程の場合は，通例あなたひとりになりますから，同期はいないと思って良いでしょう．

一方で，研究室には先輩がいる可能性があります．次に述べます通り，学生がいる研究室はいくつかの研究室に集中しているためです．

筆者の入学時，５年一貫博士課程生は筆者を入れて４名，３年次編入学生が33名でした．

::: {.callout-important icon="false" title="学生が３名以上居る研究室（2023 年度当時）"}

* [野間研究室](https://www.ism.ac.jp/senkou/subject/teacher.html#page_13) ５名
* [日野研究室](https://www.ism.ac.jp/senkou/subject/teacher.html#page_07) ５名
* [二宮研究室](https://www.ism.ac.jp/senkou/subject/teacher.html#page_28) ５名
* [藤澤研究室](https://www.ism.ac.jp/senkou/subject/teacher.html#page_30) ４名
* [持橋研究室](https://www.ism.ac.jp/senkou/subject/teacher.html#page_39) ４名

<!--
* 上野研究室 ２名
* 中野研究室 ２名
* 福水研究室 ２名
* 吉田研究室 １名
* 庄研究室 １名
* 松井研究室 １名
* 南研究室 １名
* 山下研究室 １名
* 金藤研究室 １名
* 志村研究室 １名
* 鎌谷研究室 １名
-->

:::

{{< tweet daiti_m 1801219144446320867 >}}

### 授業について {#sec-lectures}

::: {.callout-tip appearance="simple" title="チェックすべきリンク集"}
* [統数研ページ「担当教員・授業科目」](https://www.ism.ac.jp/senkou/subject/)
* [統数研ページ「終了要件」](https://www.ism.ac.jp/senkou/about/doctoral_thesis.html)
:::

５年一貫博士課程の卒業要件では，必修授業（研究指導）を除いて 20 単位の取得が必要です [@総合研究大学院大学学生便覧2023 p.22]．

私は修士の１年の間に（必修を除いて）12 単位を取得しましたので，あと４授業分を４年で消化すれば良いことになります．

12 単位を取ったと言っても，すべて「１年の間に取るべきだ」と考えた準必修の入門的なオムニバス講義でしたから，単位取得や成績の確保に追われるようなことはなく，自分の学びたいことをじっくり学べた１年でした．^[例えば，計 20 単位を５年で消化することにして，１学期に１授業ずつ取ることも，制度としては出来ます．]


::: {.callout-caution collapse="true" title="筆者が１年目にとった授業"}

統計科学コースには準必修と呼ぶべき「取らなきゃいけない授業」はありませんが，修士のうちに履修すべきとされる基本的な内容を扱う [**基礎科目**](https://www.ism.ac.jp/senkou/subject/subject1.html) と呼ばれる授業が全部で８つあります．

そのうち，次の３つを筆者は履修しました．

::: {.callout-note collapse="true" icon="false" title="多変量解析"}

疫学と医療統計の [野間先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_13) や，環境統計の [金藤先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_12)，調査の [前田先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_23) と [朴先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_21)，金融データの [山下先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_15)，差分プライバシーの [南先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_14) と，各分野で多変量解析を実際に使って研究なさっている先生方によるオムニバス講義です．

何よりも，各分野によって多変量解析への姿勢が少しずつ違い，教科書で読むだけでは無味乾燥であった多変量解析が極めて身近で手触りを感じました．

以下はシラバスの抜粋です．

> 下記の構成で授業を行う。（）内は主な担当教員である。

1. ガイダンス（多変量データ解析概観）（野間）
2. 多変量データの取得と合成変量モデルによる解析（前田）
3. 多変量の推測統計の初歩（多変量正規分布，多変量T2検定など）（金藤）
4. カテゴリカルデータの解析（分割表の解析）（野間）
5. 多変量データのための回帰分析・重回帰分析 (1)（南）
6. 多変量データのための回帰分析・重回帰分析 (2)（南）
7. 離散変数と定性データの分類・統計モデル (1) （山下）
8. 離散変数と定性データの分類・統計モデル (2)（山下）
9. 一般化線型モデル(1) 一般論，推測手法（金藤）
10. 一般化線形モデル(2) ロジスティック回帰，ポアソン回帰（野間）
11. 主成分分析と関連手法（朴）
12. 因子分析・共分散構造分析（朴）
13. 正準相関分析と数量化の方法（前田）
14. クラスター分析・MDS（前田）
15. まとめ・発展的話題（山下・南）

:::

::: {.callout-note collapse="true" icon="false" title="計算推論基礎"}

指導教員の [鎌谷先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_03) による MCMC の授業だけでなく，データ同化を研究する [中野先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_06) から粒子フィルターについて，統計物理学出身の [坂田先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_33) からグラフィカルモデルについて，自然言語処理のエキスパートである [持橋先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_39) からノンパラメトリックベイズについて学べた授業です．

どの内容に対しても先生方の背景がピッタリであることにお気づきでしょうか．

計算推論の手法は数理的に高度ですが，どの分野から生まれた手法で，どのような問題に適用されているかをセットで学ぶことで，稀有な直感が醸成されます．

指定の教科書を読むだけでは得られない肌感を得るのに最適な授業で，出席する前と後での理解度の差が歴然としていました．

以下はシラバスの抜粋です．

1. イントロダクション
2. 乱数の使い方：ブートストラップ法，モンテカルロ法
3. ＭＣＭＣ入門
4. ベイズ統計入門
5. 階層ベイズモデルとベイズ平滑化
6. 状態空間モデル，逐次ベイズ推定，粒子フィルタ
7. 粒子フィルタの応用と発展
8. グラフィカルモデルの基礎
9. 有向グラフと無向グラフ
10. 様々なグラフィカルモデル
11. 確率伝搬法とその周辺
12. 混合ガウス分布とK-means法
13. EMアルゴリズム
14. 変分ベイズEMアルゴリズムとその応用
15. Variational Autoencoder (VAE)とその応用

:::

::: {.callout-note collapse="true" icon="false" title="統計的機械学習基礎"}

日本のカーネル法・深層学習研究の第一線を走っていらっしゃる [福水先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_29) から直接深層学習について学べたことが大変印象深かったものでした．

それだけでなく，マテリアルズインフォマティクスで機械学習がどう活かされるかを [吉田先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_16) と [Wu 先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_19) 先生から学び，学習理論を [日野先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_07) から学び，Gauss 過程法を [松井先生](https://www.ism.ac.jp/senkou/subject/teacher.html#page_08) から学ぶことが出来る授業です．

以下はシラバスの抜粋です．

1. 総論（機械学習とは？　教師あり学習、教師無し学習、モデル選択）
2. カーネル法　（カーネル法の基礎と方法）
3. サポートベクターマシン I　（SVMの基礎）
4. サポートベクターマシン　II　（SVMの基礎と発展）
5. アンサンブル法（ランダムフォレスト、バギング、ブースティングなど）
6. 深層学習 I　（深層学習の基礎）
7. 深層学習 II 　（深層学習の発展）
8. ガウス過程I（ガウス過程の概念と基礎）
9. ガウス過程II（カウス過程の方法）
10. 様々な問題設定 I（転移学習、半教師付き学習）
11. 様々な問題設定II （強化学習）
12. 様々な問題設定III （能動学習、実験計画、応用的話題）
13. 統計的学習理論 I　（訓練誤差と汎化誤差の理論）
14. 統計的学習理論 II　（訓練誤差と汎化誤差の理論）
15. まとめ

:::

:::

また，統数研が毎年開催している公開講座も，学生ならば無料で参加ができます．

<!--

## 受験に当たって

### 定員

### 入試の基本情報

::: {.callout-tip appearance="simple" title="チェックすべきリンク集"}
* [統数研のページ](https://www.ism.ac.jp/senkou/admission/examination.html)
* [総研大のページ](https://www.soken.ac.jp/admission/application_info/stat/index.html)
:::

### 過去問と解答

a

-->

## 終わりに {.appendix}

ページ下部のコメントからもぜひお気軽にお問い合わせください．