---
title: "R によるベイズ推定入門"
subtitle: "brms を用いたベイズ階層モデリング入門"
author: "司馬 博文"
date: 5/12/2024
date-modified: 6/5/2024
categories: [MCMC, Stan, R]
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
abstract-title: 概要
abstract: brms
format:
  html:
    code-fold: false
execute:
  cache: true
---

{{< include ../../../_preamble.qmd >}}

::: {.callout-tip title="リンク集" appearance="simple"}

[r-project](https://cran.r-project.org/web/packages/brms/), [Documentation](https://paul-buerkner.github.io/brms/), [GitHub](https://github.com/paul-buerkner/brms), [discourse](https://discourse.mc-stan.org/), [@Burkner2017], [@Burkner2018], [@Burkner2021]

:::

```r
install.packages("brms")
```

^[R を最新バージョン 4.3.1 → 4.4.0 にアップデートしなければインストールに失敗したことに注意．]

## 使い方

::: {.callout-caution collapse="true" title="例"}

Documentation で紹介されている [例](https://paul-buerkner.github.io/brms/) を実行してみる：

```{r}
library(brms)
fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
            data = epilepsy, family = poisson())
```

```{r}
summary(fit1)
```

:::

## 実装

`brm` 関数（コードは [こちら](https://github.com/paul-buerkner/brms/blob/master/R/brm.R)）の実装を調べる．