---
title: "新時代の MCMC を迎えるために"
subtitle: "連続時間への進化"
author: 
    - name: "司馬 博文"
      orcid: 0009-0007-8251-1224
      affiliation:
        - name: 総合研究大学院大学先端学術院（統計科学コース）
          url: https://www.ism.ac.jp/senkou/
          group: ５年一貫博士課程
date: 5/24/2024
keywords:
    - マルコフ連鎖モンテカルロ法（MCMC）
    - 連続時間 MCMC
    - ハミルトニアンモンテカルロ法（HMC）
    - "区分的確定的マルコフ過程（PDMP: piecewise deterministic Markov process）"
categories: [MCMC, Simulation, Poster]
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
abstract-title: 概要
abstract: 物質科学を震源地とする MCMC のイノベーションが，統計力学と統計学の分野に波及して来ています．その結果，ここ 10 年で急激に MCMC 手法の革新が起こりました．従来 MCMC が離散時間ベースだったところが，イベントベースで連続時間ベースなものにとって替わられようとしているのです．
copyright: "Copyright Hirofumi Shiba 2024. All Rights Reserved"
---

{{< include ../../../_preamble.qmd >}}

[@Peters-deWith2012]

## MCMC の最先端はどうなっているか？

MCMC は物理学者から物質科学者，そして統計学者から機械学習家まで，多くの人が幅広く用いる手法です．

その結果，多くの同一の手法が違う名前で呼ばれていることも多く，現状の最先端ではどのようなことが起こっているのか見極めるのが困難です．

ここでは，上述のすべての分野に渡って共通して起こりつつある大きな地殻変動を紹介します．キーワードは **連続時間 MCMC** です．^[[@Fearnhead+2018-PDMC] から取った用語です．コンピュータシミュレーションである以上，結局は離散化するのですが，粒子の動きは（従来の Metropolis-Hastings 法のような）Markov 連鎖であるというより，連続時間確率過程のような動きをする手法群であることには間違いありません．]

### 筆者の目標：新時代のサンプラーの開発

情報通信機器の発達によりデータが複雑で大規模化する現代では，モデルも同様に大規模で複雑化していく必要があります．OpenAI の ChatGPT や Sora，Anthropic の Claude-3 などの **基盤モデル** はその象徴と言えるでしょう．

筆者は，その中で **新時代の MCMC** の開発を目標としています．

高次元空間上の複雑な分布からも効率的にサンプリングできる MCMC 手法が開発された際には，多くの人が自分のノートパソコンで気軽にできるベイズ統計分析の幅が大きく広がることでしょう．

それこそ，ニューラルネットワークの表現力をフルに活用するだけでなく，ベイズ手法の強みも併せて，小規模データでも鮮やかな分析が簡単に出来るようになるかもしれません．

そのような世界線こそ，AI 技術の民主化と呼ぶにふさわしい，来るべき未来だと筆者は信じています．

また，基盤モデルの Bayes 的な理解を進めることも，実は壮大ながらも，筆者の最終的な目標の一つであります．

### 最先端 MCMC 手法の世代交代が近い！？

現状，HMC (Hamiltonian Monte Carlo) [@Neal1996] というなんと約 30 年前の MCMC 手法が，Stan などの確率的プログラミング言語のデフォルト MCMC 手法として採用されています．

この手法はもともと "別の HMC" たる混合モンテカルロ (HMC: hybrid Monte Carlo) [@Duane+1987] が量子力学系のシミュレーションに特化した MCMC であったところを，一般の統計モデルに適用可能な形式に翻訳する形で提案されたものでした．

ということで，HMC は，オリジナルの MCMC がそうであったように，物理学の方から着想された効率的な MCMC 手法であったのです．

**HMC が，提案から 30 年目を迎える前に，更なる効率的な手法によって代替されようとしています**．

そのきっかけも，やはり，物理学（今回は物質科学）からの着想でした．

