---
title: "数学者のための確率的グラフィカルモデル２"
author: "司馬博文"
date: 1/19/2024
categories: [Computation, Math Notes]
toc: true
number-sections: true
code-block-bg: true
code-block-border-left: "#31BAE9"
code-overflow: wrap
code-fold: true
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
crossref:
    sec-prefix: 節
    eq-prefix: 式
    def-prefix: 定義
    def-title: 定義
    thm-prefix: 定理
    thm-title: 定理
    fig-prefix: 図
    fig-title: 図
abstract-title: 概要
abstract: 数学者のために，マルコフネットワークの古典的な例と，統計力学の考え方を概観する．
---

{{< include ../../../_preamble.qmd >}}

[@Li2009]

## 統計力学概観

### 興りと運動論的方法

統計力学は，マクロ観測量をミクロ情報のみから予測することを最大の目的とする．その成果の１つとして，マクロ観測量の揺らぎについても，より細かい分析を可能とする．^[[@Baxter1982 p.1] の他に，[@Friedli-Velenik2017 p.18] にも同様の記述がある．] 特に物理的過程を確率過程としてもモデリングする非平衡統計力学は，粗視化と確率化が対応していることを示唆する．^[[@戸田+2011 p.ix] 「物理的過程を確立的に捉えるとき，根元的なミクロのレベルから出発して，マクロのレベルに到達するには，ものの見方の粗さ (coarse graining) のさまざまな段階がある．それぞれの段階でインフォメーションが失われ，それに応じた確率化が行われる．」]

> The aim of statistical mechanics is to predict the relations between the observable macroscopic properties of the system, given only a knowledge of the microscopic forces between the components. [@Baxter1982 p.1]

[@Boltzmann1872] による方程式
$$
S=k\log W
$$
は Max Planck が 1900 年前後にまとめたものである．^[[@戸田+2011 p.vi], [Eric Weisstein's World of Physics](https://scienceworld.wolfram.com/physics/BoltzmannEquation.html)．これは方程式というよりは，エントロピー（左辺）の数学的定義と読むべきである [@Villani-Mouhot2015 p.6]．]

> 統計力学はこの１行から生まれたといってもよかろう． [@戸田+2011 p.vi]

これは希薄気体の熱力学を，ミクロの対象に関する密度関数の時間変化を記述することで基礎付けたもので，この接近を一般に **運動論的方法** (kinetic method) という．^[[@戸田+2011 p.vi]．「ミクロの対象」と言ったが，Maxwell がこの理論を展開した当時 [@Maxwell1867], [@Maxwell1878] は原子論もまだ仮説の一つに過ぎなかった [@Villani-Mouhot2015 p.3]．]

この手法がそのまま統計熱力学一般の基礎付けとはならず，その抽象的な枠組みは，後に [@Gibbs1902] によって与えられた．^[statisitcal ensemble の概念もこのときに導入された．[Wikipedia](https://en.wikipedia.org/wiki/Josiah_Willard_Gibbs#Career,_1880%E2%80%931903)]

なお，運動論的方法は，統計物理学の端緒であると同時に，現在でも十分に理解されているとは言い難く，機械学習などとも結びつきながら現在でも活発に研究が進められている分野である [@Villani2002]．

### 磁性体の物理

多くの物質は，外部磁場 $H>0$ を印加すると磁化する：$M(H)>0$．これを [常磁性体](https://ja.wikipedia.org/wiki/%E5%B8%B8%E7%A3%81%E6%80%A7) (paramagnetism) という．これは相互作用が無視できる要素から出来ているためと言える．そのため，**理想体系** とも呼ばれる．^[同様の例として Boyle-Charles の法則に従う気体も挙げられている [@戸田+2011 p.129]]

一方で鉄などの強磁性体では，外部磁場を印加したのち，これを取り除いても磁性が残り，これを [**自発磁化**](https://en.wikipedia.org/wiki/Spontaneous_magnetization) という：$M_0:=M(0)>0$． ^[[@Kittel2018 p.323], [@Baxter1982 p.1]．]

一方で，磁場を反転させたとき，逆向きに磁荷されるから，$M(-H)=-M(H)$ というべきである．すなわち，強磁性体は $H=0$ において相転移を起こす．^[[@Baxter1982 p.2]．「相転移を起こす系は一般に構成要素間に相互作用のある系であり，**協力系** とも呼ばれ，相転移は **協力現象** と言われることもある」 [@戸田+2011 p.129]．]

強磁性体には [@Weiss1907] が一定の理解を与え，これが理論が与えられた最初の秩序無秩序問題である．^[[@戸田+2011 p.viii]．] その後多くの模型が提案されているが，Ising 模型を初め，１次元の場合と２次元の特別な例のいくつかを除いて，相転移の厳密な理論は存在しない．^[[@戸田+2011 p.viii], [@Baxter1982 p.v]．]

しかし強磁性体も，一定の温度以上では自発磁化を失い，常磁性体と同じように振る舞う．すなわち，$M$ は $H=0$ でも連続になる．これを [**Curie温度**](https://ja.wikipedia.org/wiki/%E3%82%AD%E3%83%A5%E3%83%AA%E3%83%BC%E6%B8%A9%E5%BA%A6) といい，$T_C$ で表す．^[[@Kittel2018 p.323], [@Huebener2019 pp.176-177]．よく $T_C$ で表される．一方で反磁性体では **Néel温度** という．]

理論的には，$T=T_C$ の場合，$H=0$ では連続であるが傾きが発散して可微分ではないとする．

物体の磁化 $H$ を $T,H$ の２変数関数と見做した場合，線分 $[0,T_C]$ を除いた領域で $H$ は滑らかである，とも解釈できる．点 $(T_C,0)$ を [**臨界点**](https://ja.wikipedia.org/wiki/%E8%87%A8%E7%95%8C%E7%82%B9) (critical point) という．

$$
M_0(T)=\lim_{H\to 0+}M(H,T).
$$

### 磁化率

磁化率を
$$
\chi(H,T):=\pp{M(H,T)}{H}
$$
と定義する．変数変換 $t=\frac{T-T_C}{T_C}$ も用いる．すると臨界点は $(H,t)=(0,0)$ にある．

磁化率 $\chi$ は $(H,t)=(0,0)$ に非整数位数の極を持ち，その指数を [**臨界指数**](https://ja.wikipedia.org/wiki/%E8%87%A8%E7%95%8C%E6%8C%87%E6%95%B0) (critical exponents) という．

