---
title: "A Function that is Continuous on a Closed Subset"
author: "Hirofumi Shiba"
image: Images/Skilling-Hutchinson.svg
date: 4/17/2025
categories: [Topology]
bibliography: 
    - ../../../assets/2023.bib
    - ../../../assets/2024.bib
    - ../../../assets/2025.bib
csl: ../../../assets/apalike.csl
abstract-title: Japanese Abstract
abstract: 関数の連続点の集合は $G_\delta$ 集合になる．任意の $G_\delta$ 集合はある関数の連続点の集合になる．$\mathbb{R}$ 上の関数で，ちょうど $(-\infty,0]$ 上でのみ連続なものを構成する．
---

{{< include ../../../assets/_preamble.qmd >}}

For the sake of simplicity, we focus on the case of $f:\R\to\R$.

This article is concerned with the *continuity set* of $f$, defined as
$$
\Cont(f):=\Brace{x\in\R\mid f\text{ is continuous at }x}.
$$

Most continuous functions are treated on open sets. We might be easily tricked to think that $\Cont(f)$ should be open.

Is this conjecture true?^[It is not true.] As a starting point, proving that $\Cont(f)$ is a countable intersection of open sets is not difficult.

## $\Cont(f)$ is $G_\delta$

We denote an open ball of radius $\delta$ centered at $x$ by $U_\delta(x)$.

::: {.callout-tip title="Proposition" icon="false"}

$\Cont(f)$ is a $G_\delta$ set, meaning that it is a countable intersection of open sets. Specifically,
$$
\Cont(f)=\bigcap_{n=1}^\infty\Brace{x\in\R\,\middle|\,\exists_{\delta>0}\;\forall_{y,z\in U_\delta(x)}\;\abs{f(y)-f(z)}<\frac{1}{n}}.
$$
:::

::: {.callout-note title="Proof" icon="false" collapse="true"}

It is straightforward to check that each $\Brace{x\in\R\,\middle|\,\exists_{\delta>0}\;\forall_{y,z\in U_\delta(x)}\;\abs{f(y)-f(z)}<\frac{1}{n}}$ is open.

The easy part is the $\supset$ direction, since for every $\ep>0$, there exists a $N>0$ satisfying $\frac{1}{N}<\ep$.

$\subset$ direction is also straightforward, following from the definition of continuity and triangle inequality.

:::

## $G_\delta$ sets are continuity sets

A fun fact is that every $G_\delta$ set is the continuity set $\Cont(f)$ of some function $f$, proved in, for example, a almost one-page article [@Kim1999].

::: {.callout-tip title="[Theorem p.258 @Kim1999]" icon="false"}

Let $X$ be a nonempty metric space without isolated points. Then every $G_\delta$ subset $G\subset X$ is the continuity set of some function $f:X\to\R$.

:::

::: {.callout-note title="Proof" icon="false" collapse="true"}

:::

## Example of $f:\R\to\R$ with closed $\Cont(f)$

In perfectly regular spaces, every closed set is a $G_\delta$ set [@Tong1952].

So there should be an example on $\R$ that $\Cont(f)$ is closed.

::: {.callout-caution title="Example^[My colleague Nakajima-san taught me this example.]" icon="false"}

The function $f$ defined as follows has $\Cont(f)=\ocinterval{-\infty,0}$:
$$
f(x):=\begin{cases}
0,&x\le0,\\
\frac{1}{n},&x\in(0,\infty)\cap\bQ,\\
-\frac{1}{n},&x\in(0,\infty)\setminus\bQ.
\end{cases}
$$

:::