---
pagetitle: Hirofumi Shiba
format:
    html:
        toc: true
        number-sections: false
        default-image-extension: svg
        include-in-header: 
            - text: |
                <style>
                h1, h2, h3, p, li, .small-letter {
                    font-family: "Gill Sans", sans-serif !important;
                    font-weight: 400;
                    font-style: normal;
                }
                p, li {
                    font-size: 110%;
                }
                </style>
    pdf: 
        toc: false
        number-sections: false
        urlcolor: minty
        template-partials: 
            - before-title.tex
        keep-tex: true
        mainfont: TeX Gyre Pagella
        block-headings: false
        default-image-extension: svg
        latex-tinytex: true
        pdf-engine: lualatex
        fontsize: 11pt
        fontenc: T1
        fontfamily: kpfonts  # https://tug.org/FontCatalogue/kpsansserif/
        shift-heading-level-by: -1
format-links: [pdf]
comments: false
---

::: {layout="[50,50]" layout-valign="bottom"}

::: {#first-column}
# \Huge Hirofumi Shiba {.large-letter}
:::

::: {#second-column .artificial-align}

\color{minty}

\hfill [{{< fa home >}}]{.color-minty} [https://162348.github.io/](https://162348.github.io/){.small-letter}\par<br>
\hfill [{{< fa envelope >}}]{.color-minty} [shiba.hirofumi@ism.ac.jp](mailto:shiba.hirofumi@ism.ac.jp){.small-letter}\par

::: {.content-visible when-format="html"}

[{{< fa file-pdf >}}]{.color-minty} [View in PDF](https://162348.github.io/static/CV/cv.pdf){.small-letter}

:::

\color{gray}\hfill [Last Update: 3/8/2025]{.small-letter}

:::

:::

\vspace{-1em}

## Academic History

::: {.content-visible when-format="pdf"}
\renewcommand{\labelitemi}{\textcolor{minty}{\faGraduationCap}}
:::

* **Ph.D. in Statistical Science**. _Graduate University for Advanced Studies, SOKENDAI, Tokyo, Japan_. \hfill [2023.4 -- 2028.3]{.cvdate}

    Superivsor: [Kengo Kamatani](https://sites.google.com/view/kengokamatani/home)

* **B.A. in Mathematics**. _The University of Tokyo, Japan_. \hfill [2019.4 -- 2023.3]{.cvdate}

    Supervisor: [Nakahiro Yoshida](https://www.ms.u-tokyo.ac.jp/~nakahiro/hp-naka-e)

## Research Interests

Monte Carlo methods, Diffusion Models, Bayesian Neural Networks, Bayesian Statistical Modelling, especially in Political Science & Biostatistics

## Work Experience

::: {.content-visible when-format="pdf"}
\renewcommand{\labelitemi}{\textcolor{minty}{\faUniversity}}
:::

* **Consultant**. _PreMedica, Inc., Tokyo, Japan_. \hfill [2024.9 -- today]{.cvdate}

    Provided Bayesian data analysis solutions for clients in the healthcare industry.

* **Research Assistant**. _The Institute of Statistical Mathematics, Tokyo, Japan_. \hfill [2023.7 -- 2025.3]{.cvdate}

    Contributed to the R package `YUIMA`, an open-source project aiming to simulate and infer multidimensional stochastic differential equations, with an emphasis on Bayesian inference.

* **Cooperative Researcher**. _RCAST, the University of Tokyo, Japan_. \hfill [2023.4 -- today]{.cvdate}

    Research on trustworthy AI and machine learning from the viewpoint of economic security.

* **Data Scientist**. _IMIS Co., Ltd_. \hfill [2022.8 -- 2024.1]{.cvdate}

    Provided statistical analysis and machine learning solutions for clients in the manufacturing industry.


## Research Visit

::: {.content-visible when-format="pdf"}
\renewcommand{\labelitemi}{\textcolor{minty}{\faUniversity}}
:::

* Department of Statistical Science, **University College London**, United Kingdom. \hfill [2024.11.4 -- 2024.12.2]{.cvdate}

  Supervisor: Alexandros Beskos

* Department of Statistics & Data Science, **National University of Singapore**. \hfill [2025.6.1 -- 2025.6.30]{.cvdate}

  Supervisor: Alexandre Thiéry

* Institute of Stochastics, **Ulm University**, Germany. \hfill [2025.7.13 -- 2025.7.26]{.cvdate}

  Supervisor: Evgeny Spodarev

::: {.content-visible when-format="pdf"}
\renewcommand{\labelitemi}{\textcolor{minty}{\faBookmark}}
:::

## Awards

* **Best Poster Award**, 19th Spring Meeting of the Japan Statistical Society. \hfill [2025.3.8]{.cvdate}
* **Director's Award** from the Japan Statistical Society Certificate. \hfill [2025.3.8]{.cvdate}