---
pagetitle: 司馬博文（しばひろふみ）
format:
    html:
        toc: true
        number-sections: false
        default-image-extension: svg
        # include-in-header: 
        #     - text: |
        #         <style>
        #         h1, h2, h3, p, li, .small-letter {
        #             font-family: "Gill Sans", sans-serif !important;
        #             font-weight: 400;
        #             font-style: normal;
        #         }
        #         p, li {
        #             font-size: 110%;
        #         }
        #         </style>
    pdf: 
        toc: false
        number-sections: false
        template-partials: 
          - before-title.tex
        keep-tex: true
        pdf-engine: lualatex
        fontenc: T1
        fontfamily: kpfonts  # https://tug.org/FontCatalogue/kpsansserif/
        fontfamilyoptions: sfmath
        linkcolor: minty
        filecolor: minty
        urlcolor: minty
        citecolor: minty
        block-headings: false
        default-image-extension: svg
        latex-tinytex: true
        documentclass: article
        fontsize: 11pt
        shift-heading-level-by: -1
format-links: [pdf]
comments: false
---

::: {layout="[50,50]" layout-valign="bottom"}

::: {#first-column}
# \Huge 司馬博文（しばひろふみ） {.large-letter}
:::

::: {#second-column .artificial-align}

\color{minty}

\hfill [{{< fa home >}}]{.color-minty} [https://162348.github.io/](https://162348.github.io/){.small-letter}\par<br>
\hfill [{{< fa envelope >}}]{.color-minty} [shiba.hirofumi@ism.ac.jp](mailto:shiba.hirofumi@ism.ac.jp){.small-letter}\par

::: {.content-visible when-format="html"}

[{{< fa file-pdf >}}]{.color-minty} [PDF でみる](https://162348.github.io/static/CV/cv_Japanese.pdf){.small-letter}

:::

:::

:::

\vspace{-1em}

## 経歴

::: {.content-visible when-format="pdf"}
\renewcommand{\labelitemi}{\textcolor{minty}{\faGraduationCap}}
:::

* **博士（統計科学）**. _総合研究大学院大学先端学術院統計科学コース_. \hfill [2023.4 -- 2028.3]{.cvdate}

    指導教員：[鎌谷研吾教授](https://sites.google.com/view/kengokamatani/home)

* **学士（理学）**. _東京大学理学部数学科_. \hfill [2019.4 -- 2023.3]{.cvdate}

    指導教員：[吉田朋広教授](https://www.ms.u-tokyo.ac.jp/~nakahiro/hp-naka-e)

<!-- 総合研究大学院大学（統計科学コース）５年一貫博士課程２年目．

1999年生まれ，男，日本国籍．

日本語，中国語が母語で，英語も話せる（TOEFL iBT 100点）．Python, R でのコーディング経験３年以上，Julia １年以上． -->

## 研究分野

* モンテカルロ計算

    MCMC，SMC，PDMC などのシミュレーション技術．

* 統計モデリング
  
    政治学・疫学・惑星地球科学などへの応用．

* ベイズ機械学習
  
    ニューラルネットワーク・カーネル法・ノンパラメトリクス．

## 職歴

::: {.content-visible when-format="pdf"}
\renewcommand{\labelitemi}{\textcolor{minty}{\faUniversity}}
:::

* **リサーチ・アシスタント**. _統計数理研究所_. \hfill [2023.7 -- 現在]{.cvdate}

    確率過程の統計推測のための R パッケージである [YUIMA](https://r-forge.r-project.org/projects/yuima/) の開発などを通じ，モンテカルロ法とベイズ統計の応用に取り組む．

* **連携研究員**. _東京大学先端科学技術研究センター_. \hfill [2023.4 -- 現在]{.cvdate}

    信頼できる AI と機械学習の視点からの経済安全保障の研究．

* **データサイエンティスト**. _IMIS 研究所_. \hfill [2022.8 -- 2024.1]{.cvdate}

    製造業のクライアントに対して統計分析と機械学習のソリューションを提供．

## 研究滞在

* **ユニバーシティ・カレッジ・ロンドン**，イギリス．\hfill [2024.11.4 -- 2024.12.2]{.cvdate}

  受入教員：Alexandros Beskos 教授

* **シンガポール国立大学**，シンガポール．\hfill [2025.6.1 -- 2025.6.30]{.cvdate}

  受入教員：Alexandre Thiéry 准教授

* **ウルム大学**，ドイツ．\hfill [2025.7.13 -- 2025.7.26]{.cvdate}

  受入教員：Evgeny Spodarev 教授

::: {.content-visible when-format="pdf"}
\renewcommand{\labelitemi}{\textcolor{minty}{\faBookmark}}
:::

## 受賞

* 優秀発表賞 第19回日本統計学会春季集会\hfill [2025.3.8]{.cvdate}