---
title: "特異値分解"
author: "司馬博文"
date: "8/12/2024"
image: Images/SVD.svg
categories: [Functional Analysis]
bibliography: 
    - ../../../assets/mathematics.bib
    - ../../../assets/bib.bib
    - ../../../assets/bib1.bib
csl: ../../../assets/apalike.csl
abstract-title: 概要
abstract: 行列の特異値分解とは，正方行列の直交対角化を一般の行列に拡張したものである．特異値を大きいものから $r$ 個選ぶことで，Hilbert-Schmidt ノルムの意味で最適な $r$-階数近似が構成できる．このことは主成分分析に応用を持つ．
listing: 
    -   id: related-articles-listing
        type: grid
        sort: false
        contents:
            - "../Kernels/HierarchicalModel.qmd"
            - "../Kernels/Manifold.qmd"
            - "../Kernels/Kernel.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
---

{{< include ../../../assets/_preamble.qmd >}}

## 特異値分解

::: {.callout-tip title="命題（特異値分解）^[[@Eckart-Young1936 p.213 Theorem 1], [@Strang16 p.372] など．]" icon="false"}

任意の行列 $A\in M_{n,p}(\R),r:=\rank(A)$ について，直交行列 $U\in O_n(\R),V\in O_p(\R)$ と非負実数 $\sigma_1\ge\cdots\ge\sigma_r>0$ が存在して，次が成り立つ：
$$
A=U\Sigma V^\top,\qquad\Sigma:=\begin{bmatrix}D&O_{r,p-r}\\O_{n-r,r}&O_{n-r,p-r}\end{bmatrix},\quad D:=\diag(\sigma_1,\cdots,\sigma_r).
$$
$D$ を **特異値行列**，の対角要素を **特異値** と呼ぶ．^[[@Eckart-Young1936 p.214] によると，以前はにより正準乗数 (canonical multipliers) と呼ばれていた．]

:::

[@Sylvester1889] は特異値を正準乗数 (canonical multipliers) と呼んでいた．Sylvester は特異値分解を独立に再発見した一人で，歴史上最初の特異値分解は [@Beltrami1873] が与えたものだとされている．より詳しい歴史については [@Stewart1993] 参照．

::: {.callout-note title="証明" icon="false" collapse="true"}

1. まず $v_1,\cdots,v_r\in\R^n$ を，$A^\top A$ の固有ベクトルからなる正規直交系として取る．
    このとき $v_1,\cdots,v_r$ は $\Im(A^\top)$ の像の基底である．
    $v_1,\cdots,v_r$ が $A^\top A$ の固有ベクトルであることが必要であることは，
    $$
    A^\top A=(U\Sigma V^\top)^\top(U\Sigma V^\top)=V\Sigma^\top U^\top U\Sigma V^\top=V(\Sigma^\top\Sigma)V
    $$
    となることからわかり，$\sigma_1^2,\cdots,\sigma_r^2$ が $A^\top A$ の固有値である．
    （従って $AA^\top$ の固有値でもある）．
2. 続いて，条件 $Av_i=\sigma_iu_i\;(i\in[r])$ によって，$u_1,\cdots,u_r$ を定める．するとこれらは直交し，
    $\Im(A)$ の基底をなす．さらに，$AA^\top$ の固有ベクトルでもある．
    
    このことは次のように示せる：
    
    \begin{align*}
    u_i^\top u_j&=\paren{\frac{Av_i}{\sigma_i}}^\top\paren{\frac{Av_j}{\sigma_j}}=\frac{v_i^\top A^\top Av_j}{\sigma_i\sigma_j}=\frac{\sigma_j^2}{\sigma_i\sigma_j}v_i^\top v_j=0,\qquad i\ne j.
    \end{align*}

    $\brac{u_1,\cdots,u_r}\subset\Im(A)$ であることと，正規直交することから線型独立でもあり，これらが $\Im(A)$ の基底であることがわかる．
    さらに，任意の $i\in[r]$ について，
    $$
    AA^\top u_i=\frac{AA^\top Au_i}{\sigma_i}=\sigma_iAv_i=\sigma_i^2u_i,\qquad i\in[r].
    $$
    なお，$Av_i=\sigma_iu_i$ が必要であることは，$v_1,\cdots,v_r$ の正規直交性から，
    $$
    Av_i=\Paren{u_1\sigma_1v_1^\top+\cdots+u_r\sigma_rv_r^\top}v_i=u_i\sigma_i
    $$
    からわかる．

3. $v_1,\cdots,v_r$ の正規直交な延長であって，$v_{r+1},\cdots,v_n$ が $\Ker(A)$ の基底になるもの，$u_1,\cdots,u_r$ の正規直交な延長であって，$u_{r+1},\cdots,u_m$ が $\Ker(A^\top)$ の基底になるものが取れる．
    これは，核と余像，像と余核が直交するためである．
    これについて，$A=U\Sigma V^\top$ が成り立つ．

:::



::: {.callout-warning title="系" icon="false"}

以上の証明から，次のこともわかる：

1. $A$ の特異値は，$A^\top A$ の固有値の正の平方根に等しい．
2. $V$ の列ベクトルは $A^\top A$ の固有ベクトルであり，$U$ の列ベクトルは $AA^\top$ の固有ベクトルになる．

:::

## 低階数近似

$(n,p)$-行列の全体 $M_{n,p}(\bC)$ は [Hilbert-Schmidt 内積](../../../static/Notations.qmd#subsec-linear-space)
$$
(B \mi A)_\HS:=\Tr(A^*B)=\sum_{i=1}^m\sum_{j=1}^na_{ij}b_{ij}
$$
に関して Hilbert 空間をなす．$M_{n,p}(\R)$ はこの閉部分空間をなす．

::: {.callout-tip title="命題 [@Eckart-Young1936]" icon="false"}

$A\in M_{n,p}(\R)$ を行列，$0\le r\le n\lor p$ を自然数とする．ランク $r$ の行列 $\wt{A}\in M_{n,p}(\R)$ のうち，$A$ に最も近いものは
$$
\wt{A}:=U\Sigma_{1:r}V^\top=\argmin_{\rank(\wt{A})=r}\norm{A-\wt{A}}_\HS
$$
が与える．ただし，$\Sigma_{1:r}=\diag(\sigma_1,\cdots,\sigma_r,0,\cdots,0)$ とした．

:::

またこのときの残差は，残った特異値のうち最大のもの
$$
\norm{A-\wt{A}}_\HS=\sigma_{r+1}
$$
が与える．^[$r\ge\rank(A)$ であるとき，$\sigma_{r+1}=0$ とする．[@Strang16 p.394] も参照．]

## 一般化逆行列

::: {.callout-tip title="命題 [@Moore1920]-[@Penrose1955]^[[@柳井-竹内-一般逆行列] も参照．]" icon="false"}

$A\in M_{mn}(\R)$ について，次の３条件を満たす行列 $A^+\in M_{nm}(\R)$ は一意的に定まる：

a. 反射型一般可逆行列：$AA^+A=A,A^+AA^+=A^+$
b. 最小ノルム型：$A^+A$ は自己共役である：$(A^+A)^\top=A^+A$
c. 最小誤差型：$AA^+$ も自己共役である：$(AA^+)^\top=AA^+$

これを **Moore-Penrose の一般化逆行列** という．

:::

任意の行列 $A\in M_{n,p}(\R)$ の一般化逆行列は，直交行列 $V,U$ で座標変換を施したところで逆行列を取り，これを再び $V,U$ で変換し直したものに等しい：

::: {.callout-tip title="命題（一般化逆の特徴付け）^[[@柳井-竹内-一般逆行列 定理5.6], [@Strang16 p.395] も参照．]" icon="false"}

$A\in M_{n,p}(\R)$ の一般化逆行列は次のように表せる：
$$
A^+=V\Sigma^{-1}U^\top,\qquad \Sigma^{-1}=\begin{bmatrix}D^{-1}&O_{r,p-r}\\O_{n-r,r}&O_{n-r,p-r}\end{bmatrix}.
$$

:::

## 関連ページ {.unnumbered .unlisted .appendix}

::: {#related-articles-listing}
:::