---
title: "Hamiltonian Monte Carlo on Stiefel Manifolds"
subtitle: "Riemannian Metric Selection as a Preconditioner"
author: "Hirofumi Shiba"
date: 7/26/2026
categories: [HMC, Geometry]
# image: Images/Cochran.svg
bibliography: 
    - ../../../assets/2023.bib
    - ../../../assets/2024.bib
    - ../../../assets/2025.bib
    - ../../../assets/2026.bib
csl: ../../../assets/apalike.csl
jupyter: julia-1.12
code-fold: false
---

{{< include ../../../assets/_preamble.qmd >}}

## Stiefel Manifolds

Stiefel manifolds $\operatorname{St}_p(\mathbb{R}^n)$ is the set of all orthonormal $p$-frames in $\R^n$, or equivalently, the set of all $n\times p$ matrices with orthonormal columns.\footnote{[@Milnor-Stasheff1974 p.56] defines the Stiefel manifold as the set of all $p$-frames, not necessarily orthonormal, in $\R^n$.} Formally, we define
To make our presentation concrete, we focus on the minimal nontrivial case
$$
\operatorname{St}(3,2):=\{X\in\R^{3\times2}\mid X^\top X=I_2​\}.
$$
We immediately see $\operatorname{St}(3,2)\simeq\operatorname{SO}(3)$, as
$$
\operatorname{St}(3,2)\ni(x_1,x_2)\mapsto(x_1,x_2,x_1\times x_2)\in\operatorname{SO}(3),
$$
$$
\operatorname{SO}(3)\ni(x_1,x_2,x_3)\mapsto(x_1,x_2)\in\operatorname{St}(3,2),
$$
are diffeomorphisms between the two manifolds. They are 3-dimensional manifolds.

### Tangent Space

Notice $\operatorname{St}(3,2)=F^{-1}(0)$ for a analytic function
$$
F(R)=R^\top R-I_2.
$$
For this function, the derivative is
$$
DF_R(\Delta)=R^\top\Delta+\Delta^\top R.
$$
We see the tangent space can be expressed as
$$
T_R(\operatorname{St}(3,2))=\{\Delta\in\R^{3\times2}\mid R^\top\Delta+\Delta^\top R=0\}.
$$

### Application in Control

Geodesics in $\operatorname{SO}(3)$ is used to model dynamics of a rigid body.