---
title: "Pierre Del Moral 著作まとめ"
author: "Hirofumi Shiba"
date: "11/10/2023"
categories: [Index]
abstract-title: 概要
abstract: 英語で書かれた著作と論文を一覧にしたページ
toc: true
number-sections: true
---

[HP](https://people.bordeaux.inria.fr/pierre.delmoral/publications-books.html)も参照．

## Feynman-Kac模型についての本

### Del Moral and Penev (2014) Stochastic Processes

### [Del Moral (2013) Mean Field Simulation for Monte Carlo Integration](https://162348.github.io/posts/2023-11-9/)

### [Del Moral (2004) Feynman-Kac Formulae](https://162348.github.io/posts/2023-11-8/)

### Del Moral and Miclo (2000) in Seminaire de Probabilites XXXIV

Del Moral and Miclo (2000) [Branching and interacting particle systems approximations of feynman-kac formulae with applications to non-linear filtering](https://link.springer.com/chapter/10.1007/BFb0103798)

## Feynman-Kac模型についてのレビュー

### Del Moral+ (2012) On the Concentration Properties of Interacting Particle Processes

Del Moral, P., Hu, P. and Wu, L. (2012) [On the Concentration Properties of Interacting Particle Processes](https://www.nowpublishers.com/article/Details/MAL-026). *Foundations and Trends in Machine Learning*, 3(3-4): 255-389.

[INRIA](https://inria.hal.science/file/index/docid/607965/filename/RR-7677.pdf)にもpdfあり．

## その他レビュー

### ランダム行列理論： Bishop, Del Moral, and Angele (2018) An Introduction to Wishart Matrix Moments

Bishop, A., Del Moral, P. and Angele, N. (2018) An Introduction to Wishart Matrix Moments. *Foundations and Trends in Machine Learning*, 11(2): 97-218.