---
title: "法律家のための統計数理（2）第1章第2-4節"
author: "Hirofumi Shiba"
date: "12/6/2023"
categories: [草野数理法務]
toc: true
toc-expand: true
number-sections: true
cover: img.jpg
twitter-card: true
bibliography: ../../mathematics.bib
csl: ../../apa.csl
abstract-title: 概要
abstract: 教科書第1章第2-4節(pp.1-14)までの内容を
---

{{< include ../../_preamble.qmd >}}

## 今回の内容

第一審の裁判において，事実認定が中心的な問題である．この際に起き得る誤謬を，ベイズの方法を用いてどう回避できるか？という例が３つ挙げられている．

### 主観確率の基本的な計算方法と捜査官の誤謬

::: {.callout-tip icon="false" title="問題1-1"}
殺人事件の加害者はAとBのどちらか？利用可能な情報は次のみ：被疑者のA, Bは同居しており，そのうちどちらかが加害者であることはわかっているものとする．

1. 台所に左利きの包丁があった．Aが左利きである確率はいくらか？ただし，人間が左利きである確率は1割とする．
2. Aは左利きであること，被害者の外傷の部位や凶器の形状から加害者も左利きであったことは確定的であるとする．Aに逮捕令状を出しても良いだろうか？ただし，利き手の情報を除けば，AかBかは完全に五分五分であるとする．なお，共犯はなく，どちらか一方の単独犯であることも確実であるとする．
:::

::: {.callout-caution icon="false" title="結論"}
1. AもBも左利きである可能性があるため，5割より少し大きい．
2. AもBも左利きである可能性があるため，9割強である．95%を一つの基準にするなら，逮捕令状は出すべきではない．
:::

この問題のポイントは「条件付き確率」への理解である．

::: {.callout-note icon="false" title="証明"}
1. 事象を
$$
A:=\Brace{\text{Aは左利きである}}
$$
$$
B:=\Brace{\text{Bは左利きである}}
$$
と定めると，
$$
\P[A\cup B]=\P[A]+\P[B]-\P[A\cap B]=\frac{19}{100}.
$$
これより，[条件付き確率の公式](../2023-11-22/%E6%B3%95%E5%BE%8B%E5%AE%B6%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E7%B5%B1%E8%A8%88%E6%95%B0%E7%90%861.qmd#sec-conditional-probability)から
$$
\P[A|A\cup B]=\frac{\P[A]}{\P[A\cup B]}=\frac{10}{19}\approx52.6\%
$$
:::

今回の肝は，事象 $A,B,C$ を互いに独立に設定したために，各積事象 $A\cap B,B\cap C,C\cap A$ が悉く計算可能なものとして得られた，という点である．これを計算しておけば，欲しい値がこれらの言葉で得られているから，答えまで一本道で辿り着ける，という訳である．

::: {.callout-tip icon="false" title="Monty Hall問題"}

:::

### ベイズの公式と検察官の誤謬

::: {.callout-tip icon="false" title="問題1-2"}
ドーピング検査の結果から，ある日本選手Iが金メダルを剥奪された．弁護人としては，どのような弁護の筋があるか？

1. 本ドーピング検査において，禁止薬物をを用いていない人に対して陽性の結果が出る（偽陽性）確率は1%で，逆の偽陰性も1%である．
2. 日本選手で，禁止薬物を用いている割合は0.1%とする．当該日本選手Iもこの割合に従うものとする（とりわけ禁止薬物を使っていそうな理由・いそうでない理由はないものとする）．
:::

各事象を
$$
A:=\Brace{\text{ I は薬物を使用していた}}
$$
$$
E:=\Brace{\text{ I に陽性反応が出た}}
$$
と設定する．今回は $A,E$ は独立ではないので，Venn図の方法は使えない．例えば確率 $\P[A\cap E]$ などはどうやっても計算できない．ここで，条件付き確率の計算の問題に分け入ることになる．今回与えられている条件はそれぞれ，

$$\text{(1)}\qquad\P[\ov{E}|A]=\frac{1}{100},\quad\P[E|\ov{A}]=\frac{1}{100}$$
$$\text{(2)}\qquad\P[A]=\frac{1}{1000}$$

と表現できており，知りたい値は，今現在Iが本当に薬を使っていたという確率 $\P[A|E]$ である．**これは全く大きな値ではない！**これは，そもそも薬物を使っている人が少なく，健常な人の方が大多数であるために，検査で陽性が出たからといってそれが本当に薬物を使っている人から出た「真の陽性」である確率が極めて小さくなってしまうという普遍的な現象である．

::: {.callout-note icon="false" title="証明"}

:::

## ベイズ統計学

