---
title: "確率測度のカップリング"
author: "司馬 博文"
date: 3/25/2024
categories: [Process]
toc: true
number-sections: true
code-block-bg: true
code-block-border-left: "#5AB5BA"
code-overflow: wrap
code-fold: true
bibliography: 
    - ../../../assets/mathematics.bib
    - ../../../assets/bib.bib
csl: ../../../assets/apalike.csl
crossref:
    sec-prefix: 節
    eq-prefix: 式
    def-prefix: 定義
    def-title: 定義
    thm-prefix: 定理
    thm-title: 定理
    fig-prefix: 図
    fig-title: 図
abstract-title: 概要
abstract: Markov 過程のエルゴード性の証明は，カップリングの概念を用いれば極めて明瞭に見渡せる．
---

{{< include ../../../assets/_preamble.qmd >}}

カップリングによる一様エルゴード性の証明は [@Griffeath1975b]，エルゴード性の証明は [@Kulik-Scheutzow2015]，指数エルゴード性は [@Hairer-Mattingly2011] による．

エルゴード定理自体は古くから示されているが，カップリングによる証明は極めて見通しがよく，もはや極めて自然で直感的に理解できる段階にまで達しているものと思われる．

このような感覚は，高度に洗練された数学的概念には，よく見られるものであるようである：

>グロタンディークの業績を振り返ってきたが、それが、その後の代数幾何、数論幾何にもたらしたものは、あまりに巨大である。簡単に紹介した、ドリーニュ、マンフォード、クィレン、ファルティングス、ラフォルグの業績は、どれもフィールズ賞の栄誉をうけた。
> こうしてみると、リーマン・ロッホの定理や、エタール・コホモロジーのレフシェッツ跡公式といった大定理が、輝きを放っている。しかし、それよりも強く感じられることは、これらの定理の証明を追い求めたというよりは、理論を構築するうちに、こうした定理が自然に得られるような枠組みを作り上げたという印象である。これは、ドリーニュによるヴェイユ予想の証明や、ワイルズによるフェルマー予想の解決からうける印象とは、異質である。[@斎藤毅2010]

## 導入

### 歴史

カップリングを最初に導入し，同時に最初のカップリング不等式を導いたのは Lévy の下で博士号を取得した年に発表された [@Doeblin1938 pp.78-80] である．^[[@Butkovsky-Veretennikov2013] などに言及あり．] Doeblin はその２年後に 25 歳で戦死する．^[自殺と言われているらしい．[Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%B4%E3%82%A9%E3%83%AB%E3%83%95%E3%82%AC%E3%83%B3%E3%82%B0%E3%83%BB%E3%83%87%E3%83%BC%E3%83%96%E3%83%AA%E3%83%BC%E3%83%B3) 参照．]

その後，[@Doob1953], [@Harris1955], [@Vaserstein1969], [@Griffeath1975b], [@Pitman1976], [@Nummelin1984] などによって発展するが，Markov 連鎖のエルゴード性の解析に体系的に用いられるようになったのは極めて最近である．^[[@Kulik2018] や [@Lindvall1992] 参照．[@Harris1955] は engagement と呼んでいる．]

[@Breiman1969] や [@Hoel+1986] などの初等的な教科書は，離散状態空間上の Markov 連鎖のエルゴード性の証明にカップリングを用いていたという．1970 年代の相関粒子系の研究の高まりと同時にカップリング手法が広く使われるようになり，「カップリング」の用語が生まれたのもこの時期であるという．^[[@Lindvall1992] によると，確固たる記録はないが，coupling の語を造語したのは [Frank Spitzer](https://en.wikipedia.org/wiki/Frank_Spitzer) だという共通了解があるという．]

最終的にカップリングが成功する確率が最大になるようなカップリングが存在し，[@Pitman1976], [@Griffeath1975a] は **maximal coupling** と呼ぶが，これは必ず Markov 連鎖にならないことがわかっている．この２つの論文が，カップリングの重要性の周知に大きく貢献したという．^[[@Lindvall1992] のエピローグ参照．Griffeath の指導教官は Frank Spitzer であり，カップリングの用語も受け継いでいた．Pitman は [@Breiman1969] から着想を得たといい，カップリングの語も用いていない．[@Lindvall1992] も [@Pitman1976] に大きな影響を受けたという．]

一方で，[@Vaserstein1969] が考えたような「各段階でカップリング確率が最大になる」ようなカップリングは Markov 連鎖になり，これを **最適 Markov カップリング** または [@Kulik2018 p.33] は **greedy coupling** などと呼ぶ．

[@Nummelin1984], [@Lindvall1992] などが発展させた手法は **generalized regeneration** というもので，エルゴード性の分析とは少し方向が違う．

### 定義

### 概要

カップリングにより，$\cP(E)$ 上の２つの力学系 $\{(P^*)^n\mu\}_{n\in\N},\{(P^*)^n\nu\}_{n\in\N}$ の距離を比べることが可能になる．

$\mu$ を不変確率分布にとれば，$\{(P^*)^n\mu\}_{n\in\N}$ はその上でもはや動かない１点からなる力学系になるため，その場合はエルゴード速度に関する示唆を得られる．

一般の場合は，$\cP(E)$ はデルタ測度を極点に持つ凸集合であるから，$\mu=\delta_x,\nu=\delta_y$ という場合を取れば良い．その際は，「スタート地点を忘れる速度」という意味で，Markov 連鎖の忘却速度を特徴付けることができる．