---
title: "Langevin Dynamics の多項式エルゴード性"
subtitle: "Ergodic Lower Bounds"
author: "司馬博文"
date: 7/5/2024
date-modified: 7/12/2024
image: Images/ExtendedGenerator.svg
format:
    html:
        toc: true
    # typst: 
    #     margin:
    #         x: 1.5em
    #         y: 1.5em
    #     mainfont: "UDEV Gothic NF"
    pdf: 
        toc: false
        number-sections: true
        urlcolor: minty
        citecolor: minty
        linkcolor: minty
        filecolor: minty
        toccolor: minty
        template-partials: 
            - ../../../assets/before-title.tex
        keep-tex: true
        block-headings: false
        pdf-engine: lualatex
        documentclass: article
        latex-tinytex: true
        fontenc: T1
        fontfamily: kpfonts  # https://tug.org/FontCatalogue/kpsansserif/
        fontfamilyoptions: sfmath
        shift-heading-level-by: -1
# format-links: [pdf, typst]
categories: [Process]
bibliography: 
    - ../../../assets/mathematics.bib
    - ../../../assets/bib.bib
csl: ../../../assets/apalike.csl
abstract: 目標分布の裾が重ければ重いほど，Langevin 拡散過程の収束は遅くなる．本記事ではその様子を，平衡分布との全変動距離について，定量的に評価する．
---

{{< include ../../../_preamble.qmd >}}

$\R^n$ 上の Langevin 拡散を考える：
$$
dX_t=-\nabla V(X_t)\,dt+\sqrt{2\beta^{-1}}\,dB_t,\qquad X_0=x.
$$ {#eq-Langevin}
ただし，
$$
V(x)=O(\abs{x}^{2k})\qquad(\abs{x}\to\infty)
$$
の仮定をおく．$k\ge1/2$ の場合，指数エルゴード的であるが，$k<1/2$ の場合はそうではない．

$k\in(0,1/2)$ の設定で，次の ergodic lower bound を示したい：
$$
C_1\exp\paren{c_1V(x)-c_2t^{\frac{k}{1-k}}}\le\norm{P_t(x,-)-\mu_*}_\TV
$$ {#eq-ergodic-lower-bound}
$$
\mu_*(dx)\propt e^{-\beta V(x)}dx
$$
この lower bound から，$k\in(0,1/2)$ の場合，Langevin 過程 $X$ が指数エルゴード的たり得ないことが従う．

式 ([-@eq-ergodic-lower-bound]) を示すためには，$G(x):=e^{\kappa V(x)}\;(\kappa\in\R)$ に対して，
$$
\E_x[G(X_t)]\le g(x,t)
$$
を満たす関数 $g$ を見つける必要がある [@Hairer2021-Convergence pp.34-35]．

これは次の３ステップを辿る

1. そもそも $\E_x[G(X_t)]<\infty$ であることの証明（第 [-@sec-integrability] 節）．
2. $G$ に関するドリフト条件 $P_t\wh{L}G\le C\varphi\circ G$ から，$\E_x[G(X_t)]$ の $t$ に関する微分不等式を導く（第 [-@sec-extended-generator] 節）．
3. 微分不等式から，Gronwall の補題より，結論を得る（第 [-@sec-Gronwall] 節）．

## $G=e^{\kappa V}$ の可積分性について {#sec-integrability}

::: {.callout-tip appearance="simple" icon="false"}

次元 $n=1$ で考えてみる．

$V(x)=\frac{x^2}{2}$ とした場合，$X$ は OU 過程になり，

$$
\E_x[G(X_t)]<\infty\quad\Leftrightarrow\quad t<-\frac{1}{2}\log\paren{1-\frac{\beta}{\kappa}}.
$$

$V(x)=\log x$ とした場合，$X$ は Bessel 過程になり，
$$
\E_x[G(X_t)]<\infty\qquad(\forall_{t>0}).
$$

$k\in(0,1/2)$ の場合，$\nabla V$ が有界であることに注目すれば，Bessel 過程の場合と同様に
$$
\E_x[G(X_t)]<\infty\qquad(\forall_{t>0}).
$$

:::

### 導入

Markov 過程 $X$ に関するドリフト条件
$$
\wh{L}V\le-C\varphi\circ V\qquad\on\R^n\setminus K
$$
からは $V:E\to\R_+$ の可積分性が出る：
$$
\E_x[V(X_t)]<\infty\qquad t\ge0.
$$

::: {.callout-note title="証明" icon="false" collapse="true"}

上のドリフト条件を，[@Hairer2021-Convergence] の最も弱い意味で解釈すると
$$
M_t:=V(X_t)+C\int^t_0\varphi\circ V(X_s)\,ds
$$
が任意の $x\in E$ に関して $\P_x$-局所優マルチンゲールである，ということになる．

これだけの仮定でも，$V$ が下に有界であるために $M_t$ も下に有界であり，下に有界な局所優マルチンゲールは（真の）優マルチンゲールであることから，
$$
\E_x\Square{V(X_t)+C\int^t_0\varphi\circ V(X_s)\,ds}\le V(x).
$$

加えて左辺が下に有界であることから，$\E_x[V(X_t)]<\infty$ でないと矛盾が起こる．

:::

しかし，lower bound を得たい場合，
$$
\wh{L}V\le C\varphi\circ G\qquad\on\R^n
$$ {#eq-drift-condition}
という情報のみから，
$$
\E_x[G(X_t)]\le g(x,t)\;(<\infty)
$$
という評価を得る必要が出てくる．この場合，$\E_x[G(X_t)]<\infty$ は非自明で，ケースバイケースの議論がである．

### OU 過程の場合

An overdamped Langevin dynamics on $\R$ is defined as the solution to the following SDE:
$$
dX_t=-\nabla V(X_t)\,dt+\sqrt{2\beta^{-1}}\,dB_t,\qquad X_0=x_0.
$$

If $V(x)=\frac{x^2}{2}$, $X$ becomes an Ornstein-Uhlenbeck process. Transforming via $f(t,x)=xe^t$ and using Itô's formula, we get
$$
X_t=x_0e^{-t}+\sqrt{2\beta^{-1}}\int^t_0e^{-(t-s)}\,dB_s.
$$
Hence, $X$ is a Gaussian process with $X_t\sim\rN\paren{x_0e^{-t},\beta^{-1}(1-e^{-2t})}$.

In this case, expectation with respect to $G(y)=e^{\kappa V(y)}=e^{\frac{\kappa y^2}{2}}\;(\kappa\in\R)$ is given by

\begin{align*}
    \E_x[G(X_t)]&=\int_{\R} G(y)\frac{1}{\sqrt{2\pi\beta^{-1}(1-e^{-2t})}}\exp\paren{-\frac{(y-xe^{-t})^2}{2\beta^{-1}(1-e^{-2t})}}\,dy\\
    &=\frac{1}{\sqrt{2\pi\beta^{-1}(1-e^{-2t})}}\int_{\R}\exp\paren{\frac{\kappa\beta^{-1}(1-e^{-2t})y^2-(y-xe^{-t})^2}{2\beta^{-1}(1-e^{-2t})}}\,dy.
\end{align*}


Taking a closer look at the numerator inside $\exp$,

\begin{align*}
    &\qquad\kappa\beta^{-1}(1-e^{-2t})y^2-(y-xe^{-t})^2\\
    &=y^2\Paren{\kappa\beta^{-1}(1-e^{-2t})-1}-2xe^{-t}y+x^2e^{-2t}.
\end{align*}


Therefore, we conclude
$$
\E_x[G(X_t)]<\infty\quad\Leftrightarrow\quad\kappa\beta^{-1}(1-e^{-2t})<1.
$$
In other words, $P_tG(x)$ is finite as long as
$$
t<-\frac{1}{2}\log\paren{1-\frac{\beta}{\kappa}}.
$$

### Bessel 過程の場合

$V=a\log x$ ととると，$V'(x)=\frac{a}{x}$ であるから，これに関する Langevin 動力学は，$\beta=1$ のとき，
$$
dX_t=-\frac{a}{X_t}\,dt+dB_t
$$
と，母数 $a$ を持つ Bessel 過程になる．ただし，$0$ への到着時刻 $T_0$ で止めたもの $X^{T_0}$ を考える．

::: {.callout-tip title="[@Lawler2019 p.10 命題2.5]" icon="false"}

母数 $a$ を持つ Bessel 過程 $X^{T_0}$ の密度を $q_t(x,y;a)$ で表す．このとき，
$$
q_t(x,y;1-a)=\paren{\frac{y}{x}}^{1-2a}q_t(x,y;a)
$$
$$
q_t(x,y;a)=q_t(y,x;a)\paren{\frac{y}{x}}^{2a}
$$
$$
q_{r^2t}(rx,ry;a)=\frac{1}{r}q_t(x,y;a)
$$

加えて $a\ge\frac{1}{2}$ でもあるとき，
$$
q_1(x,y;a)=y^{2a}\exp\paren{-\frac{x^2+y^2}{2}}h_a(xy),
$$
$$
h_a(x)\sim\frac{1}{\sqrt{2\pi}}x^{-a}e^x\qquad(\abs{x}\to\infty)
$$

:::

この結果は [@Lawler2019 p.59] をみる限り，修正 Bessel 関数と，Bessel 過程の Fokker-Planck 方程式との考察によって証明されている．

$$
G(y)=e^{\kappa V(y)}=e^{a\kappa\log(y)}=y^{a\kappa}
$$
であるから，密度 $q_t(x,y;a)$ に対してはどうやっても可積分である．

### $k<1/2$ の場合の尾部確率

$k<1/2$ で最も大きく変わる点は，
$$
\nabla V(x)=O(\abs{x}^{2k-1})\qquad(\abs{x}\to\infty)
$$
であるために，$\nabla V$ が $\R^n$ 上で有界になることである．

このため，一般に SDE
$$
dZ_t=b(Z_t)\,dt+\sigma(X_t)\,dB_t
$$
の密度が，任意の $T>0$ に対して，ある $A_T,a_T>a$ と $y\in\R$ が存在して
$$
\frac{1}{A_T\sqrt{2\pi t}}e^{-\frac{a_T\abs{y-x}^2}{2t}}\le p_t(x,y)\le\frac{A_T}{\sqrt{2\pi t}}e^{-\frac{\abs{y-x}^2}{2a_Tt}}
$$
$$
t\in\ocinterval{0,T}
$$
が成り立つことが使える．^[[@Kohatsu-Higa2022] で最初に知った．特に [@Kohatsu-Higa2003] は詳しく扱っており，上からの評価は Malliavin 解析から得られる [@Taniguchi1985]．同様にして熱方程式の基本解としても捉えられるが．]

これによれば，
$$
G(x)=e^{\kappa V(x)}=O(e^{\kappa\abs{x}^{2k}})\quad(\abs{x}\to\infty)
$$
に対して $p_t$ の尾部が勝つため，$P_tG(x)<\infty$ である．

### $k<1/2$ の場合の $G$ の可積分性

$k<1/2$ の場合，式 ([-@eq-Langevin]) のドリフト係数が有界になる．このことから，$G$ の可積分性が，$X_t$ の密度の考察に依らず次のように導ける．

$$
M:=\max_{x\in\R^n}\nabla V(x)
$$
と定める．$V(x)=O(\abs{x}^{2k})\;(\abs{x}\to\infty)$ より，ある $C>0$ が存在して，
$$
V(x)\le C\abs{x}^{2k}\qquad\on\R^n.
$$
\begin{align*}
    \abs{X_t}&\le\int^t_0\abs{\nabla V(X_t)}\,dt+\sqrt{2\beta^{-1}}\abs{B_t}\\
    &\le Mt+\sqrt{2\beta^{-1}}\abs{B_t}
\end{align*}
より，
\begin{align*}
    \E_x[\abs{G(X_t)}]&\le\E_x\Square{e^{\kappa V(\abs{X_t})}}\\
    &\le\E_x\Square{\exp\Paren{\kappa V(M_t+\sqrt{2\beta^{-1}\abs{B_t}})}}\\
    &\le e^{\kappa\abs{Mt}^{2k}}\E_x\Square{e^{\kappa 2^k\beta^{-k}\abs{B_t}^{2k}}}<\infty.
\end{align*}

## 微分と拡張生成作用素の関係 {#sec-extended-generator}

<!-- ::: {.callout-tip appearance="simple" icon="false"}

次の連続性は？

$$
t\mapsto\E_x\SQuare{1_{[0,\tau_n]}(t)\wh{L}G(X_t)}.
$$
これさえ言えれば，$\pp{}{t}P_tG=P_t(\wh{L}G)$ を得る．

::: -->

$(X_t)$ を $E=\R^n$ 上の Feller-Dynkin 過程，$(P_t)$ をその遷移半群，$\wh{L}$ をその拡張生成作用素とする．

::: {.callout-tip title="命題 [-@sec-extended-generator]" icon="false"}

$G\in\cD(\wh{L})$ とする．すなわち，
$$
t\mapsto M_t:=G(X_t)-\int^t_0\wh{L}G(X_s)ds
$$
は任意の $x\in E$ について $\P_x$-局所マルチンゲールである．

このとき，さらに $G$ について次の条件を仮定する：

1. $\E_x[\abs{G(X_t)}]<\infty\;(x\in E,t\in\R_+)$．すなわち，$P_tG:E\to\R$ が定まる．
2. 同様に $\E_x[\abs{\wh{L}(G)(X_t)}]<\infty\;(x\in E,t\in\R_+)$．すなわち，$\wh{L}P_tG:E\to\R$ も定まる．^[元々はある正の定数 $C>0$ が存在して，$\wh{L}G\le CG$．ある凹関数 $\varphi$ について $\wh{L}G\le\varphi\circ G$ が成り立つならばこの仮定は満たされることに注意，としていた．]
3. $t\mapsto P_t\wh{L}G(x)$ は局所有界．

このとき，$P_tG(x)$ は $t$ で微分可能であり，次が導ける：
$$
\pp{}{t}\E_x[G(X_t)]=\E_x[\wh{L}G(X_t)].
$$

:::

これは，通常の意味での生成作用素 $L$ の性質
$$
\pp{}{t}P_tG=P_t(LG)
$$
が，可積分性の条件の下で，拡張生成作用素 $\wh{L}$ にも引き継がれると理解できる．

::: {.callout-note title="証明" icon="false"}

<!-- 局所マルチンゲール性の仮定から，還元する停止時の列 $\{\tau_n'\}$ が存在する：$\tau_n'\nearrow\infty\;\as$ かつ $M^{\tau_n'}$ はマルチンゲール．

これに対して，
$$
\tau_n:=\inf\Brace{t\ge0\mid\abs{G(X_t)}\ge n}\land\tau_n'
$$
と定めると，これもやはり還元する停止時の列である．特に， -->

仮定より，停止時の列 $\tau_n\nearrow\infty\;\as$ が存在し，任意の $n\in\N$ について，$M^{\tau_n}$ はマルチンゲールで，
$$
\E_x\Square{G(X_{t\land\tau_n})-\int^{t\land\tau_n}_0\wh{L}G(X_s)ds}=G(x),\qquad  t\ge0,x\in E.
$$ {#eq-1}

[仮定１]{.blue-letter}より $\E_x[\abs{G(X_{t\land\tau_n})}]<\infty$ であるから，
$$
\E_x\Square{\Abs{\int^{t\land\tau_n}_0\wh{L}G(X_s)ds}}<\infty.
$$
でもある．従って Fubini-Tonelli の定理から
$$
\E_x\Square{\Abs{\int^{t\land\tau_n}_0\wh{L}G(X_s)ds}}=\int^t_0\E_x\SQuare{1_{[0,\tau_n]}(s)\wh{L}G(X_s)}\,ds
$$
と書き換えられる．

よって，式 ([-@eq-1]) は
$$
\E_x\SQuare{G(X_{t\land\tau_n})}=G(x)+\int^{t}_0\E_x\SQuare{1_{[0,\tau_n]}(s)\wh{L}G(X_s)}\,ds
$$
とも表せる．右辺が $t$ について微分可能であるから，左辺も微分可能である：
$$
\pp{}{t}\E_x\SQuare{G(X_{t\land\tau_n})}=\E_x\SQuare{1_{[0,\tau_n]}(t)\wh{L}G(X_t)}.
$$
<!-- 
$$
\Om\times(0,\infty)\ni(\om,t)\mapsto\int^{t\land\tau_n}_0\wh{L}G(X_s)ds
$$
が任意の $t\in(0,\infty)$ について

1. $\P_x$ について可積分で，
2. 変数 $t$ に関する偏微分係数も $\P_x$ について可積分

であるから，右辺は $t$ で微分可能であり，さらに $\E_x$ と $\pp{}{t}$ とが交換できる：
$$
\pp{}{t}\E_x\SQuare{G(X_{t\land\tau_n})}=\E_x\SQuare{\pp{}{t}\int^{t\land\tau_n}_0\wh{L}G(X_s)ds}=\E_x\SQuare{1_{[0,\tau_n]}(t)\wh{L}G(X_t)},\qquad n\in\N,x\in E,t\in(0,\infty).
$$
これより，左辺の $\E_x[G(X_{t\land\tau_n})]$ も $t\in(0,\infty)$ に関して微分可能だったことがわかる． -->

両辺の $n\to\infty$ に関する極限を取ると，右辺は $\abs{\wh{L}G(X_t)}$ が $\P_x$-可積分であるから（[仮定２]{.blue-letter}），Lebesgue の優収束定理より，
$$
\lim_{n\to\infty}\pp{}{t}\E_x[G(X_{t\land\tau_n})]=\lim_{n\to\infty}\E_x\SQuare{1_{[0,\tau_n]}(t)\wh{L}G(X_t)}=\E_x[\wh{L}G(X_t)],\qquad x\in E,t\in(0,\infty).
$$

加えてこの収束は，$t\in(0,\infty)$ に関して広義一様に起こる．実際，Hölder の不等式より，^[$\sup_{t\in[0,T]}\wh{L}G(X_t)$ は可積分とは限らないため，$\sup$ を期待値の中に入れることはできない．Hölder の不等式により，これを迂回できる．]
\begin{align*}
&\qquad\sup_{t\in[0,T]}\Abs{\pp{}{t}\E_x[G(X_{t\land\tau_n})]-\E_x[\wh{L}G(X_t)]}\\
&=\sup_{t\in[0,T]}\ABs{\E_x[1_{[0,\tau_n]}(t)\wh{L}G(X_t)]-\E_x[\wh{L}G(X_t)]}\\
&=\sup_{t\in[0,T]}\ABs{\E_x\SQuare{(1-1_{[0,\tau_n]}(t))\wh{L}G(X_t)}}\\
&\le\sup_{t\in[0,T]}\E_x\SQuare{(1-1_{[0,\tau_n]}(T))\abs{\wh{L}G(X_t)}}\\
&\le\norm{1-1_{[0,\tau_n]}(T)}_{L^\infty(\Om)}\sup_{t\in[0,T]}\E_x\Square{\abs{\wh{L}G(X_t)}}\xrightarrow{n\to\infty}0.
\end{align*}
最後の不等式にて，[仮定３]{.blue-letter}による局所有界性
$$
\sup_{t\in[0,T]}\E_x\Square{\abs{\wh{L}G(X_t)}}<\infty
$$
を用いた．


この導関数の一様収束と，Lebesgue の優収束定理による各点収束
$$
\E_x[G(X_{t\land\tau_n})]\xrightarrow{n\to\infty}\E_x[G(X_t)]
$$
を併せると，$\E_x[G(X_t)]$ も可微分で，その導関数は極限
$$
\pp{}{t}\E_x[G(X_t)]=\lim_{n\to\infty}\pp{}{t}\E_x[G(X_{t\land\tau_n})]=\E_x[\wh{L}G(X_t)]
$$
として得られることが結論づけられる．

:::

::: {.callout-tip title="[@Rudin-Principles p.152 定理7.17]^[[@杉浦光夫1980 p.311] 定理13.7系では，$f_n$ に $C^1$-級の仮定を置いて，この場合は $f$ が $C^1$-級になることを導いている．]" icon="false"}

$f_n:[a,b]\to\R$ を可微分な関数列とし，ある関数 $f:[a,b]\to\R$ に各点収束するものとする．

仮に，導関数列 $\{f'_n\}$ が一様位相に関して Cauchy 列ならば，$f_n\to f$ も一様収束し，加えて $f$ も可微分で，
$$
\lim_{n\to\infty}f'_n(x)=f'(x)
$$
が成り立つ．

:::

## 下界の導出 {#sec-Gronwall}

元来の目的である下界の導出のためには，
$$
\E_x[G(X_t)]\le CG(x)\exp\paren{ct^{\frac{k}{1-k}}}
$$
という評価を得る必要がある．Gronwall の不等式を用いれば，導関数に関する不等式
$$
\pp{}{t}\E_x[G(X_t)]\le\E_x[\wh{L}G(X_t)]\le C\E_x[\varphi\circ G(X_t)]
$$
があれば十分である．この導関数に関する不等式は，命題 [-@sec-extended-generator] とドリフト条件 ([-@eq-drift-condition])
$$
\wh{L}G\le C\varphi\circ G
$$
を併せることで，
$$
\pp{}{t}\E_x[G(X_t)]=\E_x[\wh{L}G(X_t)]\le C\E_x[\varphi\circ G(X_t)]
$$
より得る．

## 参考文献