---
title: "Lévy 過程に駆動される SDE のエルゴード性"
subtitle: "カップリング法／最適輸送距離による証明"
author: "司馬 博文"
date: 10/14/2024
date-modified: 10/14/2024
categories: [Process]
image: Images/LevyExtendedGenerator.svg
bibliography: 
    - ../../../assets/mathematics.bib
    - ../../../assets/bib.bib
    - ../../../assets/bib1.bib
csl: ../../../assets/apalike.csl
abstract-title: 概要
abstract: Lévy 過程は独立定常増分な Feller-Dynkin 過程のことである．このクラスの過程は，Brown 運動と純粋跳躍過程の独立和として表現される．これが Lévy-Ito 分解であるが，純粋跳躍過程の全てが複合 Poisson 過程かといえばそうではない．Gamma 過程は任意の区間上で無限回跳躍するが，有界変動である（B 型の Lévy 過程）．Cauchy 過程は有界変動ではなく，跳躍部分は発散するが，無限に強いドリフトによってこれを打ち消している（C 型の Lévy 過程）．これらの過程を例とし，YUIMA パッケージを通じてシミュレーションを行いながら，Lévy の特性量 $(A,\nu,\gamma)$ の変化が，Lévy 過程の見本道にどのような変化をもたらすかの直感的理解を試みる．
listing: 
    -   id: yuima-listing
        type: grid
        sort: false
        contents:
            - "Levy.qmd"
            - "Poisson.qmd"
            - "PureJump.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
    -   id: lst-embedding1
        type: grid
        sort: false
        grid-columns: 1
        grid-item-align: center
        contents:
            - "Langevin.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
---

## 関連記事 {.unnumbered .unlisted}

::: {#yuima-listing}
:::

{{< include ../../../assets/_preamble.qmd >}}

## はじめに

本稿では Lévy 過程 $\{Z_t\}$ に駆動された SDE
$$
dX_t=a(X_t)\,dt+b(X_{t-})\,dZ_t=a(X_t)\,dt+\sigma(X_t)\,dW_t+\int_{\Brace{\abs{u}\le1}}c(X_{t-},u)\,\wt{N}(dtdu)+\int_{\Brace{\abs{u}>1}}c(X_{t-},u)\,N(dtdu)
$$ {#eq-SDE-Levy}
で駆動される確率過程 $\{X_t\}$ のエルゴード性を議論する．

Lévy 過程 $\{Z_t\}\subset\L(\Om;\R^m)$ は拡散項を持たない $\sigma\equiv0$ とし，跳躍係数 $c:\R^m\times\R^m\to M_m(\R)$ も跳躍幅 $u$ に関して線型 $c(x,u)=b(x)u$ で，次の Ito-Lévy 分解を持つとする：
$$
Z_t=\int^t_0\int_{\abs{u}\le1}u\wt{N}(ds,du)+\int^t_0\int_{\abs{u}>1}uN(ds,du),
$$
$$
N(ds,du):=ds\,\nu(du),\qquad\wt{N}(ds,du):=N(ds,du)-ds\,\nu(du),\qquad\int_{\R^m}\abs{u}^2\land1\nu(du)<\infty.
$$
ただし $N$ を強度測度 $ds\,\nu(du)$ を持つ跳躍を表す Poisson 点過程とした．

Borel 可測関数 $b:\R^m\to M_{m}(\R)$ と $a:\R^m\to\R^m$ は局所 Lipschitz 連続で，線型増大条件
$$
\abs{a(x)}^2+\int_{\abs{u}\le1}\abs{b(x)u}^2\nu(du)\le K(1+\abs{x}^2),\qquad x\in\R^m,
$$
を満たすとする．このとき，SDE ([-@eq-SDE-Levy]) には一意な強解 $\{X_t\}$ が存在し，$X$ は càdlàg な Markov 過程である．^[[@Ikeda-Watanabe1981 p.245] 定理9.1．]

加えて，$b$ が有界であるという条件も引き続き課すこととする．

伊藤の公式より，拡張生成作用素
$$
\wh{L}f(x):=\paren{Df(x)\,|\,a(x)}+\int_{\R^m}\Paren{f\Paren{x+b(x)u}-f(x)-1_{B^m}\Paren{(Df(x)|b(x)u)}}\nu(du),\qquad f\in C^2(\R^m),
$$ {#eq-Levy-SDE-generator}
に関して $M_t^f:=f(X_t)-f(x)-\int^t_0\wh{L}f(X_s)ds$ で定まる càdlàg 過程 $\{M^f_t\}$ は任意の $x\in\R^m$ に関して局所 $\P_x$-マルチンゲールである．

拡散過程，例えば Langevin 動力学のエルゴード性証明

::: {#lst-embedding1}
:::

との最大の違いは，ドリフト関数 $V\in C^2(\R^m)$ に Lévy 測度 $\nu$ に関する可積分条件が加わることにある．そもそも $\wh{L}V$ が well-defined であるためには，式 ([-@eq-Levy-SDE-generator]) の積分が発散してはならないのである．

このように $\wh{L}f(x)$ の値が $f$ の $x\in\R^m$ 以外での値にも依存する性質を **非局所性** という．

## 文献紹介 {.appendix}

Lévy 過程のエルゴード性の結果については，[3.4節 @Kulik2018] によくまとまっている．