---
title: "ベイズデータ解析６"
subtitle: "応答が質的変数の場合"
author: "司馬博文"
date: 12/5/2024
date-modified: 12/29/2024
categories: [Bayesian, Statistics]
bibliography: 
    - ../../../assets/mathematics.bib
    - ../../../assets/bib.bib
    - ../../../assets/bib1.bib
csl: ../../../assets/apalike.csl
abstract-title: 概要
abstract: |
    通常の回帰モデルは応答変数が連続であることが暗黙の仮定となっている．
    この節では，応答変数が質的変数である場合のモデリングを扱う．
    質的変数は順序変数であるか名目変数であるか（順序の構造があるかないか）の峻別が重要である．
    いずれの場合でも多くのモデルが利用可能であり，その多くが一般化線型モデルの枠組みで統一的に扱うことができる．
keywords: [Binomial Model, Multinomial Model, Polychotomous Response Data, Log-linear Model, Bradley-Terry Model, Plackett-Luce Model, Poisson Model, Rank Ordered Data]
image: Files/BayesianWorkflow.svg
listing: 
    -   id: lst-survey
        type: grid
        sort: false
        contents:
            - "BDA1.qmd"
            - "BayesRegression.qmd"
            - "BayesANOVA.qmd"
            # - "Survey2.qmd"
            # - "Survey3.qmd"
            # - "Survey4.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
    -   id: lst-embed
        type: grid
        sort: false
        grid-columns: 1
        contents:
            - "BDA3.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
    -   id: lst-ideal
        type: grid
        sort: false
        grid-columns: 2
        contents:
            - "../TransDimensionalModels/IdealPoint.qmd"
            - "../TransDimensionalModels/IdealPoint1.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
---

{{< include ../../../assets/_preamble.qmd >}}

## 関連記事 {.unnumbered .unlisted}

回帰モデルや分散分析では，暗黙裡に応答変数が連続であることが仮定されている．

::: {#lst-survey}
:::

本節では質的な変数，特に順序構造がある離散変数のモデリングを考える．このようなものを **順序応答** (ordinal response) という．

このようなデータには，多くの場合背後に **連続潜在変数** を仮定してモデリングを行う．

その結果，潜在変数の存在が Gibbs サンプラーの構成を容易にする．

## ２項モデル

### はじめに

$0,1$ の確率変数の分布は，Bernoulli 分布 $\Ber(p)=\Bin(1,p)$ によって記述できる．

この際，パラメータ $p$ を代理の応答変数として回帰分析がなされることになる．

多くの場合，リンク関数 $g$ に関して，$g(p)$ を線型の予測子 $\beta^\top X$ で回帰する．Bernoulli 分布は指数型分布族の例であるため，このようなモデルは **一般化線型モデル** の例になる．

### ロジスティックモデル

仮に変数 $y_i\sim\Ber(p)$ に応じて，
$$
X_i|Y_i=i\sim\rN(\mu_i,\sigma^2),\qquad i\in\{0,1\}
$$
として説明変数 $X_i$ が決まっていたとする．

このような状況で，$X_i$ はある $\al,\beta$ に関して次のロジットモデルを満たす：^[[@Ding2024LinearModels p.222] も参照．]
$$
\operatorname{logit}(p_i)=\al+\beta x_i.
$$

### 潜在変数解釈 {#sec-latent-variable}

$P(\mu,\sigma^2)$ を正規分布やロジスティック分布などの対称な分布，$F$ を $P(0,1)$ の分布関数とする．このとき，プロビットまたはロジスティックモデル
$$
\P[Y_i=1|X_i]=F(X_i^\top\beta)
$$
は，潜在変数 $Y_i^*$ が存在して
$$
Y_i=1_{\R_+}(Y_i^*),\qquad Y_i^*\sim P(X_i^\top\beta,1)
$$ {#eq-latent-logistic}
として結果が決まっているものとも解釈できる．これは
$$
\P[Y_i=1|X_i]=\P[Y_i^*>0|X_i]=\P[-U\le X_i^\top\beta],\qquad U\sim P(0,1),
$$
が成り立つためである．

この潜在変数 $Y_i^*$ は単位 $i\in[N]$ の潜在的な尺度として解釈できる．これを用いて因子分析様の解析を行う例には [理想点推定](../TransDimensionalModels/IdealPoint.qmd) もある．

::: {#lst-ideal}
:::

一方で $Y_i^*$ の存在は Gibbs サンプラーの構成を容易にする [@Albert-Chib1993]．

$F$ を $t$-分布とした場合，これを robit モデル [@Liu2004-robit] という [15.6 節 @Gelman-Hill-Vehtari2020]．$t$ 分布の自由度を無限大にした場合が probit モデルに相当する．

第 [-@sec-utility] 節でまた別の，効用関数による潜在変数表現を扱う．

### 順序応答

前節 [-@sec-latent-variable] の潜在変数解釈は容易に２値応答以外の場合に拡張できる．その結果多項モデルを用いたソフトマックス回帰 [-@sec-softmax-regression] などとは別のアプローチが，多値順序応答に対して可能になる．

$y\in n+1:=\{0,1,\cdots,n\}$ という順序を持った順序応答の場合でも
$$
\chi(u)=1_{(c_0,\infty)}(u)+1_{(c_1,\infty)}(u)+\cdots+1_{(c_n,\infty)}(u)
$$
という階段関数を用いて
$$
Y_i=\chi(Y_i^*),\qquad Y_i^*\sim P(X_i^\top\beta,1)
$$
というデータ生成過程を想定できる．

これはそのまま **順序多項回帰** (ordered multinomial regression) [@Walker-Duncan1967] に相当する．

この場合 $c_0=0$ とし，それに応じて $Y_i^*\sim P(X_i^\top\beta-c_0,1)$ とする径数付けを採用する場合も多い．

ベイズ推論は $\chi$ を特徴付ける点 $(c_0,c_1,\cdots,c_n)$ 上に事前分布を置くことで実行できるが，**順位尤度** (rank likelihood) を通じた議論により，$g$ を特定せずとも Gibbs サンプラーによる推論が可能である [Section 12.1.2 @Hoff2009]．

### 識別可能性と分離

線型回帰において，[共線型性](BDA1.qmd#sec-collinearity) があると識別可能性が失われる．ロジスティック回帰にはもう一つ識別不可能性の典型的な原因がある．

多くの点推定手法において，説明変数の線型変換が極めて強力な説明変数になる場合，やはり「正解」が何個も存在する状況が現れるため，モデルの非識別性が暗黙のうちに問題になる．これを **分離** (separation) という [@BDA p.412]．

特に最尤推定法，一様事前分布を持ったベイズ推定は不安定になるが，このような場合でも裾の重い事前分布を採用することでベイズ推論が安定的に実行可能である（同様にして正則化を加えた最尤推定も可能である） [@Gelman-Hill2006 p.104]．

特に係数に（互いに独立な） $t$-分布 $t(\nu,0,s)$ を仮定する，ロバスト性を意識した設定がデフォルトと理解されている [@BDA p.412]．

ただし，$\nu,s$ は説明変数のスケールに合わせてなるべく無情報になるように設定される．$s\to\infty$ の極限が一様分布になり，分離の問題にセンシティブになっていく．

$g(\mu)=:\theta$ のそれぞれの値に関して，成功試行と失敗試行が同数現れる尤度は $\frac{e^{\theta/2}}{1+e^\theta}$ となり，これは $t(7,0,2.5)$ でよく近似される．

$t(1,0,2.5)$ から $t(7,0,2.5)$ はいずれも $[-5,5]$ に多くの重みを持つが，$\nu=1$ に近いほど裾が重くなる．$g(\mu)$ のスケールで $+5$ をすることは，確率を $0.01$ から $0.5$ にすることに等しいため，切片項への $t$-事前分布は $\mu\in[0.01,0.99]$ を強く仮定していることは含意する．

### ベイズ計算

一般に二項回帰モデルはベイズ計算法の良いベンチマークになる．

大規模なモデルでは事前調整ありの期待伝搬と乱歩 MH が強いが，Gibbs サンプラーや SMC サンプラーも十分良い性能を示す一方で，NUTS などの HMC ベースの手法は苦しむという [@Chopin-Ridgway2017]．

特に説明変数の次元 $p$ が大きい場合の事後分布サンプリングはまだまだ難しいことが知られている．

### 分散分析

[@BDA p.423] 16.5 節は良い例である．アメリカ合衆国における国民の投票行動をロジットリンクにより二項モデルで一般化線型回帰をしている．Bayes ANOVA により人種による大きな効果と同時に，人種と州の強い交差効果が発見できている．

### 選択モデル

計量経済学の分野で古くから使われている潜在変数表現 [-@sec-latent-variable] の拡張として，**選択モデル** (choice model) がある．

これに関しては [階層ロジスティックモデルの稿](BDA3.qmd#sec-choice-model) で詳しく扱う．

::: {#lst-embed}
:::

## 多項モデル

### はじめに

順序応答 $y\in\{1,\cdots,k\}$ の場合，$y$ がカウントを表す場合は Poisson モデル，複数回繰り返される独立試行の成功回数である場合は二項モデルが考えられる．

一方で多項モデル（正確にはカテゴリカルモデル）
$$
Y\sim\operatorname{Cat}(\al_1,\cdots,\al_k),\qquad\sum_{j=1}^k\al_j=1,
$$
も想定できる．$y$ が全く構造を持たない名目 (nominal) 応答である場合，ほぼ唯一の選択である．

### 名目応答に対する多項モデル {#sec-softmax-regression}

名目応答が $k$ 次元ベクトル $y_i\in\N^k$ の形で与えられている場合，
$$
y_i\sim\Mult(n_i;\al_{i1},\cdots,\al_{ik}),\qquad\sum_{j=1}^k\al_{ij}=1,
$$
というモデルを想定できる．$n_i\equiv1$ の場合，応答を one-hot 表現にしたカテゴリカルモデルに対応する．

リンク関数 $g$ は，特定のカテゴリ $j=1$ を **基準** (reference) として $g(\al):=\log\frac{\al}{\al_{i1}}$ と定めることが多い：
$$
\log\frac{\al_{ij}}{\al_{i1}}=X_i\beta^{(j)}.
$$
これを **多項ロジスティック回帰** (multinomial logistic regression) [@Ding2024LinearModels p.228] または **ソフトマックス回帰** (softmax regression) [@Kruschke2015 p.650] という：
$$
\al_{ij}=\operatorname{softmax}(X_i\beta^{(j)})=\frac{e^{X_i\beta^{(j)}}}{\sum_{l=1}^ke^{X_i\beta^{(l)}}},\qquad \beta^{(1)}=0.
$$

係数は，説明変数が $1$ 単位増加した際の，参照カテゴリ $j=1$ に対する対数オッズ比の変化を表す．

一方で条件付きロジスティック回帰 (conditional logistic regression) なる方法もある [22.2節 @Kruschke2015 pp.655-]．

### 効用による表現 {#sec-utility}

多項ロジスティックモデルも潜在変数解釈 [-@sec-latent-variable] が可能である．

$k$ 次元の標準 Gumbel 分布に従う誤差 $\ep_{i-}\in\R^k$ に関して，
$$
U_{il}:=\beta_l^\top X_l+\ep_{il},\qquad l\in[k],
$$
を潜在的な効用とし，
$$
Y_i:=\argmax_{l\in[k]}U_{il}
$$
によって応答が定まると見ることができる [@McFadden1974]．

### 順序応答に対する多項モデル

応答 $y_i\in\{1,\cdots,k\}$ に自然な順序がある場合，カテゴリ確率 $\al_{i1},\cdots,\al_{ik}$ の代わりに累積確率
$$
\pi_{ij}:=\sum_{l\le j}\al_{il}=\P[Y_i\le j]
$$
を考え，モデルにその順序構造を自然に伝えることができる．

この場合リンク関数はロジットやプロビットが使える：
$$
\log\frac{\pi_{ij}}{1-\pi_{ij}}=X_i\beta^{(j)}.
$$
$\beta^{(j)}\equiv\beta$ と取ることも多い．

このモデルを，$g$ がロジットである場合順序ロジスティック回帰 (ordinal / ordered logistic regression) [@McCullagh1980] といい [@Kruschke2015 p.671]，$g$ がプロビットである場合順序プロビット回帰 (ordered probit regression) という．

異なるパラメータ付け
$$
\operatorname{logit}(\pi_{ij})=\beta_0^{(j)}-X_i\beta
$$
を用いた場合，これを **比例オッズロジットモデル** (proportional odds logit model) ともいう [@Ding2024LinearModels p.232]．

### Poisson モデル

応答が $\{1,\cdots,k\}$ カテゴリのカウント $y=(y_1,\cdots,y_k)$ である場合，
$$
y_i\iidsim\Pois(\lambda_i)
$$
というモデルを想定できる．

カウント総数 $n:=\sum_{i=1}^ky_i$ が既知である場合，これに関して条件付けると
$$
y\bigg|\sum_{i=1}^ky_i=n\sim\Mult(n;\al_1,\cdots,\al_k),\qquad\al_i:=\frac{\lambda_i}{\sum_{j=1}^k\lambda_j}
$$
という周辺モデルを想定したことになる．

リンク関数には対数関数 $g=\log$ を用いることが多い．

### トーナメントデータ

一度に２人の単位が勝負をし，どちらが勝利したかのデータに対する標準的なモデルに，[@Bradley-Terry1952] モデルがある．国際チェス連盟や欧州囲碁連盟で選手のランクづけにも採用されている [@Hastie-Tibshirani1998]．

このモデルでは各プレイヤーに能力パラメータ $\al_i$ を与え，能力の差のロジスティック関数
$$
\P[i\;\text{defeats}\;j]=\frac{e^{\al_i-\al_j}}{1+e^{\al_i-\al_j}}
$$
という確率で勝敗が決まるとする．$\lambda_i:=e^{\al_i}$ というパラメータづけもよく用いられる．

このモデルは「勝利」「引き分け」「敗北」の３応答に対する確率モデルを調節することで，引き分け [@Rao-Kupper1967] や先手有利 [@Davidson-Beaver1977], [@Agresti12-CategoricalData] などの情報も取り入れられるように簡単に拡張できる．

このように２値応答ではなく多値応答とみても，前節の Poisson モデルの定式化に帰着させることで，一般化線型モデリングの枠組みに合流させることができる [@BDA pp.427-428]．

### 順位データ

ランキングデータは，トーナメントのような常に１対１比較のみを通じて情報が得られるわけではない．多者比較 (multiple comparison) も取り入れた Bradley-Terry モデルより一般的なものが [@Plackett1975]-[@Luce1959] モデルである．

Plackett-Luce モデルでは，参加者 $[K]:=\Brace{1,\cdots,K}$ の強さに当たる潜在変数 $\lambda_k>0$ を導入し，これに比例した「優勝」確率を持つとする．そして順位の決定は，参加者のプールから「勝ち抜け」の１人を決定する独立試行の繰り返しと見て，
$$
\P[Y=y|\lambda]=\prod_{j=1}^{K-1}\frac{\lambda_{y_j}}{\sum_{l=j}^K\lambda_{y_l}}
$$
としてモデリングする．

このモデルは，「陽の目を見る瞬間」
$$
W_k\iidsim\Exp(\lambda_k)
$$
という到着時刻があり，この時刻の早さで順位が決まる
$$
\P[W_{y_1}<\cdots<W_{y_K}|\lambda]=\P[Y=y|\lambda]=\prod_{j=1}^{K-1}\frac{\lambda_{y_j}}{\sum_{l=j}^K\lambda_{y_l}}
$$
という潜在変数表現を持つ．これは Thurstone 表現 [@Thurstone1927]，またはランダム効用モデルと呼ばれる [Chapter 9 @Diaconis1988 p.167]．

このような潜在変数表現を元にした MM アルゴリズム [@Hunter2004] や Gibbs サンプラー [@Caron-Doucet2012] に基づく推論法が存在する．`PlackettLuce` パッケージ [@Turner+2020] も参照．

さらに Plackett-Luce モデルで引き分けを許すように拡張したものが Gibbs サンプラーとともに [@Henderson2024] で提案されている．

### 対数線型モデル

$y$ も $x$ も名目応答である場合，これは分割表解析の問題になる．

この際には [**対数線型モデル**](https://en.wikipedia.org/wiki/Log-linear_analysis) (log-linear model) も考えられる．

それぞれのセルに Poisson モデルをおき，そのパラメータを代理応答変数として，対数リンクにより一般化線型回帰を行うものである．

このモデルは，サンプルサイズ $N$ が既知の場合などの下では，周辺分布に多項モデルをおくことに等価である [@Yates1934]．

対数線型モデルは分割表解析だけでなく，[多重代入法](Survey3.qmd#sec-MI) などの欠測データ解析にも応用される．

## コピュラモデル

### はじめに

以上の質的変数のモデルは，いずれも潜在的な連続変数の離散化としてデータを理解するものであった．

仮にこの潜在変数により興味がある場合，この潜在変数をより具体的に，特にその相関構造をモデリングしたいということになる．

[@Lopez-Paz+2013]

## 文献紹介 {.appendix}

[@BDA] の 16 章で一般化線型モデルが扱われている．[@Kruschke2015] はさらに詳しく，22 章で名目応答，23 章で順序応答，24 章でカウントデータを扱っている．

[12 章 @Hoff2009] にて正規コピュラモデルが ordinal probit モデルの，潜在変数を多次元に拡張した場合として導入されている．

[@Chib-Winkelmann2001] はリンクを対数関数とし，Poisson 周辺分布を持つカウントデータのコピュラモデリングを実行している．

[@Quinn2004] は連続確率変数に対してコピュラモデリングを実行している．