---
title: "ベイズデータ解析２"
subtitle: "平均処置効果の推定"
author: "司馬 博文"
date: 9/23/2024
date-modified: 9/25/2024
categories: [Statistics]
bibliography: 
    - ../../../assets/mathematics.bib
    - ../../../assets/bib.bib
    - ../../../assets/bib1.bib
csl: ../../../assets/apalike.csl
abstract-title: 概要
abstract: |
    人間を対象にする介入の研究では，介入の前後で変化があったかが争点となる．
image: Files/ATE.svg
listing: 
    -   id: lst-survey
        type: grid
        sort: false
        contents:
            - "Survey1.qmd"
            - "Survey3.qmd"
            - "Survey4.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
---

{{< include ../../../assets/_preamble.qmd >}}

## はじめに

### 概観

現代の因果推論は平均処置効果 (ATE)
$$
\tau=\E[Y_i(1)]-\E[Y_i(0)]
$$
と関連する推定対象 (estimand / target parameter) に集中している．

ランダム化された実験，あるいは欠測メカニズムが推定しやすいように工夫された「擬似実験」を行なった場合は，ほとんどモデリングの議論を表に出さずに ATE を不偏推定できる．

しかし擬似的な実験も難しい状況下では，モデリングや DAG を通じた識別可能性の議論が欠かせない．

### 経済学における因果推論の歴史

経済学において，[@Haavelmo1943] は「構造推定」の枠組みで統計的因果推論を捉えた．^[[@川口-澤田2024], [@Pearl2015] も参照．]

構造推定では「同時方程式」により統計モデルを定義するが，その際には識別可能性が問題になる．

このアプローチでの経済学は大きな批判に晒された．

### 計量経済学における信頼性革命

[@Leamer1983] は計量経済学の手法と古典的な実験科学とを比較し，計量経済学の信頼性は感度解析とロバストを取り入れることによって（のみ）回復されるだろうと論じた．

[@Leamer1983] が「よく計画された実験を超える統計的手法など出てこないかもしれない」と論じていた通り，その後の信頼性革命は主に実験計画を改善することによって達成された [@Angrist-Pischke2010]．

そのキーワードは「自然実験」や「擬似実験」と呼ばれており，サーベイ手法での「擬似ランダム化」アプローチに相当する．[擬似ランダム化については次稿も参照](Survey3.qmd)．

## 文献案内 {.appendix}

### ベイズ推定 {.appendix}

平均処置効果のベイズ推定は初めから [@Rubin1978] により考えられていた．

近年のレビューには [@Li+2023-BayesianCausalInference] がある．

> First and most importantly, by enabling imputation of all missing potential outcomes, the Bayesian paradigm provides a unified inferential framework for any causal estimand. [@Li+2023-BayesianCausalInference p.18]

頻度論的な因果推論手法は特にモデルフリーな感覚があり，応用分野に浸透しきっている．モデリングの必要性を感じにくいこともあり，ベイズ的な方法が出遅れたままの感がある．

ベイズ手法の成功事例には [@Dorie+2019] がある．ここでは，2016 年の Atlantic Causal Inference Conference のデータ解析コンペティションで，BART (Bayesian Additive Regression Trees) に基づく手法が優勝したことが考察されている．

> In general, Bayesian nonparametrics offers both the flexibility of modern machine learning algorithms and the statistically-principled uncertainty quantification of Bayesian inference. [@Linero-Antonelli2023]

### 計量経済学 {.appendix}

[@川口-澤田2024] は日本語の文献であるが，最新の手法も含めた潜在結果モデルの因果推論手法を，計量経済学の構造推定の文脈から切り離して紹介しており，計量経済学に限らず広い聴衆にリーチすべき内容になっている．[GitHub サポートページはこちら](https://github.com/keisemi/EconometriciansGuide_CausalInference)．

### 生物統計学 {.appendix}

[@Hernan-Robins2020] は 2024 年 reviesed 版も [無料で公開されている](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/)．

### 社会科学 {.appendix}

[@Morgan-Winship2014] は社会学の本である．

### 統計学 {.appendix}

[@Rosenbaum2023] は統計学の本である．