---
title: "Quartoの基本 | Quarto Basics in Japanese"
author: "Hirofumi Shiba"
date: "11/4/2023"
categories: [Quarto]
abstract: Hello, Quartoのページを日本語訳した
abstract-title: 概要
toc: true
---

## デモページ

The followings were pasted from the [official documentation](https://quarto.org/docs/get-started/hello/vscode.html).

For a demonstration of a line plot on a polar axis, see @fig-polar.

```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 4 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

## 使い方の概要

QuartoではこのようなNotebook-likeなドキュメントが，極めて簡単に＋凡ゆるフォーマットで作成できる．
特にVSCodeの拡張機能と組み合わせれば，`RStudio`のような隙のない統合開発環境が得られる．またVSCodeでは[ビジュアルモードでの編集](https://quarto.org/docs/visual-editor/vscode/)もサポートされており，Jupyter Notebookと全く同じ使用感で始められる．

基本的な仕組みとして，自分で作成するのは `.qmd`ファイルのみである．その後は`quarto render`コマンドにより，コードブロックはJupyterによって処理され，全体はmarkdownに変換され，Pandocによって`pdf`, `html`, `word` など好きな形式に最終出力できる．

拡張機能をオンにしたVSCodeでは`Run Cell`ボタンもあるので，ノートブック全体を毎度ビルドせずとも，コードブロックごとに実行して結果を見ることもできる．`Ctrl+Enter`で１行ごとに実行できる操作感は`RStudio`と同じである．

各ファイルの冒頭にYAML blockを用意することで，ノートブックの詳細を調整できる（参照：[HTML Options](https://quarto.org/docs/reference/formats/html.html)）．

```{YAML}
---
title: "Quarto Basics"
format:
  html:
    code-fold: true
jupyter: python3
---
```

本文はmarkdown記法で書く．数式も使える：
$$\mathrm{P}[|\xi|<t]\le2e^{-\frac{t^2}{2\sigma^2}},\qquad t>0.$$

また，コードブロックにもコメントアウトと接頭辞の組み合わせ`#|`を前につけることでYAMLで指示が出せる（参照：[指示のリスト](https://quarto.org/docs/reference/cells/cells-jupyter.html)）．上のコードブロックには

```{YAML}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"
```

と追加されているために，出力された図にラベリングとキャプションが付いているのである．

## 美点
* レンダリングがとんでもなく速い．体感でTeXの10分の1である．
* それでいて数式とコードブロックを併在させることが出来る．
* ローカル環境で動く．Jupyter Notebookが続かない筆者にとって，この点は肝要である．
* 私用の勉強ノートとしても使えると同時に，内容そのままブログとして公開できる．
* すごい細かいが，例えば`project type`を`website`としたリポジトリで`quarto render`をしても，不要なファイルが自動で削除される．このような点がライトユーザーでもとにかく使いやすい．