---
title: "ベイズ計算とは何か | About Bayesian Computation（執筆中）"
author: "Hirofumi Shiba"
date: "12/6/2023"
categories: [Survey, Computation]
toc: true
number-sections: true
twitter-card: true
code-block-bg: true
code-block-border-left: "#31BAE9"
code-overflow: wrap
code-fold: true
bibliography: ../../../mathematics.bib
csl: ../../../apa.csl
abstract-title: 概要
abstract: 「ベイズ統計学」は一大トピックであるが，「ベイズ計算」という分野があることはそれほど周知のことではない．この分野の問題意識を，「ベイズ計算」分野の歴史と共に理解することを試みる．
crossref:
  sec-prefix: 節
  eq-prefix: 式
---

# 「ベイズ計算」の「ベイズ」とは何者か？

> 賭博，生命保険，確率論この三つの間には，その発生に切っても切れない因縁がある．この点を明確に摘出することは，統計学の黎明を知るのに不可欠であろう． [@北川敏男49-統計学の認識]

> de Moivreを彼の著”Approximation”に，またBayesを彼の定理に導いた原因は，純然たる数学的なものというよりも，神学的及び社会学的のものであった． [@Pearson1926]

## ベイズまでの統計学の黎明

統計学の黎明を要請したものは，社会への不安であった．筆者に言わせれば，この社会への不安を直視したのがドイツ，数で解決しようとしたのがイギリスで，解決への筋道を確率論で基礎づけたのがフランスである．

17世紀初頭から何度も流行を繰り返し，遂に1665年にはロンドンの人口の1/4を死に至らしめた [ペストの大流行](https://ja.wikipedia.org/wiki/%E3%83%AD%E3%83%B3%E3%83%89%E3%83%B3%E3%81%AE%E5%A4%A7%E7%96%AB%E7%97%85) は恐怖の対象であった．パンデミックは現代でも恐怖の対象であるが，当時はその全貌の把握が難しく，これが第一に切望された．月の運行による健康被害，国王の統治が疫病を引き起こす，などの俗見が流布していた時代である．しかし，「数」という解決手段は極めて功を奏した．

数による解決が他でもないイギリスから生まれたことは，Francis Bacon 1561-1626 に象徴される自然科学の風土，「Aristotelesの三段論法を通じて，経験的に因果関係を発見することで，我々は自然を理解できる」という希望が当時のイギリスには存在したことが挙げられる．

> 海へ行け，きっと獲物があるぞという先輩がBaconであった．漁獲法一般の講義をする先生が，例えば後世のJ. S. Millの帰納論理学に相当するのである．統計学を作った漁師たちは，Mill先生の帰納法の論理学の講義などは，上の空で聞いた．そして各自の漁獲法を自らの浜で覚えたのである． [@北川敏男49-統計学の認識 p.12]

### John Grauntの死亡表

最初にペスト流行の激しさの判定に寄与する人口状況を，数によって理解しようとしたのが [John Graunt](https://en.wikipedia.org/wiki/John_Graunt) 1620-1674 であった．

当時の英国王立理学協会は^[正式名称をThe Royal Society for the Improvement of Natural Knowledge by Experimentという] は，封建的な諸関係の崩壊解消と同時に，商品生産・貨幣による売買の全面支配によって貨幣的表現が富の大部分に侵入したことにより新たに誕生した市民階級が勢力を占めており，Grauntもこのような商人階級の出身である．

そのような身分のGrauntが英国王の推薦を受けて王立協会員の名誉を勝ち取った論文 [@Graunt1662] は，ギルド発行の死亡統計 [Bills of Mortality](https://en.wikipedia.org/wiki/Bills_of_mortality) と教会に蓄積していた統計資料^[当局の人間に死亡を報告する義務は全くなかった。その代わり、それぞれの教区では2人かそれ以上の死体を調査し、死因を決定する義務を負う調査員を任命していた。「調査員」は死亡を報告する毎に遺族より少額の手数料を徴収する資格が与えられていたので、教区では任命しなければ貧困のため救貧税による支援が必要となりそうな人間を割り当てていた。（[Wikipediaページより](https://ja.wikipedia.org/wiki/%E3%83%AD%E3%83%B3%E3%83%89%E3%83%B3%E3%81%AE%E5%A4%A7%E7%96%AB%E7%97%85)）] から統計的な処理を通じて世界初の「死亡表」を作成し，次の内容を初めて結論づけた．

- 36%の幼児は６歳未満で死亡する．
- 洗礼数をみると，男女比は16:15くらいである．
- 都市の死亡率は地方より高い．
- Londonの城外では死亡率は３倍である．

加えてLondonの世帯数を3通りの方法で推算し，世帯数は5万であろうと結論づけた．なお，当時の俗見ではLondon人口は100万と言われていた．男女比は1:3と言われているものもある．

その後このような生命表はギルド的な共助制度の土壌の上で生命保険の成立としても結実した．

### 統計学への期待と希望

このイギリスの数を使った解決は，[政治算術学派](https://ja.wikipedia.org/wiki/%E6%94%BF%E6%B2%BB%E7%AE%97%E8%A1%93) と呼ばれ，海外への輸出が進んだ．

ドイツの牧師 [Johann Peter Süβmilch](https://ja.wikipedia.org/wiki/%E3%83%A8%E3%83%8F%E3%83%B3%E3%83%BB%E3%83%9A%E3%83%BC%E3%82%BF%E3%83%BC%E3%83%BB%E3%82%B8%E3%83%A5%E3%83%BC%E3%82%B9%E3%83%9F%E3%83%AB%E3%83%92) 1707-1767 は Graunt に倣って，教会に蓄積していた統計資料を用い，出生率の性別比が長期的には女性1,000対男性1,050に収束することを発見した．

中でも特に，「たくさんのデータを集めると何かが見えてくる」ことに大きな希望を持ち，Grauntが教会の資料に注目したことをColumbusの新大陸発見になぞらえている．

> 若し我々が家を一軒一軒数えていくならば，ある家では娘だけに，またある家では息子だけに，あるいはそうでなくとも，非常に不釣り合いな両者の配合にでくわすであろう．小さな社会や村落でも秩序的なものを認めることは，容易ではない．（中略）．かかる場合に，誰が，能く規則と秩序とに想達し得るだろう．所で，教会の記録はこの秩序の確認のための大きな手段である．それは教会用及び世俗用のためにすでに数世紀前から取られ，**とくに宗教改革後はかなり正確にとられてきた**．誰がそれを利用したか？その発見はアメリカ発見と同時に可能であったのだ．（中略）**それをGrauntがなし得たのである**．
> Süβmilch (1741) 『神の秩序』

このようにSüβmilchは男児の出生率の方が高いことを神の存在証明と見なしたのであった．この宗教的な外被を取り去るには，確率論の登場をまたねばならなかったが，これにはさらにフランスの学派が合流するのを待つ必要があり，それには100年を要したのであった（ @sec-Laplace も参照）．



## ベイズが取り組んだ問題

というわけで，$i=1,\cdots,n$ 番目の世帯の新生児が，男児である $y_i=1$ か女児である $y_i=0$ かのデータなどから，人口・疫病・国家動態に役立つ知識を引き出すことが当時の重要な問題意識であることをわかっていただけただろう．

時代が下り，やはりイギリスの牧師 [Thomas Bayes](https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%BC%E3%83%9E%E3%82%B9%E3%83%BB%E3%83%99%E3%82%A4%E3%82%BA) 1701-1761 の時代では，より抽象的な設定で統計的推定の問題が研究されていた．中でもBayesは，次のような「区間推定」の問題を考えていた．

{{< include ../../../_preamble.qmd >}}

::: {.callout-tip icon="false" title="ベイズが取り組んだ問題（現代語訳）"}
2値のデータ $Y_i\in\{0,1\}$ は，ある未知の「成功率」 $\theta\in(0,1)$ に従って，
$$
Y_i=\begin{cases}
1&\text{確率 }\theta\text{ で}\\
0&\text{残りの確率} 1-\theta\text{ で}
\end{cases}
$$
という値を取るとする．^[これは統計的モデルとしてBernoulli分布 $Y_i|\theta\iidsim\Ber(\theta)$ を仮定するということである．] このようなデータが独立に観測されて，標本 $\y:=(y_1,\cdots,y_n)^\top$ と得られているとする．神のみぞ知る，このデータ $\y$ を生み出した真の成功率 $\theta$ が区間 $(a,b)\subset(0,1)$ に入っているという確率 $\P[a<\theta<b|\b{y}]$ をどう見積もれば良いか？
:::

以上，抽象的に述べたが，わかりやすいように引き続き $Y_i$ は性別で，$\theta$ は男児が生まれる確率 $\theta=\P[Y_i=1]$ だと解釈する．Bayes自身は「白線が引かれたテーブル上にボールを $n$ 個転がし，それぞれの領域に幾つのボールが入ったかの情報のみから，白線の位置を推定する」という定式化した [@Bayes1763], [こちらのサイト](https://www.tcbegley.com/blog/posts/bayesian-billiards)も参照．

## ベイズのアイデア

彼の発想は極めてシンプルである．

1. まず**事前分布** $p(\theta)$ と呼ばれる，最初の $\theta\in(0,1)$ に対する予想を自由に表現する．
2. この事前の信念をデータを用いて修正する形で，**事後分布** $p(\theta|\y)$ を得る．これは「データ $\y$ が得られた，という条件の下で考えた条件付き分布」である．
3. この事後分布の形から区間推定を実行する．

この3.の部分は，Bayesが特に区間推定に拘ったためのものであり，点推定でも良ければ次期予測でも良い．3.を自由に入れ替えても，1.と2.の部分が同じように動作するということ，これがベイズ統計学である．

また，読者は，パラメータ $\theta$ は「男児が生まれる確率」であるが，これ自体にも事前分布という「確率」$p(\theta)$ を導入することに戸惑うだろう．しかし，**これがベイズ統計学の特徴である**．「男児が生まれる確率 $\theta$」だろうとなんだろうと，「わからない」と主観的に感じるあらゆる対象に，確率分布を導入する，これがベイズ統計学の枠組みの普遍性であり，無差別性であり，有用性を支えている．

::: {.callout-note icon="false" title="[@Bayes1763] の解決"}
1. まず，事前分布を設定する．Bayesは 「$\theta\in(0,1)$ は全く予想がつかない」「どんな $\theta$ もあり得る」という立場を取った．すなわち，どんな $\theta\in(0,1)$ に対しても，その「あり得る度」は一定だとしたのである．横軸を $\theta\in(0,1)$ の値，縦軸を「主観的にあり得ると思う度合い」として図で表すと次の通りである：
```{python}

import matplotlib.pyplot as plt
import numpy as np

# Define the range for x-axis
x = np.linspace(0, 1, 1000)

# Uniform distribution density function is constant
y = np.ones_like(x)

# Plot the graph
plt.figure(figsize=(3, 2)) # Size suitable for a smartphone screen
plt.plot(x, y, label='Uniform Distribution (0,1)', color=(0.35, 0.71, 0.73, 1))
plt.fill_between(x, y, color=(0.35, 0.71, 0.73, 0.3))
plt.xlabel('x')
plt.ylim(0, 1.5)
plt.ylabel('Density')
plt.title('Density Function of Uniform Distribution on (0,1)')
plt.legend()
plt.grid(True)
plt.show()
```
これを一様分布という．このように，一様分布とは「どのような $\theta$ の値も同様に確からしい」という予想の表現である．

1. しかし，データ $\y=(y_1,\cdots,y_n)^\top$ が得られている今，どんな $\theta$ も等しく尤もらしいという訳ではない．そこで，「データ $\y$ に関する条件付き分布」を計算することとする．実は，簡単な確率の法則から，次の公式を得ることができる（[講義ノート](%E6%B3%95%E5%BE%8B%E5%AE%B6%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E7%B5%B1%E8%A8%88%E6%95%B0%E7%90%862.qmd#sec-Bayes-formula)も参照）：^[各 $\theta$ の下で目の前のデータ $Y_1,\cdots,Y_n$ が生成される確率 $p(Y_1,\cdots,Y_n|\theta)$ が低いということは，「その $\theta$ から生成されたデータである確率は低い」という逆の発想ができる．そこで $p(Y_1,\cdots,Y_n|\theta)$ という条件付き確率を**尤度**ともいう．]
$$
p(\theta|\y)=\frac{p(\y|\theta)p(\theta)}{\int_\Theta p(\y|\theta)p(\theta)\,d\theta}
$$ {#eq-Bayes-formula}
    この公式を用いて，条件付き分布 $p(\theta|\y)$ を計算する．例えば [日本の2021年の出生児性別のデータ](https://www.e-stat.go.jp/dbview?sid=0003411595) を用いると次のようになる．

```{python}
import matplotlib.pyplot as plt
from scipy.stats import beta

# パラメータの設定
n = 811622
male = 415903
female = n - male

# ベータ分布のPDFを計算
x = np.linspace(0, 1, 1000)
y = beta.pdf(x, 1+male, 1+female)

# プロット
plt.figure(figsize=(3, 2))
plt.plot(x, y, label=f'Beta({1+male}, {1+female})', color=(0.35, 0.71, 0.73, 1))
plt.fill_between(x, y, color=(0.35, 0.71, 0.73, 0.3))
plt.xlabel('p')
plt.xlim(0.4, 0.6)
plt.ylabel('Probability Density')
plt.title('Bayesian Posterior Distribution')
plt.legend()
plt.grid()
plt.show()
```

こうして極めて鋭い事後分布が出来た．@eq-Bayes-formula の妥当性を認めるならば，この図は「男児の方が女児よりも生まれる確率が高い」ことの証拠として，極めて説得的ではないだろうか？

3. では区間推定の例として，$(a,b)=(0.5,1.0)$ として，「男児の方が女児よりも多い確率」を推定しよう．これは次を計算することになる：
$$
\begin{align*}
    &\P\Square{\frac{1}{2}<\theta<1}\\
    &=\int^1_{\frac{1}{2}}p(Y_1,\cdots,Y_n|\theta)\,d\theta.
\end{align*}
$$
```{python}
print(sum(y[500:600])/1000)
```
もはや丸め誤差により $1$ を越してしまっている．ほとんど確実に「男児の方が生まれる確率が高い」と結論づけて良いだろう．
:::

この [@Bayes1763] が実行したように，**事後確率 $p(\theta|Y_1,\cdots,Y_n)$ をみて $\theta$ に関する推論をする**，という立場からの統計的営み全体を，**ベイズ統計学**という．

## ベイズ統計学の基本問題 {#sec-fundamental-problem-of-Bayes}

事後確率を導く際に用いた @eq-Bayes-formula は[**Bayesの公式**]((%E6%B3%95%E5%BE%8B%E5%AE%B6%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E7%B5%B1%E8%A8%88%E6%95%B0%E7%90%862.qmd#sec-Bayes-formula))と呼ばれており，従ってベイズ統計学の最も肝要なパーツである．今回の場合では，Pythonコードをご覧になった方はわかったかもしれないが，
$$
p(\theta|\y)=\frac{\theta^m(1-\theta)^{n-m}}{B(m+1,n-m+1)}
$$
となっており，これは $(0,1)$ 上の [Beta分布](../2023-11-24/Beta-Gamma.qmd) と呼ばれるものである．

現代のBayes統計学の多くの統計量は，ある関数 $g:\Theta\to\R$ を用いて
$$
\E[g(\theta)|\y]=\int_{\Theta}g(\theta)p(\theta|\y)\,d\theta
$$
と表される．先ほどのBayesの区間推定の例では $g=1_{(a,b)}$ と取った場合に当たる．^[さらに，$g(\theta)=\theta^p$ と取った場合，事後積率という統計量になる．等に $p=1$ の場合が事後平均である．] 

実は，**この最も簡単と思われる設定でも，この積分は殆ど計算できないのである**．そのこともあってか，論文 [@Bayes1763] は実はBayesの死後にRichard Priceによって投稿されたものであり，生前に自ら投稿・発表した訳ではなかった．^[なお，1763に出版されたものはPriceによる補遺も付いた短縮版であり，全文は1974年に出版された．[@Stigler1990]] 当然，発表当時も全く注目を受けなかった [@Stigler1990]．

> Hence, despite the analytical availability of $p(\theta|\y)$ via (2)--“Bayes’ rule” as it is now known-—the quantity that was of interest to Bayes needed to be estimated, or *computed*. The quest for a computational solution to a Bayesian problem was thus born. [@Martin+2023-history p.2]

::: {.callout-important title="ベイズ統計学の基本問題" icon="false"}
ベイズの枠組み

1. まず**事前分布** $p(\theta)$ と呼ばれる，最初の $\theta\in(0,1)$ に対する予想を自由に表現する．
2. この事前の信念をデータを用いて修正する形で，**事後分布** $p(\theta|\y)$ を得る．

は非常に自然で，特に確率分布を簡単にプロットできる現代では不確実性が明確に図示できるという美点がある．しかしながら，モデル $p(\theta),p(\y|\theta)$ の設定をいくら簡単にしても根本的に計算が困難で実行不可能なのである．これを解決する分野を**ベイズ計算**という．Bayesの論文 [@Bayes1763] でも，計算法の開発が約半分を占めた．^[pp.376-403 がBayesの論文の本論の内容であり pp.399-403 で計算法を３つのルールにまとめているが，その導出部は一部「長すぎるから掲載を省略する」とされている．] このように，**Bayes統計学は当初からBayes計算の問題を懐胎していた**のである．

> In short, the implementation of all forms of Bayesian analysis relies heavily on numerical computation. [@Martin+2023-history p.2]
:::

## Laplaceの近似 {#sec-Laplace}

Laplace 25歳時の初めての統計に関する著作 [@Laplace1774] で，Bayesが解こうとしたものと全く同じ

$$\begin{align*}
    &\P[a<\theta<b|\y]\\
    &\quad=\frac{\int^b_a\theta^m(1-\theta)^{n-m}\,d\theta}{B(m+1,n-m+1)}
\end{align*}$$ {#eq-Beta-integral}

という積分の計算の問題を，被積分関数を
$$
f(\theta):=\frac{\log p(\theta|\y)}{n}
$$
を用いて指数関数の形に表すことで解いた：
$$
\begin{align*}
    \P[a<\theta<b|\y]&=\int^b_ap(\theta|\y)\,d\theta\\
    &=\int^b_ae^{nf(\theta)}\,d\theta
\end{align*}
$$
この形に変形することがどのように役立つかは，次の定理が説明してくれる：

::: {.callout-tip title="定理（Laplace近似）"}
^[[nCatLab](https://golem.ph.utexas.edu/category/2021/10/stirlings_formula.html) 参照．]
関数 $f:[a,b]\to\R$ はただ一つの最大値を $x_0\in(a,b)$ で取り，$f''(x_0)>0$ を満たすとする．このとき $n\to\infty$ の極限について，
$$
\int^b_ae^{nf(x)}\,dx\sim\sqrt{-\frac{2\pi}{nf''(x_0)}}e^{nf(x_0)}
$$
:::

これを $f$ の二次近似について適用することで，あらゆる確率分布 $p(\theta|\y)\,d\theta$ に関する積分 @eq-Beta-integral について，その正規近似の積分で近似できるのである．

この手法は現在のBayes計算手法のアイデアの源泉であり続けている [@Rue+2009]．

## ベイズ統計学の長く苦しい時代

上述の「[@Bayes1763] の手法は理念的に好ましかろうと，実際には実行不可能である」という問題は，Laplaceが普遍的な近似計算手法を開発したこと（ @sec-Laplace ）を除いて，計算機の発明と普及を待つ必要があった．その間実に2世紀超えである．

また，Laplaceの近似手法は普遍的であり，Bayesの最初の設定のような簡単な $p(\theta|\y)$ と $g=1_{(a,b)}$ に限らずとも使えるという，ベイズ統計学にとって最も重要な特徴も備えていたが，パラメータ $\theta\in(0,1)$ の次元が1ではなくなると途端に使えなくなるという欠点がある．

> （前略）ベイズ統計学の有用性は以前から理解されていたが，この問題の抜本的な解決は1980年代まで待たざるを得なかった．**それ以前は，ベイズの定理自体は18世紀に早々に発見されたにもかかわらず，長い間，確率の解釈，事前分布の設定，事後分布の計算の困難さのために哲学的議論に終始し，実用化にはほど遠かったのである**．実用化の扉の鍵となったのは，一つは計算機の急速な発達，もう一つは計算集約的な画期的アルゴリズムの提案である． [@樋口知之2014 p.17]

## フランスでの確率論の歴史

このように，Laplaceが，ベイズ統計学暗黒の時代の中で唯一の小さな前身を産んだ．それだけでなく，Laplaceは確率論最大の集大成を産んでおり，これが他でもないフランスから生まれたことにも相応の理由があった．

まず第一に，賭博の流行により，確率というものの理解と征服が嘱望された．

> その（確率論の）発展の動きを与えたものは，交易を賭ける商業資本家が占星術よりも確実な指導をこの学術に求めるという様な社会が基盤となって存在したことである．例えば，17世紀中葉のPascalとFermatの間の往復文書に取り扱われたカード遊びの数学的問題が，広く人々の関心を呼び起こした事情の裏には，至富の途を確実に求める商人たちの渇望が学問が外の世界にあったことを忘れてはならない． [@北川敏男49-統計学の認識]

第二に，統計的現象を神学的な畏怖の対象と見るのではなく，自然科学による自然の理解と征服の文脈の最先端として理解する土壌がフランスにあったことが指摘できる．

> 17, 18世紀の啓蒙的合理主義は，偶然的な事象に対しても数学的な取り扱いを行うことに特別の興味を持った．思想的にはこの時代精神こと確率論を発展させた最大の動力であった．その駆使する数学解析の多彩と合理主義の徹底とに於て，Laplaceの大著はよくこの時代を代表するものと言うべきであろう．

> 古典確率論の一応の完成は典雅に見えるであろう．**だが人は，確率論のもった政治的，社会的意義を忘れてはならない**．理知を一切の尺度として「代数学の炉火によって倫理学及び政治学を照さん」([Condorcet](https://ja.wikipedia.org/wiki/%E3%83%8B%E3%82%B3%E3%83%A9%E3%83%BB%E3%83%89%E3%83%BB%E3%82%B3%E3%83%B3%E3%83%89%E3%83%AB%E3%82%BB)) という時代精神，神の啓示に代らんとする確率論，それはフランス革命の思想的基礎に連関することを見失ってはならないのである． [@北川敏男49-統計学の認識]

# MCMCの発明

「積分が計算できない」というベイズ統計学の基本問題（ @sec-fundamental-problem-of-Bayes ）は，計算機の発達と普及と同時に，**シミュレーションによる確率的アルゴリズムの開発**によって根本的に解決された．

しかし，この解決法は必ずしもベイズ統計学のために考案されたわけではなく，むしろ物理学と第二次世界大戦とに深い関係があった．

$$
\E[g(\b{\theta})|\y]=\int_{\Theta}g(\theta)p(\theta|\y)\,d\theta
$$

> In fact, until Bayesians discovered MCMC, the only computational methodology that seemed to offer much chance of making practical Bayesian statistics practical was the portfolio of quadrature methods developed under Adrian Smith’s leadership at Nottingham (Naylor and Smith 1982; Smith et al. 1985, 1987). [@Green+2015 p.836]

## モンテカルロ法の発明

乱数のシミュレーションを用いた確率的なアルゴリズムをMonte Carlo法と総称する． [@Metropolis+1953] が提案したMetropolis法も，Monte Carlo法の一種である．



# ベイズ統計学のこれから

更なる複雑なモデル・データに対応できるベイズ計算手法の開発が最も肝要な課題だと筆者は信じる．

## ベイズ統計モデリングが理論モデルの実証に役立つ

ベイズモデルの有用性は，複雑なモデルにも統一的な方法で対応できる点にもある．

> メカニズムを明示的に表現した数理社会学の数理モデルを，論理的に飛躍することなくダイレクトに統計モデルへと接続できるベイズ統計モデリングは，理論モデルベースの実証研究と相性のよい，たいへん便利な方法と言えるだろう． [@浜田宏2022 p.137]

MCMCの開発とパッケージへの実装と安価で高性能な計算機が普及してからベイズ統計学の興隆は目覚ましく，現在ではベイズ統計学は統計学に関する論文の1割強を占め，諸科学分野全体に浸透しつつあるが，経済学・心理学への応用は早かったのに比べて，政治科学・社会科学への応用は遅れ気味であり，社会学での使用はまだ稀であると言える [@Lynch-Bartlett2019]．