---
title: "分岐過程"
author: "司馬博文"
date: 12/23/2023
categories: [Process]
toc: true
number-sections: true
code-block-bg: true
code-block-border-left: "#31BAE9"
code-overflow: wrap
code-fold: true
bibliography: ../../../mathematics.bib
csl: ../../../apa.csl
abstract-title: 概要
abstract: 分岐過程の定義と歴史，性質についてまとめる．
crossref:
    sec-prefix: 節
    eq-prefix: 式
    def-prefix: 定義
    def-title: 定義
    thm-prefix: 定理
    thm-title: 定理
---

{{< include ../../../_preamble.qmd >}}

## 離散分岐過程

### 定義

::: {#def-BGW .callout-tip icon="false"}
## 定義^[この一般的な定義は [@Quine-Szczotka1994] を参考にした．歴史は [@Kendall1975], [@Heyde-Seneta1977] が詳しい．[@Bienayme1845] が初めに考察をしたが，注目されなかった．[@Watson-Galton1875] は注目されたが，数学的な議論には誤りが含まれていた．] ：Bienaymé-Galton-Watson 過程 [@Bienayme1845], [@Watson-Galton1875]

$Y_1,Y_2,\cdots$ を $\bZ$-値確率変数の列とし，$\mu\in\cP(\bZ)$ を初期分布とする．これに対して
$$
X_0\sim\mu,\quad X_{n+1}:=1_{\Brace{X_n\ge1}}\sum_{j=T_{n-1}+1}^{T_{n-1}+X_n}Y_j,
$$
$$
T_{-1}:=0,\quad T_n:=\sum_{j=0}^nX_j\quad(n\in\N),
$$
と定める．この過程 $\{X_n\}_{n=0}^\infty$ を **分岐過程** といい，分布を $\P_\mu$ と表す．

特に $\{Y_n\}_{n=1}^\infty\subset\L(\Om;\N)$ が非負で独立同分布である場合，過程 $\{X_n\}_{n=0}^\infty\subset\L(\Om;\N)$ を **Bienaymé-Galton-Watson 分岐過程** という．
:::

$X_n$ を第 $n$ 世代の個体数と解釈してみよう．$T_n$ は第 $n$ 世代までを含め，存在し得た全個体数を意味することとなる．

第 $n$ 世代を構成する $X_n$ 個体がそれぞれ $Y_{T_{n-1}+1},\cdots,Y_{T_{n-1}+X_n}=Y_{T_n}$ 人の家族を遺して消滅し，これらの子孫が第 $n+1$ 世代 $X_{n+1}$ の構成員となる．

$X_n\le0$ となった場合は以降も常に $X_m=0\;(m\ge n)$ が成り立ち，$0$ が吸収点となる．

$X_n,Y_n$ に負の整数値も許す場合は，2つの種族の個体数の差を考える場合などと解釈できる．

### 乱歩への埋め込み

初期分布を $\mu=\delta_1$ とすると，$T_0=X_0=1\;\as$．すると，任意の $m\in\N^+$ について，事象 $\Brace{X_m\ge1}$ の上では，
$$
T_{n}=1+\sum_{j=1}^{T_{n-1}}Y_j\quad(0\le n\le m+1)
$$ {#eq-Tn}
$$
\begin{align*}
    X_{n}&=T_{n}-T_{n-1}\\
    &=1+\sum_{j=1}^{T_{n-1}}Y_j-T_{n-1}\\
    &=1+\sum_{j=1}^{T_{n-1}}\wt{Y}_j\quad(0\le n\le m+1)
\end{align*}
$$ {#eq-Xn}
$$
\wt{Y}_j:=Y_j-1\quad(j\in\N^+)
$$
が成り立つ．

よって，絶滅しないという事象
$$
\bigcap_{m\in\N^+}\Brace{X_m\ge1}=\Brace{\lim_{n\to\infty}T_n=\infty}
$$
の上では，$X_0=1\;\as$ から始まる乱歩 (random walk)
$$
X_n=1+\wt{S}_{T_{n-1}}\quad(n\in\N)
$$
$$
\wt{S}_n:=\sum_{j=1}^n\wt{Y}_j\quad(n\in\N)
$$
と理解できる．

### Markov性

::: {#prop-Markov-property .callout-tip icon="false"}
## 命題^[[@Quine-Szczotka1994 p.1208] 命題1．] （Markov性）
$\{X_n\}_{n=0}^\infty\subset\L(\Om;\bZ)$ を，初期分布 $\mu=\delta_1$ と確率変数列 $\{Y_n\}_{n=1}^\infty\subset\L(\Om;\bZ)$ が定める分岐過程，$\F_n:=\sigma(X_k|k\in n+1)$ を $(X_n)$ が定める filtration とする．

1. 任意の $n\in\N^+$ について $\E_{\delta_1}[Y_{n+1}|Y_1,\cdots,Y_n]=a$ ならば，
$$
\E_{\delta_1}[X_{n+1}|\F_n]=aX_n^+,\quad n\in\N.
$$
2. 加えて $\V_{\delta_1}[Y_{n+1}|Y_1,\cdots,Y_n]=\sigma^2\;(n\in\N^+)$ ならば，
$$
\V_{\delta_1}[X_{n+1}|\F_n]=\sigma^2X_n^+,\quad n\in\N.
$$
3. さらに $\{Y_n\}_{n=1}^\infty$ が独立であるならば，$\{(X_n,T_{n-1})\}_{n=1}^\infty$ は Markov 連鎖であるが，$\{X_n\}_{n=0}^\infty$ は Markov 連鎖であるとは限らない．
4. さらに $\{Y_n\}_{n=1}^\infty$ が同分布であるならば，$\{X_n\}_{n=0}^\infty$ と $\{(X_n,T_{n-1})\}_{n=1}^\infty$ はいずれも時間的に一様な Markov 連鎖である．
:::

::: {.callout-note icon="false" title="証明" collapse="true"}
1. 任意の $\{r_k\}_{k=1}^n\subset\bZ$ について，等式
$$
\E_{\delta_1}[X_{n+1}|X_1=r_1,\cdots,X_n=r_n]=ar_n^+
$$
を示せば良い．$r_n\le0$ の場合は直ちに従うから，$r_n\ge1$ として考える．この下では変形 @eq-Tn を用いることが出来るから，
$$
\begin{align*}
    &\Brace{\forall_{j\in[n]}\;X_j=r_j}\\
    &=\Brace{\forall_{j\in[n-1]}\;T_j=i_j,X_n=r_n}\\
    &=\biggl\{\forall_{j\in[n-1]}\;\sum_{k=1}^{i_{j-1}}Y_k=i_j-1,\\
    &\qquad\qquad\qquad\sum_{j=i_{n-2}+1}^{i_{n-1}}Y_j=r_n\biggr\}\\
    &=:B_n
\end{align*}
$$
$$
i_j:=1+r_1+\cdots+r_j,\quad j\in[n-1],
$$
が成り立つから，仮定より
$$
\E_{\delta_1}[Y_{j}1_{B_n}]=a\P_{\delta_1}[B_n]\quad(j\ge i_{n-1}+1)
$$
であることに注意して，
$$
\begin{align*}
    &\E_{\delta_1}[X_{n+1}|X_1=r_1,\cdots,X_n=r_n]\\
    &\qquad\cdot\P_{\delta_1}[X_1=r_1,\cdots,X_n=r_n]\\
    &=\E_{\delta_1}[X_{n+1}1_{\Brace{X_1=r_1,\cdots,X_n=r_n}}]\\
    &=\E_{\delta_1}\Square{1_{B_n}\sum_{j=i_{n-1}+1}^{i_{n-1}+r_n}Y_j}\\
    &=ar_n\P_{\delta_1}[B_n]
\end{align*}
$$
を得る．両辺を $\P_{\delta_1}[B_n]$ で割ると，初めの式を得る．^[[条件付き期待値のアトムの上での性質](../Probability/条件付き期待値の問題.qmd#sec-atom) も参照．]

2. 同様にして，
$$
\begin{align*}
    &\V_{\delta_1}[X_{n+1}|X_1=r_1,\cdots,X_n=r_n]\\
    &=\E_{\delta_1}[X_{n+1}^2|B_n]-\E_{\delta_1}[X_{n+1}|B_n]^2\\
    &=\E_{\delta_1}\Square{\paren{\sum_{j=i_{n-1}+1}^{i_{n-1}+r_n}Y_j}^2\:\middle|\:B_n}\\
    &\qquad\qquad-\E_{\delta_1}\Square{\sum_{j=i_{n-1}+1}^{i_{n-1}+r_n}Y_j\:\middle|\:B_n}^2\\
    &=\sum_{j=i_{n-1}+1}^{i_{n-1}+r_n}\Paren{\E_{\delta_1}[Y_j^2|B_n]-\E_{\delta_1}[Y_j|B_n]^2}\\
    &=\sigma^2r_n^+.
\end{align*}
$$
ただし，途中の式変形で，任意の $i_{n-1}<j<k\le i_{n}$ について
$$
\begin{align*}
    \E_{\delta_1}[Y_jY_k|B_n]&=\E_{\delta_1}\SQuare{Y_j\E[Y_k|B_n,Y_j]\:\bigg|\:B_n}\\
    &=\E_{\delta_1}[Y_ja|B_n]\\
    &=a^2=\E_{\delta_1}[Y_j|B_n]\E_{\delta_1}[Y_k|B_n]
\end{align*}
$$
が成り立つことを用いた．

3. $(Y_k)_{k=1}^\infty$ が独立であるとき，$(X_k)_{k=0}^\infty$ も独立である．これより，任意の時点 $m_1<\cdots<m_k<n\in\N$ について，$T_{m_k-1}$ が与えられた下で，$X_k\;(k\ge m_k)$ と $\F_{m_k-1}$ とは独立である．よって特に，$(X_{m_k},T_{m_k-1})$ が与えられた下で，$(X_n,T_{n-1})$ と $(X_{m_i},T_{m_i-1})\;(i<k)$ とは独立である．よって，[条件付き独立性の性質](../Probability/条件付き期待値の問題.qmd#sec-conditional-independence) より
$$
\begin{align*}
    &\P_{\delta_1}\SQuare{(X_{n},T_{n-1})=(r_{n},s_{n-1})\:\bigg|\:\\
    &\qquad\qquad\forall_{i\in[k]}\;(X_{m_i},T_{m_i-1})=(r_{m_i},s_{m_i-1})}\\
    &=\P_{\delta_1}\SQuare{(X_n,T_{n-1})=(r_n,s_{n-1})\:\bigg|\:\\
    &\qquad\qquad(X_{m_k},T_{m_k-1})=(r_{m_k},s_{m_k-1})}
\end{align*}
$$
が成り立つ．

4. 
:::

### 生存確率

::: {#thm-survival .callout-tip icon="false"}
## 生存確率

$\{Z_n\}_{n=0}^\infty$ を BGW 過程で，$\P[Y_1\in 2]<1$ とする．このとき，$\mu:=\E[Y_1]\in[0,\infty]$ について，
^[[@Schinazi14-ClassicalProcesses p.19] 第2章定理1.1，[@Bhattacharya-Waymire2021 p.114] 定理9.1 など．]

1. $\mu\le1$ ならば，
$$
\P_1[\forall_{n\in\N}\;Z_n\ge1]=0.
$$

2. $\mu>1$ ならば，ある $q\in\cointerval{0,1}$ が存在して
$$
\P_1[\forall_{n\in\N}\;Z_n\ge1]=1-q>0
$$
を満たし，$q\in\cointerval{0,1}$ は $Y_1$ の確率母関数
$$
g(z):=\sum_{k=0}^\infty\P[Y_1=k]z^k
$$
に関する方程式 $g(z)=z$ の $\cointerval{0,1}$ 上でのただ一つの解である．
:::

すなわち，「未来永劫絶滅しない」確率が正であるかどうかは $Y_1$ の期待値 $\mu$ のみに依存するが，その確率 $1-q$ は $Y_1$ の分布によって定まる．
^[この $\mu$ を **基本再生産数** と呼ぶこともある [Wikipedia](https://en.wikipedia.org/wiki/Branching_process)．]

::: {.callout-note icon="false" title="証明" collapse="true"}

:::


## 連続分岐過程

### 定義

::: {#def-CBP .callout-tip icon="false"}
## 定義^[[@LeGall2016 p.177] を参考にした．] ：連続分岐過程

過程 $\{X_t\}_{t\in\R_+}\subset\L(\Om;\R_+)$ が（連続時間）**分岐過程** であるとは，
$$
Q_t(x,-)*Q_t(y,-)=Q_t(x+y,-)
$$
を満たす確率核の半群 $\{Q_t\}_{t\in\R_+}\subset B(\L_b(\R_+))$ が定めるMarkov過程であることをいう．
:::

たしかに $Q_t(0,-)=\delta_0\;(t\in\R_+)$ を満たす．

### 分岐性

::: {.callout-tip icon="false"}
## 命題^[[@LeGall2016 p.177] は branching property と呼んでいる．] （分岐性）

$\{X_t\},\{X'_t\}\subset\L(\Om;\R_+)$ を遷移半群 $\{Q_t\}\subset B(\L_b(\R_+))$ を共通とする，互いに独立な分岐過程とする．
このとき，$\{X_t+X'_t\}$ もやはり $\{Q_t\}$ を遷移半群に持つ分岐過程である．
:::

::: {.callout-note icon="false" title="証明" collapse="true"}
$X_0,X_0'$ の分布をそれぞれ $\nu,\nu'\in P(\R)$ とすると，
$X_0\indep X_0'$ より，
$X_0+X_0'\sim\nu*\nu'$ である．
すると，任意の $B\in\B(\R_+)$ に対して，
\begin{align*}
&\P[X_t+X_t'\in B]\\
&=\E[1_{\Brace{X_t+X_t'\in B}}]\\
&=\E\SQuare{\E[1_{\Brace{X_t\in B-x'}}|X_t'=x']}\\
&=\int_{\R_+}\int_{\R_+}Q_t(x,B-x')\nu(dx)\P^{X_t'}(dx')\\
&=\int_{\R_+}\int_{\R_+}\int_{\R_+}Q_t(x,B-x')\nu(dx)Q_t(y,dx')\nu'(dy)\\
&=\int_{\R_+}\int_{\R_+}Q_t(x+y,B)\nu(dx)\nu'(dy)\\
&=\int_{\R_+}\int_{\R_+}Q_t(z,B)(\nu*\nu')(dz).
\end{align*}
:::

::: {.callout-tip icon="false"}
## 補題^[[@Applebaum2009 p.22] 命題1.2.2．] （畳み込み測度に関する積分）

$f\in L(\R^d,\nu_1*\nu_2)$ について，
$$
\int_{\R^d}f(z)(\nu_1*\nu_2)(dz)=\int_{\R^d}f(x+y)\nu_1(dx)\nu_2(dy).
$$
:::

::: {.callout-note icon="false" title="証明" collapse="true"}
まず $f=1_B\;(B\in\B(\R^d))$ という定義関数の場合は，定義からすぐに従う．一般の $f$ については単関数近似による．
:::

### Feller性

::: {.callout-tip icon="false"}
## 命題^[[@LeGall2016 p.177] 命題6.22．] 

分岐過程 $\{X_t\}$ の遷移半群 $\{Q_t\}$ は

1. 任意 の$x>0,t>0$ について，$Q_t(x,\{0\})<1$．
2. $Q_t(x,-)\dto\delta_x(-)\;(t\to\infty)$．

を満たすとする．このとき，$(Q_t)$ はFeller半群である．
:::

::: {.callout-note icon="false" title="証明" collapse="true"}

:::