---
title: "粒子フィルターを用いたサンプリング"
author: "Hirofumi Shiba"
date: "12/14/2023"
date-modified: "12/14/2023"
categories: [Particles, Survey]
toc: true
number-sections: true
twitter-card: true
bibliography: ../../mathematics.bib
csl: ../../apa.csl
abstract-title: 概要
abstract: 粒子フィルターは30年前に「万能」非線型フィルタリング手法として開発されたが，近年その真の力が明らかになりつつある．相関を持つ粒子系によって分布を逐次的に近似することで，複雑な分布からでも効率的にサンプリング出来るまたとない手法であるようだ．本稿では現在までのサンプラーとしてのSMC手法に対する理解をまとめる．
crossref:
    sec-prefix: 節
    eq-prefix: 式
---

# テンパリングの歴史

{{< include ../../_preamble.qmd >}}

SMC の文脈で，目標の分布 $\pi_p\in\cP(E)$ が複雑であるとき，これに至る $\cP(E)$ 上の道
$$
[p]\ni n\mapsto\pi_n\in\cP(E)
$$
を通じて，より簡単な分布 $\pi_1,\pi_2,\cdots$ から逐次的にサンプリングをする，というアイデアを **調温 (tempering)** という（[粒子フィルターの稿](../2023/2023-11-25/ParticleFilter.qmd#sec-SMC-Samplers) も参照）．

この tempering という考え方は本質的に逐次的な発想を持っているが，元々は SMC の文脈とは全く独立に，MCMC を多峰性を持つ複雑な分布に対しても使えるように拡張する研究で提案された．

まずはその歴史を概観する．

## MC^3^ / 並行テンパリング

まず最初の発想は，目標分布 $\pi_p$ が多峰性をもち，MCMC がうまく峰を見つけられず，収束が遅くなる問題を解決する中で生まれた．

そこで，峰の間で遷移する動きを，不変分布を変えないように MCMC に加えることで，収束性が改善できないかと考えられた．

峰を全て特定し，正しいステップサイズを選択するために，複数の MCMC を同時に走らせる **MC^3^** (Metropolis-Coupled MCMC) という手法が [@Geyer1991] により提案された．

これは $\pi_1\otimes\cdots\otimes\pi_p$ を目標分布として独立な MCMC を実行し，時折 Metropolis 核の提案に従って不変分布を変えないようにそれらの位置を交換するという手法である．

この手法は **parallel tempering**^[[@Chopin+2023] でも [@Geyer1991] を引用して PT と呼んでいる．] または [レプリカ交換法](https://ja.wikipedia.org/wiki/%E3%83%AC%E3%83%97%E3%83%AA%E3%82%AB%E4%BA%A4%E6%8F%9B%E6%B3%95)，さらには population-based MCMC^[[@Jasra+2007] など．] とも呼ばれる．

しかしながら，交換の棄却率が高まりすぎないようにするためには隣り合う $\pi_n,\pi_{n+1}$ を十分近く取る必要があり，すると必要な MCMC 鎖の数が極めて大きくなってしまう．^[[@Behrens+2012 p.66] も参照．]

## 擬似テンパリング

[焼きなまし法](https://ja.wikipedia.org/wiki/%E7%84%BC%E3%81%8D%E3%81%AA%E3%81%BE%E3%81%97%E6%B3%95)（または擬似アニーリング） [@Kirkpartick+1983] の改良として最適化の文脈で提案されたのが **焼き戻し法**，または **擬似テンパリング** (simulated tempering) [@Marinari-Parisi1992] である．

これは状態空間を $E\times [p]$ に拡大し，^[記法 $[p]=\{1,\cdots,p\}$ は [本サイトの数学記法一覧](../2023/2023-12-12/Notations.qmd#sec-numbers) を参照] その上の標的分布を
$$
X|N=n\sim\pi_n
$$
を満たすようにし，$N|X$ は適宜架橋分布 $\{\pi_n\}$ を往来するよう設計することで，MC^3^ が $p$ 本の MCMC を用いて実現していたことを，$E\times [p]$ 上の MCMC 1つで効率的に実行する．

また，MCMC の収束を大幅に加速する手法としても，遺伝学における複雑な事後分布からのサンプリングへの応用を念頭に独立に提案された [@Geyer-Thompson1995]．

## テンパリング遷移 [@Neal1996]

**tempered transitions** では，架橋列 $\{\pi_n\}$ をそれぞれの $\pi_n$ を不変分布に持つ Markov 核を通じて１往復して探索し，その結果を元に $\pi_p$ を効率的に探索するような MCMC の提案を構成する．^[[@Behrens+2012] も参照．]

また，
$$
\pi_n(x)\propt\pi_0(x)e^{-\beta_nh(x)}
$$
と表せる際，架橋分布 $\{\pi_n\}$ は温度比 $\beta_n/\beta_{n+1}$ が一定になるように **幾何的に** 取ることを提案しており，現在でも一般的な基準であるようである [@Behrens+2012]．

## 焼きなまし重点サンプリング [@Neal2001]

ここで初めて SMC の文脈にもテンパリングが輸入された．^[[@Chopin-Papaspiliopoulos20-SMC p.33] で，SMC を調音に初めて応用した論文として紹介されている．] [@Neal2001] は重点サンプリングによってあらゆる温度 $\{\pi_n\}$ からの提案を効率的に採用する方法を模索した．

テンパリング遷移の後半のアルゴリズムを発展させた形である．

## 重点テンパリング [@Gramacy+2010]

こちらは擬似テンパリングを基にし，他の温度からの提案を保持しておく機構を提案している．

## 荷重を保つ擬似テンパリング [@Tawn+2020]

## 多峰性の最適化に基づく対処

目標分布の峰を特定するタスクを MCMC から分離して，[BFGS 法](https://ja.wikipedia.org/wiki/BFGS%E6%B3%95) に基づく最適化法によって先に解いてしまう手法が [@Pompe+2020] によって提案されている．

これにより探索した峰の全体を $\cI:=\{1,\cdots,I\}$ に格納し，拡大した状態空間 $E\times\cI$ 上で $\wt{\pi}$ を対象とした MCMC を実行するが，この $\wt{\pi}$ をさらに適応的に更新する Auxiliary Variable Adaptive MCMC を提案している．