---
title: "俺の人生を変えたものTop5"
author: "Hirofumi Shiba"
date: "11/4/2023"
categories: [News, Life]
abstract: 10月以前と10月以降で過ごし方が大きく変わった その要因のうち最も大きいと思われるもの５つを紹介
abstract-title: 概要
toc: true
number-sections: false
---

## 何が起こったか？

９月の京都学会→台湾研修（３週間）から帰ってきて，最初に手をつけたのが家の片付けであった．不要な本は全て売り（段ボール5箱），粗大ゴミを8000円分捨て，古着も処分した．特に，半ば物置と化していた和室をリフォームし，自分の書斎として使えるようにした．結果，11月を迎えた今，8月までの生活に比べて，

- 3時に寝て1時に起きるのもザラにあった生活が，12時には寝て10時には活動を始めているようになった．特に，**午前中からだらけることなく研究に従事することができるようになった**．
- 1日2食（昼に当たる時間と晩）でも胃もたれしたり，冷たいものを飲み過ぎて戻してしまうことがしばしばあった生活が，1日3食がっつり食べるようになった．それで居て胃もたれもなく，冷たい飲み物が苦手ということも無くなった．
- 急に立ち上がったり，電車から降りて階段を登ったりするタイミングで目の前が見えなくなるほどの立ちくらみがすることがよくあった（週の2,3回ほど）が，今では1度もなければ前兆もない．
- 以前は週1回ランニングに出れば良い方だったが，今では外出しない日は殆どランニングに出ている．
- 結果，「やられっぱなしにはならず耐える」ことが人生の中心になっていたが，いまでは「自分の手で人生を変えていける」という感覚を得ることが出来ている．

正直これほどの変化が起こるとは思わなかったし，すでに２週間近く全くブレずに持続している．自分のこれまでの人生から見ても，これからを思っても，これほど効果覿面な投資もなかったと思うので，10月に導入して良かったものベスト5を書きおこうと思う．

## １．[スタンディングデスク](https://www.amazon.co.jp/gp/product/B092CVMP7K/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1)の導入^[FlexiSpot 電動昇降式デスクEF1]

```{=html}
<iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//rcm-fe.amazon-adsystem.com/e/cm?lt1=_blank&bc1=FFFFFF&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=162348-22&language=ja_JP&o=9&p=8&l=as4&m=amazon&f=ifr&ref=as_ss_li_til&asins=B092CVMP7K&linkId=8c67cac96fbb96fd64373cde6f8fc733"></iframe>
```

これが俺の生活を根底から変えてしまった．

１週間ほどかけて物置状態の和室にスタンディングデスクを導入し，書斎として使えるようにした．すると，朝ご飯から研究が，晩御飯から読書が，シームレスに繋がるようになった．特に何もせずにだらだらしていた時間がまるごと消えてしまった．外から家に帰ってきて，風呂に入るわけでもなくソファに座ってだらだらしているようなことも減った．

あとから思えば，朝起きて研究に取りかかれない理由のうち殆どの部分が「日当たりのない部屋で」「座るのが嫌だ」の２つの事項に帰することが出来たのだ．私の部屋は北向きで窓はあれど殆ど陽は入らず，一方で和室はリビングに繋がっており，大きな窓から朝日が差し込んでくる．午前中に自宅で勉強する行為は人生全体で見て殆ど初めてのことだったが，心の底から幸せだと感じた．

また，睡眠の改善は，後述の睡眠グッズの影響も大きいだろうが，朝日当たりの良い場所で研究・読書をすることで，午前中から太陽の光を浴びるようになったことによる影響も大きいだろうと思われる．

さらに，筆者はオンライン授業を聞くのが極めて苦手で，全く集中できない上に他のことをがっつりやることも出来ない，大きなストレス源であったが，スタンディングデスクであると自然な形で聴くことができる．

このような例もあるのだ．「ダラダラしてしまうのは自分が臆病だからだ」とか，「朝に弱いのだ」などと早合点せず，もっと早くスタンディングデスクを導入して，自宅内にも２箇所勉強できる場所を用意しておけば良かったと今では思う．疲れたら立って／座ってみるだけでギアが変わるように集中力が持続する．スタンディングデスクにステッパーを組み合わせて，歩きながら作業できるようにすると雑務にもストレスが溜まらない．

## ２．[２段ハンガーラック](https://www.luminous-club.com/products/detail/product_1324/)^[【ポール径25mm】 エリソン ハンガーラック ワードローブ [ホワイト] 幅110cm 3段 幅111×奥行41×高さ220cm EHE11213WH [EHE11183WH ADD-P45WH HP-110WH] ]

```{=html}
<a class="embedly-card" href="https://www.luminous-club.com/products/detail/product_1324/">【ポール径25mm】 エリソン ハンガーラック ワードローブ [ホワイト] 幅110cm 3段 幅111×奥行41×高さ220cm EHE11213WH [EHE11183WH ADD-P45WH HP-110WH]| スチールラック・メタル製ラック通販のルミナスクラブ</a><script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
```

和室には他に本棚，ベッドと，この２段ハンガーラックが用意してある．縦方向に長い(220cmある)ために場所を取らないが，多くの衣服を収納できるし，何より取り出しやすい．これで散らかしがちだった服を一箇所に整理することが出来た．

## ３．[高反発マットレス](https://www.amazon.co.jp/gp/product/B07PXZQHBV/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&th=1)^[GOKUMIN 高反発マットレス]

```{=html}
<iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//rcm-fe.amazon-adsystem.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=162348-22&language=ja_JP&o=9&p=8&l=as4&m=amazon&f=ifr&ref=as_ss_li_til&asins=B07PXZQHBV&linkId=ee09b3c9ebe8b09ed10e19bfef0590d2"></iframe>
```

これも全く予想外だった．マットレスを変えることが睡眠に影響を与えるとも思っていなかったし，「痩せている場合は低反発」というネット上の文句がやけに腑に落ちる部分もあったため，「高反発で本当に良かったのか？」と買ってからも逡巡していたが，「体圧分散マットレス」であれば高反発だろうと身体を痛めることはない．さらに筆者の場合は，高反発マットレスで寝起きした方が，身体が疲れていないと感じる．

## ４．[IoTシーリングライト](https://beaubelle.shop/shopdetail/000000001967/)^[BeauBelle IoT シーリングライト Flavia bbs-095t]

<iframe src="https://beaubelle.shop/shopdetail/000000001967/" width="100%" height="300">
<p>Your browser does not support iframes.</p>
</iframe>

部屋のライトが音を出すようになったことがきっかけで買い替えたが，このライトは色の調整も可能でありながら，「朝９時に点灯させる」といったようなスケジューリングも可能である．

実際明るくなったことで起きることはなかったが，起きた場合に二度寝することが減った．それも，不快感も特に強くなく，勝手に身体にエネルギーが起きてくれるのである．

また，集中する際は白色光で，寝る前は暖色で光の強さも弱めていくことで，自然な眠気を誘うこともできる．

## ５．1日13時間は水以外口に入れない時間を作る

これが今回唯一の自助努力となったが，最大の気づきでもあった．夜寝る前にラーメンや甘いものをつい食べがちになっていたが，その代わりに日中の摂取カロリーを増やし，（翌朝10時に朝ご飯を食べるとするならば）９時以降は水以外，口に何も入れないようにする．大事なのはカロリーを取らない点である．人体は，口腔内にカロリーを検出するだけで，それに合わせて胃も消化の必要を見越して胃液を分泌し，調和を図るようになっている．^[関連する話は[このブログ](https://yuchrszk.blogspot.com/2021/01/blog-post_21.html)などにも紹介されている．]

思い返せば，小学校低学年までは胃腸が弱く，体調を崩した際は必ず嘔吐を繰り返した．その際に学んだ絶対の規則は「一度吐いたら６時間は何も食べないし何も飲まない」を徹底することであった．疲れさせてしまったら休ませることが人体の鉄則である．

筆者の場合は夜はしっかり半日以上胃腸を休ませることにより，日中にフルパワーで活動させることができ，夜中にお腹が空くということは減ったのであった．


正直、いまの自分は、昔の自分がなりたかった自分の最新バージョンに他ならない。己に恥じない毎日を過ごしたいと思う。