---
title: "粒子フィルターとは何か | About Particle Filters（執筆中）"
author: "Hirofumi Shiba"
date: "11/25/2023"
categories: [Particles]
toc: true
number-sections: true
website:
    twitter-card: true
bibliography: bib.bib
csl: apa.csl
abstract-title: 概要
abstract: 粒子フィルターは今年で30周年を迎える「万能」非線型フィルタリング手法である．相関を持つ粒子系によって分布を逐次的に近似する遺伝的アルゴリズムであり，多くの科学分野にまたがる応用を持つと同時に，数理的対象としても豊かな構造を持つ．その概要と今後の研究方向を紹介する．
---

## 背景

### フィルタリング（濾波）問題とは？

フィルタ（濾波器）の第一義は，液体から不純物を取り除くための装置である．そのアナロジーで「フィルタリング問題」と言った場合は，信号処理の意味で電圧や電波の信号を「濾過」してノイズを除去し本当に欲しい部分を純粋化する営みのことを指す．特に，凡ゆる通信機器において装置の熱運動によるノイズが入ることは避けられぬ自然の摂理である．^[[@Anderson-Moore1979-OptimalFiltering] 第1.1節．]

従ってGaussが天体観測から「誤差論」として統計的推定理論を創始したように，通信と制御の分野では「時々刻々と受信するデータから時々刻々と変化する信号をどのようにうまく濾波するか」という独自の課題から，独自の理論が発展していった．特に，デジタル回路がない時代では，「どのような電気回路のシステムとして濾波機をデザインすれば良いか？」という電気工学的な回路設計の問題としての側面も大きかった．

フィルタリングの問題を統計的技術で解くための理論が，まず離散時間の場合が [@Kolmogorov1941]，続いて連続時間の場合が [@Wiener1949] によって模索された．^[[@Bain-Crisan2009-StochasticFiltering] 1.3節．] しかし，このKolmogorov-Wiener理論では「信号とノイズの過程が定常である」という仮定を置いており，これが広い応用を阻んでいた．当時の技術（抵抗器やコンデンサーなど）で実装出来る範囲という制約がある以上，仕方ないことでもあったため，更なる理論的発展はデジタル技術の登場を待つことになる．

計算機というデジタル技術が使われるようになると，「フィルタ（濾波器）」はアナログデジタル変換器，レジスタ，メモリ，マイクロプロセッサから構成されるようになり，物理的な姿は全く変わってしまった．その中で [@Kalman1960] が，定常性の仮定が満たされない場合でも使えるアルゴリズムを提案すると，すぐにApollo計画に導入されるに止まらず，NASAのスペースシャトル，海軍の潜水艦などにも応用されていった．^[[@DelMoral-Penev2014] 参照．また，[@Kalman1960] からちょうど10周年の文献 [@有本卓1970] に当時の雰囲気も感じさせる良いサーベイがある．]

こうして「フィルタ（濾波器）」の語は，「水を濾過する如く電圧情報のノイズを除去する機器」という類比から，デジタル技術の出現により更なる一段階の抽象化を受けて物理的実体も失い，「ノイズを除去してメッセージ部分をなるべく正確に推定するアルゴリズム」という完全に数学的で抽象的な存在として研究が進められていくことになる．

このKalman filterは素晴らしかった．だが，モデルが線型かつ正規である場合にしか使えない．そこで，計算機や情報通信技術の発展と共に複雑化していくシステム・データに併せて，様々なフィルターが考案されていく必要があるのである．これが統計計算の時代である．

### 粒子フィルターの発明

線型性や正規性の仮定を一才必要としない濾波アルゴリズムとして，[@Gordon+1993] がbootstrap filterという名前で発表し，角度観測のみを用いた物体追跡の問題への応用を付した．この角度情報のみから物体を追跡するという問題は古典的な非線型濾波問題で，従来の拡張Kalman filterの方法では精度が全く伸びず，これに比べてbootstrap filterでは圧倒的に性能が改善したのであった．リサンプリングは多項リサンプリングを採用しており，極めて実装が簡単という点も多くの応用を生んだ理由である．^[[@Creal2011] p.256．]

なお，北川源四郎も同年（1993年）のカンファレンスでMonte Carlo filterの名前で同様のアルゴリズムを発表している．そのジャーナル版は [@北川1996]．^[[Del MoralのWebサイト](https://people.bordeaux.inria.fr/pierre.delmoral/simulinks.html)も歴史的背景に詳しい．]

### 粒子フィルターの応用

まず，[@Gordon+1993] による粒子フィルターの考案は，防衛，特に物体追跡への応用が念頭にあり，これを扱った一冊の本もある [@Ristic+2004]．

これに関連して，ロボティクス，HCI (Human-Computer Interaction) 分野への応用もなされている[@岡2005]．

ファイナンスで扱う時系列は非線型性・非正規性を示すと同時にデータ数も多い．逐次推定のステップ数が増えようとも誤差が蓄積しない粒子フィルターが見事に推定を実行する．^[ファイナンスにおける確率ボラティリティモデルなどの例が挙げられている [@Creal2011] p.256．]

加えて，マクロ経済学の分野で[動学的確率的一般均衡モデル](https://en.wikipedia.org/wiki/Dynamic_stochastic_general_equilibrium)の推定にも応用されている．このモデルは，非線型なミクロ経済学的モデルの上に構築されたモデルで，非線型な1次条件を持つ．^[[@Creal2011] p.246 に，粒子フィルターの経済学での応用が増えたきっかけがFernández-Villaverde and Rubio-Ramírez (2005, 2007) によるDSGEモデルの推定への応用だとしている．[@矢野2014] 実物景気循環モデル (Real Business Cycles
Model) への応用を解説している．]

### 粒子フィルターの一般の推定問題への応用

こうして，粒子フィルターは濾波問題の文脈で発明されたMonte Carlo法であるが，濾波問題に限らず，多くの逐次推定問題，更には（逐次的構造を持たない）一般の推定問題にも応用できる．この観点から，粒子フィルターは「逐次Monte Carlo法（Sequential Monte Carlo methods 略して **SMC** ）」ともいう．^[[@Chopin-Papaspiliopoulos20-SMC] 第3章参照．]

逐次的ではない通常の設定，いわば「静的」な設定の下でのBayes推論にSMCを用いる方法は [@Chopin2002] が草分け的な仕事をした．この枠組みでは，Bayes事後分布 $\pi(\theta|y_1,\cdots,y_N)$ の近似において，途中の $\pi(\theta|y_1,\cdots,y_n)$ を経由して逐次的に近似することが，自然な計算コスト削減法として理解できる．

### 粒子フィルターの欠点

粒子フィルターは高い汎用性の代償として，計算量が多いことを欠点に持つ．従って，粒子フィルターは，他の手法が実行不可能なほどの非線型性・非正規性を示す問題に（のみ）用いるべきというものである．が，CPUや並列計算の発展により，その問題点も形骸化してきてると言える．^[[@矢野2014] p.190，[@Ristic+2004] 前文 p.xi．]

## 粒子フィルター入門

### 重点サンプリング

### 逐次重点サンプリングの修正としての粒子フィルター

逐次重点サンプリングは，次元が上がっていくにつれて分散が指数増大するという致命的欠点がある．^[[@Chopin-Papaspiliopoulos20-SMC] 第8.7節 p.95，[@Creal2011] p.253．] そこで，「リサンプリング」（「選択（セレクション）」ともいう）という新たな機構を各段階に取り入れることを考える．この機構により，次元の呪いを克服し，推定精度が保たれるのであるが，一方で粒子の間に相関が導入されるために，理論的解析を困難にする．この点から粒子フィルターは「（平均場）相関粒子法」「遺伝型粒子フィルター」^[[@DelMoral-Horton2023-EnKF] など] ともいう．^[呼び方については[@DelMoral13-MeanFieldSimulation]と[この記事](https://162348.github.io/posts/2023-11-9/) も参照．]

## 技術的障壁と今後の研究

粒子フィルターの応用には次の点の研究が肝要である．^[[@Ristic+2004] Epilogueに次の言葉がある
> "The key factors for a successful application of particle filters in practice are therefore a good choice of the importance density and Rao-Blackwellization if possible.""
]

### 提案分布の取り方

### 部分的な線型構造の利用

周辺化粒子フィルター，またはRao-Blackwellized particle filterとも呼ばれる方法である．これは多くの場面で，仮定されている状態空間モデルが部分的に線型である場合に，線型の部分をKalmanフィルターによって正確に解き，残った部分のみを粒子フィルターで解くことで，精度の向上とアルゴリズムの効率化を図る方法である．

[@Ristic+2004 p.287] では，探知前追跡 (track-before-detect) の問題^[探知前追跡とは，信号が弱い，またはノイズが強い環境下において，信頼のおける初期信号を頼りにせずとも，物体追跡を実行するための手法．]において，周辺化粒子フィルタが，必要な粒子数を大きく削減してくれることを紹介している．

その他にも，問題毎の特有の構造を利用して計算量を削減・パフォーマンスを最適化することは重要な営みである．

### 粒子数に関する漸近論

目前の問題を，所与の精度で解くために必要な粒子数は幾ばくか？という問題は実用上も有益だと思われる．^[[@Ristic+2004 p.288] に示唆されている．]