---
title: "数学者のための確率的グラフィカルモデル概観"
author: "Draft Draft"
date: 12/20/2023
date-modified: 1/9/2024
categories: [Particles, Math Notes]
toc: true
number-sections: true
code-block-bg: true
code-block-border-left: "#31BAE9"
code-overflow: wrap
code-fold: true
bibliography: ../../../mathematics.bib
csl: ../../../apa.csl
crossref:
    sec-prefix: 節
    eq-prefix: 式
    def-prefix: 定義
    def-title: 定義
    thm-prefix: 定理
    thm-title: 定理
abstract-title: 概要
abstract: 数学者のために，PGMによるデータ解析が何をやっているのかを抽象的に説明する．
---

[決定木](../../2023/数理法務/%E6%B3%95%E5%BE%8B%E5%AE%B6%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E7%B5%B1%E8%A8%88%E6%95%B0%E7%90%863.qmd)，[状態空間モデル](../../2023/Surveys/SSM.qmd)，ベイジアンネットワークはいずれもグラフィカルモデルの例である．^[[@Taroni+2014 p.35]，[@Sucar2021 p.x]]

[@Koller-Friedman2009], [@Pearl84-Heuristics], [@Pearl88-IntelligentSystem], [@Wainwright-Jordan2008]

## 歴史と導入

グラフィカルモデルとは，条件付き独立性のグラフ表現である．

高次元分布において，成分間の独立性をグラフを用いて表現しようという発想は，その計算機との親和性が見つかる前に，種々の科学分野で試みられていた．^[[@Koller-Friedman2009 pp.12-14] 1.4節．]

* [@Gibbs1902] が相関粒子系の分布をグラフで表現した．
* [@Wright1918] は骨格測定のデータを用いた因子分析で，（遺伝的な意味での）依存関係を，パス図と呼ばれる有向グラフを用いて表した．
* [@Wold1954] とその教え子との [@Joreskog-Wold1981]，さらに [@Blalock1971] が社会学において，因果をグラフを用いて表す手法を普及させた．
* その後 [@Wold-Strotz60] は [@Pearl09-Causality] などの do-calculus に繋がっている．
* 統計学でも [@Bartlett1935] が分割表分析において変数同士の相関の研究をしたが，界隈が本格的に受け入れたのはやっと 1960 年代以降である．

人工知能分野が確率的手法を採用したのは，エキスパートシステムの構築が志向された 1960 年代であった．医療診断や油源探索における専門家に匹敵する判断力を持つアルゴリズムを構築する途上で，不確実性の度合いの定量化が必要となり，naive Bayes model と呼ばれる確率的モデルが採用された．特に [@Dombal+1972] は限られた分野であるが人間を凌駕する診断正答率を示した．

だがこの確率的アプローチはその後長い冬の時代を経験することとなり，エキスパートシステムも production rule framework やファジー論理など，他のアーキテクチャが試みられるようになっていった．

これを打開したのが

1. [@Pearl88-IntelligentSystem] による Bayesian network framework と，[@Lauritzen-Spiegelhalter1988] による効率的な推論手法という理論的発展．
2. [@Heckerman+1992], [@Heckerman-Nathwani1992] が Bayesian network を病理学標本に応用して大きな成功を挙げたこと．

の2つである．これにより，確率的グラフィカルモデル，また一般に確率的アプローチが広く受け入れられるようになった．

## 表現

### Bayesian Network

### Markov Network

