---
title: "About Mental Health Issues"
author: "Hirofumi Shiba"
date: "12/4/2023"
categories: [Life]
toc: true
toc-expand: true
number-sections: false
bibliography: ../../mathematics.bib
csl: ../../apa.csl
abstract-title: 対象
abstract: メンタルヘルスの世界を知らざるを得なくなった人と，「自分は今後どうなるのか」という不安に苛まれている人へ．
---

メンタルヘルスを損なってしまったとき，「もう二度と以前の状態には戻れないのではないか」という絶望が最初に付きまとうと思う．**結論から言うと，絶対戻れる**．**だが，今じゃない**．

そもそも，メンタルヘルスの問題は「病気」と「健常」の境界が曖昧になってしまったと感じるだろう．治ったと思ったら治っていなくて，「一体いつまで続くのだろう」「以前は『正常』だと思っていた状態に，二度と戻れないのではないか？」という反芻思考が心を襲うだろう．

**それは当然である**．あなたはまだ治っていない．そもそも普通の風邪だって，「病気」と「健常」の境界など無いに等しい．熱があると社会は許してくれるが，熱とはそもそもウイルス・病原菌の感染から身体を守るための「正常な」反応である．身体に標準に組み込まれた防衛機制の想定された挙動の範囲内である．風邪は感染の可能性もあるから社会の方から休養を許してくれるのである．

**メンタルヘルスの問題だって，（一定範囲では）身体の正常な反応である**．だが，あなたは休養を取っただろうか？社会は多くの場合理解を示さない．その中で自分の身体を守る対策を毅然と断行しただろうか？^[当然，「メンタルヘルスは自分で守らなきゃいけない」という自衛に頼った構造になっている現代社会は，少しずつ変わっていくし，変わるべきだろう．だがいつの時代も自衛は大事だ．] もし，休み休み前に進むことが出来る環境だったならば，あなたはメンタルヘルスに悩んでいなかっただろうし，「正常」と「異常」の境界にも悩んでいなかっただろう．食事が喉を通らない，眠れない，些細な刺激が絶大なストレスになる，胃を痛める，これらの反応は適度な休養が取れていて心に弾力がある状態ならば，「大変な時期もあったが，それを乗り越えて，私は大きく成功できた」という美談で終われる「正常」な心の反応である．風邪も流行感冒もそうだろう．だが，休まないまま通ろうとすると，本当に「異常」になる．風邪を治さずに活動し続けて，拗らせた経験はあるか？インフルになっても普段の生活を続けたことはあるか？あなたはそれをやろうとしていたのである．身体が想定外の挙動を起こしがちになるのも仕方ないというものである．

だから，**あなたはそもそも治っていないのである**．風邪の原因はウイルスであり，あなたは休養をして免疫機構に対処してもらう，そうして来ただろう．一方で心の病の原因は，人間関係と期待，社会的なプレッシャーがある立場，休養を許さないストレスフルな環境，あなたの場合はどれに該当するかわからないが，ほとんどの場合すぐには休養が取れない．だからこそあなたはメンタルヘルスを病んでいるのだろう．つまり，普段通りだと思っているあなたの心の風邪はまだ絶賛発熱中である．それどころか，何ヶ月も発熱したままである．早い段階で自分の免疫に治してもらわなければ，薬などの外部からの補助が必要になる（それでも治るが）．

「一体いつまで続くのだろう？」「もう二度と正常の状態に戻れないのではないか？」という不安が的外れであることがわかっていただけただろうか？まずはストレスの原因がない状態に生活を持っていき，心の免疫が働く状態を整えよう．これには時間がかかるだろう．信頼できる人以外との関係を一度整理する必要があるし，ほとんどの場合金策の問題ですぐには十分に休めないかもしれない．さらに悪いことに「ストレスのない状態に生活を変える」こと自体が，あなたのアイデンティティの死を意味するかも知れない．だからあなたはボロボロになってこれ以上前に進めなくなるまで頑張ってしまったのだろう．だが，メンタルヘルスに変調をきたしてしまった場合，そのアイデンティティは少し修正せざるを得ない．ここはどうしても残酷な部分であるが，仕方のないことである．だが，考えてみてほしい．身体を強く病んでしまった人で，ここに深く絶望する人は少ない．

ストレスの原因のない状態に持っていってから，それでも治らないならばしっかり専門家に頼り，通院して服薬をすれば，絶対に治るし，元の「正常」な状態に戻る．そのときには，あなたは「正常」と「病気」との区別について，より深い理解を得ていることだろう．私がそうだった．

## 本当に？あなたの運が良かっただけでは？と思う人へ

「もう二度と治らないのだ」「脳の構造が変わってしまう」などと言う体験者の言葉は意外と多い．だが，これは「自分はメンタルヘルスの大きな病を抱えており，休養が必要である」ということを周囲に理解してもらうには多少荒技が必要であった人が，自身の休養を守るために使う表現としてもよく使われることに注意していただきたい．**メンタルヘルスの病は，「一刻も早く治したい」と思っている人が全てではないことに注意する必要がある**．彼らの言動に，あなたが傷ついたり，絶望する必要はない．治したいと思っているならば，専門家に相談すれば治る．度合いによってかかる時間は変わるかもしれないが，あなたが満足のいくレベルまで，治る．今すぐクリニックを検索して予約の電話を入れよう．良いクリニックなら1ヶ月前後待つことになるから，とりあえず予約だけして後からそれで良かったのか考えれば良い．運悪く，合うクリニックがすぐには見つからない可能性もあるが，とにかくトライし続けるのだ．正しい手を掴めば絶対に治るから．