---
title: "確率核という概念"
subtitle: "データ解析の営みを確率空間の圏上で理解する"
author: "司馬博文"
image: Images/P.svg
date: 3/24/2024
date-modified: 8/15/2024
categories: [Probability, Kernel, Process, Functional Analysis, P(X)]
bibliography: 
    - ../../../assets/2023.bib
    - ../../../assets/2024.bib
    - ../../../assets/2025.bib
csl: ../../../assets/apalike.csl
abstract-title: 概要
abstract: 確率核という概念は現状あまりポピュラーではないと思われるが，数学的にいえば，Markov 過程論，確率論，さらにはデータ解析の中心に据えられるべき中心概念であると言えるかもしれない．例えば，カーネル法とは確率核に沿った埋め込みである．MCMC の性質も，本質的に確率核の性質が決定する．また確率核は，確率空間の圏の射となる．<br>このように，多くのデータ解析手法の中核に位置する数学的本体たる「確率核」への入門を目指すのが本記事である．
listing: 
    -   id: kernel-listing
        type: grid
        sort: false
        contents:
            - "../Kernels/HierarchicalModel.qmd"
            - "../Kernels/Kernel.qmd"
            - "../../2023/KernelMethods/KernelMethods4Mathematicians.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
---

{{< include ../../../assets/_preamble.qmd >}}

## はじめに

> 確率核 $P$ こそが Markov 連鎖の数学的本体である．

{{< tweet sp_monte_carlo 1758594237782692187 >}}

### 確率核：Markov 連鎖の本体

$(E,\cE),(F,\cF)$ を可測空間とする．確率核とは関数 $E\to\cP(F)$ のことをいう（ほとんどの場合可測になる：第 [-@sec-kernel-as-function] 節）．ただし，$\cP(F)$ は $F$ 上の確率測度全体の集合とした．

多くの場合，$\cP(E)$ は Banach 空間内の $w^*$-閉な凸集合になっている．このことが，最終的に [カーネルトリック](../../2023/KernelMethods/KernelMethods4Mathematicians.qmd#sec-Kernel) の基となる．

$E$ 上の確率核 $P:E\to\cP(E)$ が定まると，任意のスタート地点 $x\in E$ に対して，これを起点とする Markov 連鎖 $\{X^x_n\}_{n=0}^\infty\subset\L(\Om)$ が構成できる．

ここで，確率変数 $X^x_n$ を定義するために謎の標本空間 $(\Om,\F,\P)$ が出てきた．これは数学的に確率変数を定義するために必要であるが，ご存知の通り $\Om$ の性質が問題になる場面はほとんどない，純粋に形式的な存在である．一方で数学的な本体は核 $P$ なのである．まさに「核」．

Markov 連鎖の実体は分布であるが，これは確率核 $P$ を用いて $\{(P^*)^n\delta_x\}_{n=0}^\infty\subset\cP(E)$ と表せる：
$$
X^x_n\sim (P^*)^n\delta_x,\qquad n\in\N.
$$
$(P^*)^n$ は第 [-@sec-kernel-action] 節参照．$\delta_x$ は $x\in E$ 上のデルタ測度である．

### 次元を上げてランダムネスを消す

ここで，$X^x_n$ 自体は確率変数であり，ランダムな存在である．これを捉えるために測度論が必要だったのである．特に確率過程の議論に必要な測度論は大変込み入っている．

しかし分布 $(P^*)^n\delta_x$ は空間 $\cP(E)$ 上の点であり，全体として $\cP(E)$ 上の（確定的な）力学系を定めている．**ランダムネスが消えている**のである！

ただしその代わり，例え $E=\R^d$ であっても，$\cP(E)$ は無限次元空間になっている．

Newton 力学が扱う運動は結局，$\R^n$ など有限次元空間上の幾何学に帰着する．^[Hamilton の定式化などを通じて，接束 $T(\R^n)$ または余接束 $T^*(\R^n)$ 上の幾何学に変換されるが，やはり有限次元である．]

[**一方で確率的な系は，確率核 $P$ を通じて，無限次元空間 $\cP(E)$ 上の幾何学に帰着するのである**]{.underline}．時代は情報幾何学である．^[ちょうど，非線型力学系において，Koopman　作用素を導入することで，扱う空間が無限次元になってしまう代わりに，ダイナミクスの線型性を回復することに似ている．非線型力学系を扱うにあたって，非線型性の除去が肝心であるように，確率的な系の分析において，ランダムネスを取り除くことが重要であったようだ．]

### $\cP(E)$ 上の幾何学を構築する試み

$\cP(E)$ が無限次元と言えど，一度同じく「力学系」に帰着してしまえば，その数学的な大枠は共通するはずである．

まず，物理学で重要な幾何学的原理として，変分原理がある．これは，空間上に自由エネルギーや作用などの汎函数を定義して，これを最小化するものとしてダイナミクスを理解する方法である．

実際，モンテカルロ法が定める $\cP(E)$ 上の力学系を，勾配流として理解することが進んでいる [@Jordan-Kinderlehrer-Otto1998], [@Chopin+2023]．

最適輸送の名前の下で，$\cP(E)$ の幾何学を考慮したサンプリング法の開発も進んでいる．

エルゴード理論において，多くの基本的な力学系（減衰振動など）は指数収束をするが，同様にして多くの基本的な Markov 核も指数収束をする．

<!-- これが $x\in E$ に依らずに同じ点に近づくことを **忘却性** (loss of memory)，近づく先がちゃんと確率測度になることを **エルゴード性** (ergodicity) という． -->

### 確率核が数学的に重要な理由

確率核を確率空間の射とみる見方（第 [-@sec-def-kernel] 節）が急速に浸透しており，これは [Markov 圏](../../2023/Probability/MarkovCategory.qmd) の概念にも後押しされて急速に浸透しつつある．

Markov 圏は確率論，情報理論，統計学，因果推論に散らばっている基本的な概念に対して，統一的に形式的な定義を与える枠組みとして期待されている．

例えば，「エントロピー」は情報源や通信路が「決定論的」な状態からどれほどかけ離れているか？の指標として特徴付けることができるという [@Perrone2024]．

また Markov 圏上で一般化された形で，Kolmogorov や Hewitt-Savage の 0-1 法則，Blackwell の定理，エルゴード分解定理などが，純粋に代数的に証明されているという [@Perrone2024]．

この独立性の代数・図式的な特徴付けは，[確率的グラフィカルモデル](../Computation/PGM1.qmd) の分野の結果，[@Hammersley-Clifford1971] の定理などと重なる部分も多い．

だが，確率核の概念は，純粋に数学的な文献を除いてまだあまりポピュラーな概念であるとは言えないのが現状であろう．

### カーネル法でいう「カーネル」も確率核

実際，カーネル法でいう「カーネル関数」も，（いつでも [RBF カーネル](../Kernels/Kernel.qmd#sec-Gauss-kernel) のように確率核になるとは限らないが）核の一種である．

第 [-@sec-kernel-as-function] 節で説明するように，核とは可測写像 $K:E\to\cS(F)$ でもある．ただし，$\cS(F)$ は符号付き測度の集合とした．

$\cS(F)$ は極めて大きい空間である．例えば $F$ 上の $\sigma$-有限測度 $\nu\in\cS(F)$ を１つ定める毎に，Radon-Nikodym の定理により Banach 空間の同型
$$
L^1(\nu)\iso\cS^1(F)\mono\cS(F)
$$
が引き起こされる．

[カーネル法](../../2023/KernelMethods/KernelMethods4Mathematicians.qmd) とは，核 $K:E\to\cS(F)$ に沿って $E$ 上の点を $\cS(F)$ 上に埋め込む方法である．

さらに $K$ が半正定値関数が定める変換であった場合，再生核 Hilbert 空間の理論により，$\cS(F)$ の部分空間として，内積が $K$ の計算だけで効率的に計算できるようなものが選び出せる．

こうして，$E$ 上のデータ解析を $\cS(F)$ 上に写す非線型対応を導く，数学的に統一された方法が[カーネル法](../Kernels/Kernel.qmd)である（例 [-@sec-exp-kernel] 節も参照）．

### 圏論についての補足

なお，**射** という用語も，代数幾何と代数トポロジーから多くの数学分野へ浸透した感があるが，近年は純粋数学のコミュニティからも出つつあると感じられる．

「射」とは代数系の準同型の概念を一般化したものであり，「対象」と共に [圏](https://ncatlab.org/nlab/show/category) (category) という代数系の構成要素である．

一般にある対象とある射が圏をなすと言ったとき，その射は，対象の何らかの数学的構造を「保存」する働きを持つと理解される．例えば線型空間における線型写像，順序集合における単調写像，多様体における可微分写像，群や環における準同型が，それぞれの圏における「射」にあたる．

一方で，可測空間や確率空間で可測写像を射に取ると，壊滅的に実りのない圏ができる．一体どうしてだろうか？

### 圏論と現代数学

数学的対象を中心に据えて数学を整理した [Bourbaki](https://ja.wikipedia.org/wiki/ニコラ・ブルバキ) が現代数学の始まりであるという共通認識は一定に確立されている．

しかし近年，実は射の方が重要な対象なのではないか，という共通了解もできつつある：

> 余談だが、homomorphism の訳語として、準同形ということばが定着している。これは、同形もどきという意味だから、同形がだいじというブルバキの思想を反映したものといえよう。射のほうが基本的という、より現代的な視点にはそぐわないが、いまさら変えることもできないだろう。[@斎藤毅2010]

例えば距離空間の射には選択の余地がある．連続関数を取るか，一様連続写像と取るか，[非拡大写像](https://ncatlab.org/nlab/show/short+map)を取るかで，圏の振る舞いは全て違う．連続写像と取った場合は，位相空間の圏の充満部分圏になる．つまり，位相構造以外の構造は無理される．一様連続写像を取ると，完備性も見るようになる．非拡大写像を取ると，距離構造の全てが保存されるようになる．

このようにして，Bourbaki は集合の上に構造を添加していく描像を数学に持ったが，現代的には射の選択によって構造を選択していると理解するのである．

### 圏論から見た「確率核」

ここで，確率空間の圏において，射を確率核に取ると，極めて豊かな構造を持った圏 $\Stoch$ を得る．これは [Markov category](../../2023/Probability/MarkovCategory.qmd) の１つとして調べられている．

すなわち，**確率空間の実体は，その可測空間としての構造にはないと言うべきである**．実際，測度論が確率論において頻出するにも拘らず極めて非本質的に感じられることは，統計を営むものである一定の一致を得るだろう．

この確率核と，これがなす圏の構造を調べることで，「確率空間」を「確率空間」たらしめるものは何か？が考えられている．この分野を[綜合的確率論](https://ncatlab.org/nlab/show/synthetic+probability+theory) (synthetic probability theory) という [@Fritz2020]．

### 関連ページ

::: {#kernel-listing}
:::

## 核の定義と性質

### 定義 {#sec-def-kernel}

::: {.callout-tip icon="false" title="定義 (kernel, probability kernel / Markov kernel)"}

２つの可測空間 $(E,\mathcal{E}),(F,\mathcal{F})$ について，

1. （非負）**核** $K:E\to F$ とは，関数 $E\times\mathcal{F}\to[0,\infty]$ であって次の２条件を満たすものをいう：[^1]

    a. 任意の $x\in E$ に対して，$K(x,-):\mathcal{F}\to[0,\infty]$ は測度を定める．[^2]
    b. 任意の $A\in\mathcal{F}$ に対して，$K(-,A):E\to[0,\infty]$ は可測関数である．

2. 更に (1) で $K(x,F)=1\;(x\in E)$ も成り立つとき，これを **Markov 核** または **確率核** という．[^3]

3. 核 $K:E\times\mathcal{F}\to[0,\infty]$ が **有界** であるとは，$\sup_{x\in E}\|K(x,F)\|<\infty$ を満たすことをいう．[^4] すなわち，$E\to M^1(F)$ が有界な像を持つことをいう．

4. $E$ が確率空間でもあるとき，核は **ランダム測度** に等価である．[^5]

[^1]: [@Jacod-Shiryaev2003] p.65，[@Kolokoltsov2011-Generators] 3.5節 p.110, [@Klenke2020] 8.3節 p.204 では transition kernel，[@Dellacherie-Meyer1988] p.1，[@Revuz-Yor1999] 定義III.1.1.1 p.79，[@Revuz1984] 定義1.1.1.1 p.8，[@Kallenberg2017] p.16, [@Bass2011] 定義19.2 p.154 では kernel と呼んでいる．
[^2]: [@Revuz1984] 定義1.1.1.1 p.8 では符号付き測度であることを許しているが，我々はその場合は **符号付き核** と呼ぶこととしよう．
[^3]: [@Crisan-Doucet2002] p.737 では Markov transition kernel，[@DelMoral04-FeynmanKacFormulae] p.9 では Markov kernel，[@Kolokoltsov2011-Generators] 3.5節 p.110 では transition probability kernel or simply probability kernel と呼び，[@Chopin-Papaspiliopoulos20-SMC] 定義4.1 p.36, [@Bremaud20-Processes] 3.3.3節 p.135 では propability kernel，[@Kulik2018] p.25 では probability kernel としてさらに半群性も満たす族を transition probability kernels と呼ぶ．[@LeGall2016] pp.151-152 は Markovian transition kernel と transition semigroup と呼ぶ．[@Dellacherie-Meyer1988] p.2 は Markovian kernel．[@Kallenberg2017] p.29 と [@Hairer2021-Convergence] では可測関数 $E\to\mathcal{P}(F)$ と定義しており，transition kernel と呼んでしまう．
[^4]: [@Dellacherie-Meyer1988] p.2，[@Kolokoltsov2011-Generators] 3.5節 p.110．[@DelMoral04-FeynmanKacFormulae p.9] は (bounded) integral operator と呼ぶ．
[^5]: [@Kolokoltsov2011-Generators p.110] 3.5節 も参照．

:::

核には積と呼ぶべき結合的な演算が定まる．

::: {.callout-tip title="定義（核の合成と積）^[[@鎌谷研吾2021 p.382] の呼称に一致．[@Dellacherie-Meyer1988 p.4] は composition，[@Gikhman-Skorokhod2004I p.76] 定理II.4.1 は畳み込みと呼ぶ．]" icon="false"}
$E,F,G$ を可測空間とする．

1. 核 $S:F\to G$ に対して，**合成** $T\otimes S:E\to F\times G$ を
    $$(T\otimes S)(x,A\times B):=\int_AT(x,dy)S(y,B),\qquad(x\in E,A\in\F,B\in\cG),$$
    で定める．
2. **積** $TS:E\to G$ を
    $$(TS)(x,B):=(T\otimes S)(x,F\times B)=\int_FT(x,dy)S(y,B),\qquad(x\in E,B\in\cG),$$
    で定める．
:::

::: {.callout-note appearance="simple" icon="false"}

核は積に関して結合的である：^[これは一般の符号付き核については成り立たない [@Revuz1984 p.12]．]
$$(RS)T=R(ST).$$

:::

このことにより，確率空間を対象とし，確率核を射とする圏が定まることになる．これを $\Stoch$ と呼ぼう．単位射は後述の $K_{\id_E}$ が与える．

### 核の例 {#sec-exp-kernel}

核は極めて多くの重要な概念を一般化し，統一的な見方を提供してくれる．

まずなんといっても，確率核は確率行列の無限次元への一般化と捉えられる：

::: {.callout-warning appearance="simple" icon="false" title="確率行列としての確率核"}

$E,F$ が有限集合であるとき，$\cP(E),\cP(F)$ は行ベクトルの空間と見れる．

すると確率核は（行／右）[確率行列](https://ja.wikipedia.org/wiki/確率行列) $P$ と等価になる．

次節で定義する核の作用も，列ベクトル $x_t\in\R^E$ と行ベクトル $\mu_t$ に関する行列積と等価になる：
$$
x_{t+1}=Px_t,\qquad \mu_{t+1}=\mu_t P.
$$

:::

さらに，**正則な**条件付き確率とは，条件付き確率 $P:E\times\cF\to[0,1]$ が確率核になることに他ならない：

::: {.callout-warning appearance="simple" icon="false" title="正則条件付き確率は確率核^[[@Jacod-Shiryaev2003 p.65]，[@Klenke2020 p.205] 8.3節．]"}

$Y\in\L(\Om;E)$ を確率変数，$\cG\subset\F$ を部分 $\sigma$-代数とする．
$Y$の$\cG$の下での **正則条件付き確率** とは，次を満たす確率核 $\kappa_{Y,\cG}:\Om\times\cE\to[0,1]$ をいう：
$$
\kappa_{Y,\cG}(\om,B)=\E[1_{\Brace{Y\in B}}\mid\cG](\om)\;\P\das\qquad B\in\cE.
$$

:::

::: {.callout-warning appearance="simple" icon="false" title="測度は退化した核である"}

測度とは一点集合からの核 $\nu:\{*\}\to E$ と考えられる．すなわち，一点集合は圏 $\Stoch$ の終対象である．

:::

続いて，そもそも核は決定論的な対象も包含する概念であることを見る：

::: {.callout-warning appearance="simple" icon="false" title="関数も退化した確率核である^[[@Dellacherie-Meyer1988] 7 p.4，[@Revuz1984 p.9]，[@Revuz1984 p.13] 演習1.13．]"}

$f:E\to F$ を関数とする．デルタ測度への埋め込み $\delta:F\mono\cP(F)$ に沿って $f$ は確率核 $E\to\cP(F)$ とみなせる：
$$
K_f(x,-):=\delta_{f(x)}(-).
$$

$F=E,f=\id_E$ とした場合の $K_f$ が $E$ の自己射である．

:::

$k:E\times E\to\bC$ を半正定値関数とすると，[@Moore39-GeneralAnalysis2] の定理から，ただ一つの再生核 Hilbert 空間 $H\subset\bC^E$ が存在して $k$ を核に持つ．

このとき，特徴写像 $\Phi:E\to H$ は関数である．理想的には全単射であり，カーネルトリック
$$
(\Phi(x)|\Phi(y))=k(x,y)
$$
を通じて $E$ 上のデータ解析を $H$ 上に押し出す．

::: {.callout-warning appearance="simple" icon="false" title="関数の積も核である"}

$f,k:E\to\R$ を関数とする．

核を $K(x,-):=k(x)\delta_x$ と定めると，$K$ による作用とは $k$ との積に一致する：
$$
Kf(x)=\int_Ek(x)\delta_x(dy)f(y)=k(x)f(x).
$$

:::

これをさらに一般化すると，「核」の語源に辿り着く：

::: {.callout-warning appearance="simple" icon="false" title="積分変換は核を定める^[[@Dellacherie-Meyer1988 p.5] 7，[@Revuz1984 p.9]，[@Dellacherie-Meyer1988 p.2]．]"}

$\lambda\in\cM(E)$ を測度，$k\in\L(E\times E)$ を関数とする．このとき，
$$
K(x,A):=\int_Ak(x,y)\lambda(dy),\qquad x\in E,A\in\cE,
$$
は $E$ 上の（符号付き）核を定める．

すなわち，$K$ が測度 $\lambda$ に関して密度 $k$ を持つとき，これを $k$ を **積分核** とする基底 $\lambda$ に関する積分変換という．

:::

### 確率核の作用 {#sec-kernel-action}

::: {.callout-tip icon="false" title="確率核の作用^[作用は [@Hairer2021-Convergence], [@Kallenberg2017 p.16], [@Dellacherie-Meyer1988 pp.2-3] が同様に定めている．最後の文献によると，この記法は Hunt によるものだという．$T\otimes S$ の存在は [@Gikhman-Skorokhod2004I p.76] 定理II.4.1 で示されており，$\otimes$ を **直積**，$\cdot$ を **畳み込み** と呼んでいる．]"}

核は写像 $E\to\cM(F)$ と見れるため，その全体は自然に実線型空間をなす．これを $\Hom_\Stoch(E,F)$ と表す．

1. **右作用** $\cS(E)\times\Hom_\Stoch(E,F)\to\cS(E)$ を
   $$(\mu T)(A):=\int_E\mu(dx)T(x,A),\qquad A\in\F,$$
   で定める．

2. **左作用** $\Hom_\Stoch(E,F)\times\L(F)\to\L(E)$ を
   $$(Tf)(x):=\int_FT(x,dy)f(y),\qquad x\in E,$$
   で定める．^[これが $\cE$-可測であることは，$f$ の単関数近似を考えることで示せる [@Dellacherie-Meyer1988 p.2]．]

:::

::: {.callout-warning appearance="simple" icon="false" title="決定論的な確率核の作用"}
関数 $f$ が定める核 $K_f:E\to E$ は $\L(E)$ に $f$ の **前合成** として作用し，$\S(E)$ に $f$ による **押し出し** として作用する：
$$
\begin{align*}
K_fg(x)&=\int_F K_f(x,dy)g(y)=\int_F\delta_{f(x)}(dy)g(y)=g\circ f(x),\\
\mu K_f(A)&=\int_E\mu(dx)K_f(x,A)=\int_E\mu(dx)\delta_{f(x)}(A)\\
&=\mu(f^{-1}(A))=f_*\mu(A).
\end{align*}
$$
:::

::: {.callout-warning appearance="simple" icon="false" title="畳み込みは強 Feller 核である^[[@Revuz1984 p.10]．p.36 も参照．]"}

$\pi\in\cM(\R^d)$ を測度として，核 $K$ を
$$
K(x,A):=(\pi*\delta_x)(A)=\int_{\R^d}\delta_x(A-y)\pi(dy)
$$
と定めると，$K$ の右作用は測度同士の畳み込みを定める：
$$
\begin{align*}
Kf(x)&=\int_{\R^d}K(x,dz)f(z)=\int_{\R^d}\int_{\R^d}\delta_x(dz-y)\pi(dy)f(z)=\int_{\R^d}f(x+y)\pi(dy),\\
\mu K(A)&=\int_{\R^d}\mu(dx)K(x,A)=\int_{\R^d}\int_{\R^d}\mu(dx)\delta_x(A-y)\pi(dy)\\
&\hphantom{=\int_{\R^d}\mu(dx)K(x,A)}=\int_{\R^d}\mu(A-y)\pi(dy)=\pi*\mu(A).
\end{align*}
$$

実は畳み込み核は強 Feller である．すなわち，任意の有界可測関数 $f\in\L_b(E)$ に対して，$Kf\in C(E)$ は連続である．^[[@Revuz1984 p.36]，[@Revuz-Yor1999 p.412]．]

:::

::: {.callout-note icon="false" collapse="true" title="証明"}
任意の $x_1,x_2\in E$ について，$f\in\L_b(E)$ であるから，有界収束定理より
$$
\abs{Kf(x_1)-Kf(x_2)}\le\int_E\abs{f(x_1+y)-f(x_2+y)}\pi(dy)\xrightarrow{x_2\to x_1}0.
$$
:::

::: {.callout-note appearance="simple" icon="false" title="核の自己随伴性^[(1)は [@Revuz1984 p.9] と [@Dellacherie-Meyer1988 5 p.3]，(2)は [@Dellacherie-Meyer1988 7 p.4]．]"}

自然なペアリング $(-|-):\cS(E)\times\L(F)\to[-\infty,\infty]$ に関して，核 $T$ は（両辺が意味を持つ限り）自己随伴性を満たす：
$$(\mu T|f)=(\mu|Tf).$$
   
また，$(MN)f=M(Nf)$ も成り立つ．
:::

::: {.callout-note icon="false" collapse="true" title="証明"}

Fubini の定理より，次のように式変形できる：
\begin{align*}
    (\mu|Pf)&=\int_EPf(x)\mu(dx)=\int_E\int_FP(x,dy)f(y)\mu(dx)\\
    &=\int_F\int_E\mu(dx)P(x,dy)f(y)=\int_F\mu P(dy)f(y)=(\mu P|f).
\end{align*}

:::

確率核の２つの作用は，作用素として非拡大的である．ただし，$\L_b(E)$ 上に一様ノルム，$\cP(E)$ 上に全変動ノルムを考えるとする：

::: {.callout-note icon="false" title="確率核の作用の非拡大性^[[@Revuz1984 p.12]．]" appearance="simple"}
$P$ を確率核とする．

1. 左作用 $P:\L_b(E)\to\L_b(E)$ は非拡大写像を定める：$\|Pf\|_\infty\le\|f\|_\infty$．
2. 右作用 $P^*:\cP(E)\to \cP(F)$ も非拡大写像を定める：$\|\mu P\|_\TV\le\|\mu\|_\TV$．
:::

::: {.callout-note icon="false" collapse="true" title="証明"}
\begin{align*}
    \sup_{x\in E}|Pf(x)|&=\sup_{x\in E}\left|\int_EP(x,dy)f(y)\right|\le\|f\|_\infty\sup_{x\in E}\int_EP(x,dy)=\|f\|_\infty.
\end{align*}
:::

## 確率核の特徴付け

### 関数としての確率核 {#sec-kernel-as-function}

$F$ が可分距離空間であるとき，確率核とは本質的に可測関数 $E\to\cP(F)$ である．

::: {.callout-note appearance="simple" icon="false" title="核の関数としての可測性^[[@Kallenberg2017 p.30] 補題1.14 では Borel 空間について示している．[@Hairer2021-Convergence] ではあらかじめ (2) を定義としている．[@DelMoral04-FeynmanKacFormulae p.7] は最初からこれによって $\sigma$-代数を定義する．[@Ambrosio+2008 p.121] も初めからこれを通じて，可分距離空間 $Y$ に対する Borel 写像 $X\to\cP(Y)$ を定義する．(3) は [@Ambrosio+2008 p.121]．]"}
$F$ を距離化可能とする．このとき，関数 $E\times\B(F)\to[0,1]$ について，(2)$\Rightarrow$(1) が成り立ち，$F$ が可分であるとき (1)$\Rightarrow$(2) も成り立ち，２つは同値になる：

1. $E\times\B(F)\to[0,1]$ は確率核である．
2. $E\to\cP(F)$ は可測である．

(2) が成り立つとき，
$$x\in E\mapsto\int_Ff(x,y)P(x,dy),\qquad f\in\L_b(E\times F)$$
も可測である．
:::

::: {.callout-note icon="false" collapse="true" title="証明"}

* (2)$\Rightarrow$(1)

    $\sigma[\{\ev_B\}_{B\in\B(F)}]\subset\B(F)$ が成り立つから，任意の $B\in\B(F)$ について合成 $P(-,B):E\to\cP(F)\xrightarrow{\ev_B}[0,1]$ が可測．

* (1)$\Rightarrow$(2) 

    $F$ が可分に距離化可能であるとき，$\B(F)=\sigma[\{\ev_B\}_{B\in\B(F)}]$ が成り立つから，$E\to\cP(F)$ が可測であることは，任意の $B\in\B(F)$ について合成 $P(-,B):E\to\cP(F)\xrightarrow{\ev_B}[0,1]$ が可測であることに同値．
:::

### 作用素としての確率核

::: {.callout-note appearance="simple" icon="false" title="$\mathcal{P}(E)$ を不変にする線型作用は確率核である^[[@Hairer2018 p.8] 演習2.34．]"}

$E$ をPolish空間，$T:\cS^1(E)\to\cS^1(E)$ を線型作用素で，$T(\cP(E))\subset\cP(E)$ を満たすとする．
このとき，ある確率核 $P$ が存在して，$T$ はその作用である：
$$
T\mu(A)=\int_E P(x,A)\mu(dx).
$$

:::

さらに進んで，次が成り立つ：

::: {.callout-note appearance="simple" icon="false" title="核の作用の特徴付け^[[@Revuz1984 p.9] 命題1.3．]"}
$(E,\cE)$ を可測空間，$K:\L(E)\to\L(E)$ を正な線型写像とする．このとき，次は同値：

1. $K$ はある核の作用である．
2. 単調収束定理：任意の増加列 $\{f_n\}\subset\L(E)_+$ に対して，
$$
K\paren{\lim_{n\to\infty}f_n}=\lim_{n\to\infty}Vf_n.
$$
:::