---
title: "Unreasonable Effectiveness of Measure Theory"
author: "司馬 博文"
date: 5/7/2024
categories: [Opinion]
toc: true
number-sections: true
code-block-bg: true
code-block-border-left: "#5AB5BA"
code-overflow: wrap
code-fold: true
bibliography: 
    - ../../../mathematics.bib
    - ../../../bib.bib
csl: ../../../apa.csl
crossref:
    sec-prefix: 節
    eq-prefix: 式
    def-prefix: 定義
    def-title: 定義
    thm-prefix: 定理
    thm-title: 定理
    fig-prefix: 図
    fig-title: 図
---

{{< include ../../../_preamble.qmd >}}

Some say that measure theory is the most 'ugly' subject among all the branches of undergraduate mathematics.

I guess most people can agree with that to some extent. Measure theory is a subject that is full of technical details, and it is not as intuitive as  other topics in calculus.

However, the point is that we can hardly avoid measure theory when studying probability theory. On the contrary, measure theoretic details become increasingly demanding as we go deeper into the inquiry of stochastic processes.

One illustrative example is the martingale formulation of diffusion processes initiated by [@Stroock-Varadhan1969].

As it turned out, the probabilistic treatment of diffusion processes has the furthest-reaching consequences compared to other approaches, such as Kolmogorov's forward and backward equations, infinitesimal generator, and Ito's SDE.

It is remarkable that all the results obtained by classical analysis are superseded by those derived from the probabilistic approach, which is a field entirely based on measure theory.

> In fact, the martingale formulation bears the same sort of relation to the stochastic differential equation as an integral equation does to a differential equation. This analogy is deeper than may be apparent at first sight. Indeed, as with an integral equation, the relations implied by the martingale formulation are much more stable than those implied by the stochastic differential equation. [@Stroock-Varadhan1969 p.348]