---
title: "Skilling-Hutchinson の跡推定量"
author: "司馬博文"
image: Images/Skilling-Hutchinson.svg
date: 8/20/2024
date-modified: 8/22/2024
categories: [Probability, Functional Analysis]
bibliography: 
    - ../../../assets/mathematics.bib
    - ../../../assets/bib.bib
    - ../../../assets/bib1.bib
csl: ../../../assets/apalike.csl
abstract-title: 概要
abstract: Skilling-Hutchinson の跡推定量は，跡の計算 $O(d^2)$ を $O(d)$ に落とすことができる Monte Carlo 法である．
listing: 
    -   id: lst-listing
        type: grid
        sort: false
        contents:
            - "../Samplers/NF.qmd"
            - "../Samplers/NF1.qmd"
            - "../Samplers/EBM.qmd"
        date-format: iso
        fields: [title,image,date,subtitle]
---

{{< include ../../../assets/_preamble.qmd >}}

## 命題

::: {.callout-tip title="[@Skilling1989]-[@Hutchinson1990]" icon="false"}

任意の正方行列 $A\in M_n(\R)$ と，$\V[X]=I_n$ を満たす確率ベクトル $X\in\L(\Om;\R^n)$ について，

$$
\Tr(A)=\E[X^\top AX].
$$

:::

::: {.callout-note title="証明" icon="false" collapse="true"}

$$
X^\top AX=\Tr(AXX^\top)
$$
に注意する．これは，一般に $x,y\in\R^n$ に対して
$$
yx^\top=\vctrr{y_1}{\vdots}{y_n}(x_1\;\cdots\;x_n)=\begin{pmatrix}y_1x_1&\cdots&y_1x_n\\\vdots&\ddots&\vdots\\y_nx_1&\cdots&y_nx_n\end{pmatrix}
$$
$$
\therefore\qquad\Tr(yx^\top)=x^\top y
$$
が成り立つためである．

よって，次のように計算できる：

\begin{align*}
    \E[X^\top AX]&=\E[\Tr(AXX^\top)]\\
    &=\Tr(\E[AXX^\top])\\
    &=\Tr(A\E[XX^\top])=\Tr(A).
\end{align*}

:::

[@Hutchinson1990] では $A$ を対称行列に，$X$ を中心化された確率変数に限って示されている．

[@Skilling1989] では [@Hutchinson1990] のように命題の形では提示していないが，同様の推定量を提案しており，これと一般化跡 (generalized trace) と Chebyshev 多項式の議論を通じて，$A$ のスペクトルのベイズ推定を議論している．

## 推定量の性質

実用上，$X$ の分布は標準 Gauss や Rademacher 分布などが用いられる．

::: {.callout-tip title="命題（推定量の分散）" icon="false"}

$A\in S_n(\R)$ を対称行列とする．

1. $X\sim\rN(0,I_n)$ のとき，
    $$
    \V[X^\top AX]=2\Tr(A^2)=2\norm{A}^2_\HS.
    $$

2. $X\sim\Rad^{\otimes n}$ のとき，
    $$
    \V[X^\top AX]=2\sum_{i\ne j}a_{ij}^2.
    $$

:::

::: {.callout-note title="証明^[[@Hutchinson1990 p.437], [@Avron-Toledo2011 補題9], [@Adams+2018 命題4.2] も参照．]" icon="false" collapse="true"}

1. $A\in S_n(\R)$ が正定値対称であるとき，ある直交行列 $U\in O_n(\R)$ と対角行列 $\Lambda=\diag(\lambda_1,\dots,\lambda_n)$ が存在して，
    $$
    A=U\Lambda U^\top.
    $$
    $Y:=U^\top X$ と定めるとやはり $Y\sim\rN(0,I_n)$ であり，
    $$
    X^\top AX=X^\top U\Lambda U^\top X=Y^\top\Lambda Y,
    $$
    $$
    \therefore\qquad\V[X^\top AX]=2\sum_{i=1}^n\lambda_i^2=2\Tr(\Lambda^2)=2\Tr(A^2).
    $$
2. 一般の $X\in\L(\Om;\R^n)$ に関して，
    $$
    \V[X^\top AX]=\sum_{i,j,k,l=1}^na_{ij}a_{kl}\Paren{\E[X_iX_jX_kX_l]-\E[X_iX_j]\E[X_kX_l]}.
    $$
:::

::: {.callout-tip title="系" icon="false"}

$A$ が対称行列で $\E[X]=0$ であるとき，$X$ は Rademacher とした場合が最小分散不偏推定量を定める [@Hutchinson1990 命題1]．

:::

## 応用

::: {#lst-listing}
:::

* [残差フロー (residual flow)](../Samplers/NF.qmd#sec-Hutchinson) では Jacobian の推定が焦点になる．これに Skilling-Hutchinson の跡推定量を用いることができる．
* [Neural ODE](../Samplers/NF1.qmd) において，Jacobian の跡 $\Tr(J_{F_t}(x_t))$ の計算は Skilling-Hutchinson の跡推定量を用いれば $O(d)$ で済む [@Grathwohl+2019]．
* [Sliced Score Matching](../Samplers/EBM.qmd#sec-SSM) の目的関数は，Skilling-Hutchinson の跡推定量により Jacobian $Ds_\theta$ を推定したスコアマッチングと解釈できる．

## 文献紹介 {.appendix}

<!-- [@Grathwohl+2019] も参考にした． -->

[@Adams+2018] では [@Skilling1989] の研究を踏襲し，大規模行列のスペクトル（密度）推定に向けて，Skilling-Hutchinson の跡推定量の拡張が議論されている．